package datapro.eibs.beans;

import datapro.eibs.sockets.*;
import java.io.*;
import java.math.*;

import java.util.*;

/**
* Class generated by AS/400 CRTCLASS command from ECC009003 physical file definition.
* 
* File level identifier is 1061120151342.
* Record format level identifier is 3FB2C8983BB03.
*/

public class ECC009003Message extends MessageRecord
{
  final static String fldnames[] = {
                                     "H03USERID",
                                     "H03PROGRM",
                                     "H03TIMSYS",
                                     "H03SCRCOD",
                                     "H03OPECOD",
                                     "H03FLGMAS",
                                     "H03FLGWK1",
                                     "H03FLGWK2",
                                     "H03FLGWK3",
                                     "E03TARTYP",
                                     "E03TARTYPA",
                                     "E03CCRNUM",
                                     "E03CCRNUMA",
                                     "E03CCRNEW",
                                     "E03PRICUN",
                                     "E03PRICUNA",
                                     "E03PRINA1",
                                     "E03PRINA1A",
                                     "E03CCRCID",
                                     "E03CCRCIDA",
                                     "E03CCRTYP",
                                     "E03CCRISM",
                                     "E03CCRISD",
                                     "E03CCRISY",
                                     "E03CCRDLM",
                                     "E03CCRDLD",
                                     "E03CCRDLY",
                                     "E03CCREXM",
                                     "E03CCREXD",
                                     "E03CCREXY",
                                     "E03CCRISMA",
                                     "E03CCRISDA",
                                     "E03CCRISYA",
                                     "E03CCRDLMA",
                                     "E03CCRDLDA",
                                     "E03CCRDLYA",
                                     "E03CCREXMA",
                                     "E03CCREXDA",
                                     "E03CCREXYA",
                                     "E03CCRATG",
                                     "E03CCRSTS",
                                     "E03CCRDSC",
                                     "E03CCRSTSA",
                                     "E03CCRDSCA",
                                     "E03CCRUSR",
                                     "E03CCRUSRA",
                                     "E03CCRBRN",
                                     "E03CCRBRNA"
                                   };
  final static String tnames[] = {
                                   "H03USERID",
                                   "H03PROGRM",
                                   "H03TIMSYS",
                                   "H03SCRCOD",
                                   "H03OPECOD",
                                   "H03FLGMAS",
                                   "H03FLGWK1",
                                   "H03FLGWK2",
                                   "H03FLGWK3",
                                   "E03TARTYP",
                                   "E03TARTYPA",
                                   "E03CCRNUM",
                                   "E03CCRNUMA",
                                   "E03CCRNEW",
                                   "E03PRICUN",
                                   "E03PRICUNA",
                                   "E03PRINA1",
                                   "E03PRINA1A",
                                   "E03CCRCID",
                                   "E03CCRCIDA",
                                   "E03CCRTYP",
                                   "E03CCRISM",
                                   "E03CCRISD",
                                   "E03CCRISY",
                                   "E03CCRDLM",
                                   "E03CCRDLD",
                                   "E03CCRDLY",
                                   "E03CCREXM",
                                   "E03CCREXD",
                                   "E03CCREXY",
                                   "E03CCRISMA",
                                   "E03CCRISDA",
                                   "E03CCRISYA",
                                   "E03CCRDLMA",
                                   "E03CCRDLDA",
                                   "E03CCRDLYA",
                                   "E03CCREXMA",
                                   "E03CCREXDA",
                                   "E03CCREXYA",
                                   "E03CCRATG",
                                   "E03CCRSTS",
                                   "E03CCRDSC",
                                   "E03CCRSTSA",
                                   "E03CCRDSCA",
                                   "E03CCRUSR",
                                   "E03CCRUSRA",
                                   "E03CCRBRN",
                                   "E03CCRBRNA"
                                 };
  final static String fid = "1061120151342";
  final static String rid = "3FB2C8983BB03";
  final static String fmtname = "ECC009003";
  final int FIELDCOUNT = 48;
  private static Hashtable tlookup = new Hashtable();
  private CharacterField fieldH03USERID = null;
  private CharacterField fieldH03PROGRM = null;
  private CharacterField fieldH03TIMSYS = null;
  private CharacterField fieldH03SCRCOD = null;
  private CharacterField fieldH03OPECOD = null;
  private CharacterField fieldH03FLGMAS = null;
  private CharacterField fieldH03FLGWK1 = null;
  private CharacterField fieldH03FLGWK2 = null;
  private CharacterField fieldH03FLGWK3 = null;
  private CharacterField fieldE03TARTYP = null;
  private CharacterField fieldE03TARTYPA = null;
  private CharacterField fieldE03CCRNUM = null;
  private CharacterField fieldE03CCRNUMA = null;
  private CharacterField fieldE03CCRNEW = null;
  private DecimalField fieldE03PRICUN = null;
  private DecimalField fieldE03PRICUNA = null;
  private CharacterField fieldE03PRINA1 = null;
  private CharacterField fieldE03PRINA1A = null;
  private CharacterField fieldE03CCRCID = null;
  private CharacterField fieldE03CCRCIDA = null;
  private CharacterField fieldE03CCRTYP = null;
  private DecimalField fieldE03CCRISM = null;
  private DecimalField fieldE03CCRISD = null;
  private DecimalField fieldE03CCRISY = null;
  private DecimalField fieldE03CCRDLM = null;
  private DecimalField fieldE03CCRDLD = null;
  private DecimalField fieldE03CCRDLY = null;
  private DecimalField fieldE03CCREXM = null;
  private DecimalField fieldE03CCREXD = null;
  private DecimalField fieldE03CCREXY = null;
  private DecimalField fieldE03CCRISMA = null;
  private DecimalField fieldE03CCRISDA = null;
  private DecimalField fieldE03CCRISYA = null;
  private DecimalField fieldE03CCRDLMA = null;
  private DecimalField fieldE03CCRDLDA = null;
  private DecimalField fieldE03CCRDLYA = null;
  private DecimalField fieldE03CCREXMA = null;
  private DecimalField fieldE03CCREXDA = null;
  private DecimalField fieldE03CCREXYA = null;
  private CharacterField fieldE03CCRATG = null;
  private CharacterField fieldE03CCRSTS = null;
  private CharacterField fieldE03CCRDSC = null;
  private CharacterField fieldE03CCRSTSA = null;
  private CharacterField fieldE03CCRDSCA = null;
  private CharacterField fieldE03CCRUSR = null;
  private CharacterField fieldE03CCRUSRA = null;
  private DecimalField fieldE03CCRBRN = null;
  private DecimalField fieldE03CCRBRNA = null;

  /**
  * Constructor for ECC009003Message.
  */
  public ECC009003Message()
  {
    createFields();
    initialize();
  }

  /**
  * Create fields for this message.
  * This method implements the abstract method in the MessageRecord superclass.
  */
  protected void createFields()
  {
    recordsize = 357;
    fileid = fid;
    recordid = rid;
    message = new byte[getByteLength()];
    formatname = fmtname;
    fieldnames = fldnames;
    tagnames = tnames;
    fields = new MessageField[FIELDCOUNT];

    fields[0] = fieldH03USERID =
    new CharacterField(message, HEADERSIZE + 0, 10, "H03USERID");
    fields[1] = fieldH03PROGRM =
    new CharacterField(message, HEADERSIZE + 10, 10, "H03PROGRM");
    fields[2] = fieldH03TIMSYS =
    new CharacterField(message, HEADERSIZE + 20, 12, "H03TIMSYS");
    fields[3] = fieldH03SCRCOD =
    new CharacterField(message, HEADERSIZE + 32, 2, "H03SCRCOD");
    fields[4] = fieldH03OPECOD =
    new CharacterField(message, HEADERSIZE + 34, 4, "H03OPECOD");
    fields[5] = fieldH03FLGMAS =
    new CharacterField(message, HEADERSIZE + 38, 1, "H03FLGMAS");
    fields[6] = fieldH03FLGWK1 =
    new CharacterField(message, HEADERSIZE + 39, 1, "H03FLGWK1");
    fields[7] = fieldH03FLGWK2 =
    new CharacterField(message, HEADERSIZE + 40, 1, "H03FLGWK2");
    fields[8] = fieldH03FLGWK3 =
    new CharacterField(message, HEADERSIZE + 41, 1, "H03FLGWK3");
    fields[9] = fieldE03TARTYP =
    new CharacterField(message, HEADERSIZE + 42, 1, "E03TARTYP");
    fields[10] = fieldE03TARTYPA =
    new CharacterField(message, HEADERSIZE + 43, 1, "E03TARTYPA");
    fields[11] = fieldE03CCRNUM =
    new CharacterField(message, HEADERSIZE + 44, 20, "E03CCRNUM");
    fields[12] = fieldE03CCRNUMA =
    new CharacterField(message, HEADERSIZE + 64, 20, "E03CCRNUMA");
    fields[13] = fieldE03CCRNEW =
    new CharacterField(message, HEADERSIZE + 84, 20, "E03CCRNEW");
    fields[14] = fieldE03PRICUN =
    new DecimalField(message, HEADERSIZE + 104, 10, 0, "E03PRICUN");
    fields[15] = fieldE03PRICUNA =
    new DecimalField(message, HEADERSIZE + 114, 10, 0, "E03PRICUNA");
    fields[16] = fieldE03PRINA1 =
    new CharacterField(message, HEADERSIZE + 124, 35, "E03PRINA1");
    fields[17] = fieldE03PRINA1A =
    new CharacterField(message, HEADERSIZE + 159, 35, "E03PRINA1A");
    fields[18] = fieldE03CCRCID =
    new CharacterField(message, HEADERSIZE + 194, 15, "E03CCRCID");
    fields[19] = fieldE03CCRCIDA =
    new CharacterField(message, HEADERSIZE + 209, 15, "E03CCRCIDA");
    fields[20] = fieldE03CCRTYP =
    new CharacterField(message, HEADERSIZE + 224, 4, "E03CCRTYP");
    fields[21] = fieldE03CCRISM =
    new DecimalField(message, HEADERSIZE + 228, 3, 0, "E03CCRISM");
    fields[22] = fieldE03CCRISD =
    new DecimalField(message, HEADERSIZE + 231, 3, 0, "E03CCRISD");
    fields[23] = fieldE03CCRISY =
    new DecimalField(message, HEADERSIZE + 234, 5, 0, "E03CCRISY");
    fields[24] = fieldE03CCRDLM =
    new DecimalField(message, HEADERSIZE + 239, 3, 0, "E03CCRDLM");
    fields[25] = fieldE03CCRDLD =
    new DecimalField(message, HEADERSIZE + 242, 3, 0, "E03CCRDLD");
    fields[26] = fieldE03CCRDLY =
    new DecimalField(message, HEADERSIZE + 245, 5, 0, "E03CCRDLY");
    fields[27] = fieldE03CCREXM =
    new DecimalField(message, HEADERSIZE + 250, 3, 0, "E03CCREXM");
    fields[28] = fieldE03CCREXD =
    new DecimalField(message, HEADERSIZE + 253, 3, 0, "E03CCREXD");
    fields[29] = fieldE03CCREXY =
    new DecimalField(message, HEADERSIZE + 256, 5, 0, "E03CCREXY");
    fields[30] = fieldE03CCRISMA =
    new DecimalField(message, HEADERSIZE + 261, 3, 0, "E03CCRISMA");
    fields[31] = fieldE03CCRISDA =
    new DecimalField(message, HEADERSIZE + 264, 3, 0, "E03CCRISDA");
    fields[32] = fieldE03CCRISYA =
    new DecimalField(message, HEADERSIZE + 267, 5, 0, "E03CCRISYA");
    fields[33] = fieldE03CCRDLMA =
    new DecimalField(message, HEADERSIZE + 272, 3, 0, "E03CCRDLMA");
    fields[34] = fieldE03CCRDLDA =
    new DecimalField(message, HEADERSIZE + 275, 3, 0, "E03CCRDLDA");
    fields[35] = fieldE03CCRDLYA =
    new DecimalField(message, HEADERSIZE + 278, 5, 0, "E03CCRDLYA");
    fields[36] = fieldE03CCREXMA =
    new DecimalField(message, HEADERSIZE + 283, 3, 0, "E03CCREXMA");
    fields[37] = fieldE03CCREXDA =
    new DecimalField(message, HEADERSIZE + 286, 3, 0, "E03CCREXDA");
    fields[38] = fieldE03CCREXYA =
    new DecimalField(message, HEADERSIZE + 289, 5, 0, "E03CCREXYA");
    fields[39] = fieldE03CCRATG =
    new CharacterField(message, HEADERSIZE + 294, 1, "E03CCRATG");
    fields[40] = fieldE03CCRSTS =
    new CharacterField(message, HEADERSIZE + 295, 2, "E03CCRSTS");
    fields[41] = fieldE03CCRDSC =
    new CharacterField(message, HEADERSIZE + 297, 15, "E03CCRDSC");
    fields[42] = fieldE03CCRSTSA =
    new CharacterField(message, HEADERSIZE + 312, 2, "E03CCRSTSA");
    fields[43] = fieldE03CCRDSCA =
    new CharacterField(message, HEADERSIZE + 314, 15, "E03CCRDSCA");
    fields[44] = fieldE03CCRUSR =
    new CharacterField(message, HEADERSIZE + 329, 10, "E03CCRUSR");
    fields[45] = fieldE03CCRUSRA =
    new CharacterField(message, HEADERSIZE + 339, 10, "E03CCRUSRA");
    fields[46] = fieldE03CCRBRN =
    new DecimalField(message, HEADERSIZE + 349, 4, 0, "E03CCRBRN");
    fields[47] = fieldE03CCRBRNA =
    new DecimalField(message, HEADERSIZE + 353, 4, 0, "E03CCRBRNA");

    synchronized (tlookup)
    {
      if (tlookup.isEmpty())
      {
        for (int i = 0; i < tnames.length; i++)
          tlookup.put(tnames[i], new Integer(i));
      }
    }

    taglookup = tlookup;
  }

  /**
  * Set field H03USERID using a String value.
  */
  public void setH03USERID(String newvalue)
  {
    fieldH03USERID.setString(newvalue);
  }

  /**
  * Get value of field H03USERID as a String.
  */
  public String getH03USERID()
  {
    return fieldH03USERID.getString();
  }

  /**
  * Set field H03PROGRM using a String value.
  */
  public void setH03PROGRM(String newvalue)
  {
    fieldH03PROGRM.setString(newvalue);
  }

  /**
  * Get value of field H03PROGRM as a String.
  */
  public String getH03PROGRM()
  {
    return fieldH03PROGRM.getString();
  }

  /**
  * Set field H03TIMSYS using a String value.
  */
  public void setH03TIMSYS(String newvalue)
  {
    fieldH03TIMSYS.setString(newvalue);
  }

  /**
  * Get value of field H03TIMSYS as a String.
  */
  public String getH03TIMSYS()
  {
    return fieldH03TIMSYS.getString();
  }

  /**
  * Set field H03SCRCOD using a String value.
  */
  public void setH03SCRCOD(String newvalue)
  {
    fieldH03SCRCOD.setString(newvalue);
  }

  /**
  * Get value of field H03SCRCOD as a String.
  */
  public String getH03SCRCOD()
  {
    return fieldH03SCRCOD.getString();
  }

  /**
  * Set field H03OPECOD using a String value.
  */
  public void setH03OPECOD(String newvalue)
  {
    fieldH03OPECOD.setString(newvalue);
  }

  /**
  * Get value of field H03OPECOD as a String.
  */
  public String getH03OPECOD()
  {
    return fieldH03OPECOD.getString();
  }

  /**
  * Set field H03FLGMAS using a String value.
  */
  public void setH03FLGMAS(String newvalue)
  {
    fieldH03FLGMAS.setString(newvalue);
  }

  /**
  * Get value of field H03FLGMAS as a String.
  */
  public String getH03FLGMAS()
  {
    return fieldH03FLGMAS.getString();
  }

  /**
  * Set field H03FLGWK1 using a String value.
  */
  public void setH03FLGWK1(String newvalue)
  {
    fieldH03FLGWK1.setString(newvalue);
  }

  /**
  * Get value of field H03FLGWK1 as a String.
  */
  public String getH03FLGWK1()
  {
    return fieldH03FLGWK1.getString();
  }

  /**
  * Set field H03FLGWK2 using a String value.
  */
  public void setH03FLGWK2(String newvalue)
  {
    fieldH03FLGWK2.setString(newvalue);
  }

  /**
  * Get value of field H03FLGWK2 as a String.
  */
  public String getH03FLGWK2()
  {
    return fieldH03FLGWK2.getString();
  }

  /**
  * Set field H03FLGWK3 using a String value.
  */
  public void setH03FLGWK3(String newvalue)
  {
    fieldH03FLGWK3.setString(newvalue);
  }

  /**
  * Get value of field H03FLGWK3 as a String.
  */
  public String getH03FLGWK3()
  {
    return fieldH03FLGWK3.getString();
  }

  /**
  * Set field E03TARTYP using a String value.
  */
  public void setE03TARTYP(String newvalue)
  {
    fieldE03TARTYP.setString(newvalue);
  }

  /**
  * Get value of field E03TARTYP as a String.
  */
  public String getE03TARTYP()
  {
    return fieldE03TARTYP.getString();
  }

  /**
  * Set field E03TARTYPA using a String value.
  */
  public void setE03TARTYPA(String newvalue)
  {
    fieldE03TARTYPA.setString(newvalue);
  }

  /**
  * Get value of field E03TARTYPA as a String.
  */
  public String getE03TARTYPA()
  {
    return fieldE03TARTYPA.getString();
  }

  /**
  * Set field E03CCRNUM using a String value.
  */
  public void setE03CCRNUM(String newvalue)
  {
    fieldE03CCRNUM.setString(newvalue);
  }

  /**
  * Get value of field E03CCRNUM as a String.
  */
  public String getE03CCRNUM()
  {
    return fieldE03CCRNUM.getString();
  }

  /**
  * Set field E03CCRNUMA using a String value.
  */
  public void setE03CCRNUMA(String newvalue)
  {
    fieldE03CCRNUMA.setString(newvalue);
  }

  /**
  * Get value of field E03CCRNUMA as a String.
  */
  public String getE03CCRNUMA()
  {
    return fieldE03CCRNUMA.getString();
  }

  /**
  * Set field E03CCRNEW using a String value.
  */
  public void setE03CCRNEW(String newvalue)
  {
    fieldE03CCRNEW.setString(newvalue);
  }

  /**
  * Get value of field E03CCRNEW as a String.
  */
  public String getE03CCRNEW()
  {
    return fieldE03CCRNEW.getString();
  }

  /**
  * Set field E03PRICUN using a String value.
  */
  public void setE03PRICUN(String newvalue)
  {
    fieldE03PRICUN.setString(newvalue);
  }

  /**
  * Get value of field E03PRICUN as a String.
  */
  public String getE03PRICUN()
  {
    return fieldE03PRICUN.getString();
  }

  /**
  * Set numeric field E03PRICUN using a BigDecimal value.
  */
  public void setE03PRICUN(BigDecimal newvalue)
  {
    fieldE03PRICUN.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E03PRICUN as a BigDecimal.
  */
  public BigDecimal getBigDecimalE03PRICUN()
  {
    return fieldE03PRICUN.getBigDecimal();
  }

  /**
  * Set field E03PRICUNA using a String value.
  */
  public void setE03PRICUNA(String newvalue)
  {
    fieldE03PRICUNA.setString(newvalue);
  }

  /**
  * Get value of field E03PRICUNA as a String.
  */
  public String getE03PRICUNA()
  {
    return fieldE03PRICUNA.getString();
  }

  /**
  * Set numeric field E03PRICUNA using a BigDecimal value.
  */
  public void setE03PRICUNA(BigDecimal newvalue)
  {
    fieldE03PRICUNA.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E03PRICUNA as a BigDecimal.
  */
  public BigDecimal getBigDecimalE03PRICUNA()
  {
    return fieldE03PRICUNA.getBigDecimal();
  }

  /**
  * Set field E03PRINA1 using a String value.
  */
  public void setE03PRINA1(String newvalue)
  {
    fieldE03PRINA1.setString(newvalue);
  }

  /**
  * Get value of field E03PRINA1 as a String.
  */
  public String getE03PRINA1()
  {
    return fieldE03PRINA1.getString();
  }

  /**
  * Set field E03PRINA1A using a String value.
  */
  public void setE03PRINA1A(String newvalue)
  {
    fieldE03PRINA1A.setString(newvalue);
  }

  /**
  * Get value of field E03PRINA1A as a String.
  */
  public String getE03PRINA1A()
  {
    return fieldE03PRINA1A.getString();
  }

  /**
  * Set field E03CCRCID using a String value.
  */
  public void setE03CCRCID(String newvalue)
  {
    fieldE03CCRCID.setString(newvalue);
  }

  /**
  * Get value of field E03CCRCID as a String.
  */
  public String getE03CCRCID()
  {
    return fieldE03CCRCID.getString();
  }

  /**
  * Set field E03CCRCIDA using a String value.
  */
  public void setE03CCRCIDA(String newvalue)
  {
    fieldE03CCRCIDA.setString(newvalue);
  }

  /**
  * Get value of field E03CCRCIDA as a String.
  */
  public String getE03CCRCIDA()
  {
    return fieldE03CCRCIDA.getString();
  }

  /**
  * Set field E03CCRTYP using a String value.
  */
  public void setE03CCRTYP(String newvalue)
  {
    fieldE03CCRTYP.setString(newvalue);
  }

  /**
  * Get value of field E03CCRTYP as a String.
  */
  public String getE03CCRTYP()
  {
    return fieldE03CCRTYP.getString();
  }

  /**
  * Set field E03CCRISM using a String value.
  */
  public void setE03CCRISM(String newvalue)
  {
    fieldE03CCRISM.setString(newvalue);
  }

  /**
  * Get value of field E03CCRISM as a String.
  */
  public String getE03CCRISM()
  {
    return fieldE03CCRISM.getString();
  }

  /**
  * Set numeric field E03CCRISM using a BigDecimal value.
  */
  public void setE03CCRISM(BigDecimal newvalue)
  {
    fieldE03CCRISM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E03CCRISM as a BigDecimal.
  */
  public BigDecimal getBigDecimalE03CCRISM()
  {
    return fieldE03CCRISM.getBigDecimal();
  }

  /**
  * Set field E03CCRISD using a String value.
  */
  public void setE03CCRISD(String newvalue)
  {
    fieldE03CCRISD.setString(newvalue);
  }

  /**
  * Get value of field E03CCRISD as a String.
  */
  public String getE03CCRISD()
  {
    return fieldE03CCRISD.getString();
  }

  /**
  * Set numeric field E03CCRISD using a BigDecimal value.
  */
  public void setE03CCRISD(BigDecimal newvalue)
  {
    fieldE03CCRISD.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E03CCRISD as a BigDecimal.
  */
  public BigDecimal getBigDecimalE03CCRISD()
  {
    return fieldE03CCRISD.getBigDecimal();
  }

  /**
  * Set field E03CCRISY using a String value.
  */
  public void setE03CCRISY(String newvalue)
  {
    fieldE03CCRISY.setString(newvalue);
  }

  /**
  * Get value of field E03CCRISY as a String.
  */
  public String getE03CCRISY()
  {
    return fieldE03CCRISY.getString();
  }

  /**
  * Set numeric field E03CCRISY using a BigDecimal value.
  */
  public void setE03CCRISY(BigDecimal newvalue)
  {
    fieldE03CCRISY.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E03CCRISY as a BigDecimal.
  */
  public BigDecimal getBigDecimalE03CCRISY()
  {
    return fieldE03CCRISY.getBigDecimal();
  }

  /**
  * Set field E03CCRDLM using a String value.
  */
  public void setE03CCRDLM(String newvalue)
  {
    fieldE03CCRDLM.setString(newvalue);
  }

  /**
  * Get value of field E03CCRDLM as a String.
  */
  public String getE03CCRDLM()
  {
    return fieldE03CCRDLM.getString();
  }

  /**
  * Set numeric field E03CCRDLM using a BigDecimal value.
  */
  public void setE03CCRDLM(BigDecimal newvalue)
  {
    fieldE03CCRDLM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E03CCRDLM as a BigDecimal.
  */
  public BigDecimal getBigDecimalE03CCRDLM()
  {
    return fieldE03CCRDLM.getBigDecimal();
  }

  /**
  * Set field E03CCRDLD using a String value.
  */
  public void setE03CCRDLD(String newvalue)
  {
    fieldE03CCRDLD.setString(newvalue);
  }

  /**
  * Get value of field E03CCRDLD as a String.
  */
  public String getE03CCRDLD()
  {
    return fieldE03CCRDLD.getString();
  }

  /**
  * Set numeric field E03CCRDLD using a BigDecimal value.
  */
  public void setE03CCRDLD(BigDecimal newvalue)
  {
    fieldE03CCRDLD.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E03CCRDLD as a BigDecimal.
  */
  public BigDecimal getBigDecimalE03CCRDLD()
  {
    return fieldE03CCRDLD.getBigDecimal();
  }

  /**
  * Set field E03CCRDLY using a String value.
  */
  public void setE03CCRDLY(String newvalue)
  {
    fieldE03CCRDLY.setString(newvalue);
  }

  /**
  * Get value of field E03CCRDLY as a String.
  */
  public String getE03CCRDLY()
  {
    return fieldE03CCRDLY.getString();
  }

  /**
  * Set numeric field E03CCRDLY using a BigDecimal value.
  */
  public void setE03CCRDLY(BigDecimal newvalue)
  {
    fieldE03CCRDLY.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E03CCRDLY as a BigDecimal.
  */
  public BigDecimal getBigDecimalE03CCRDLY()
  {
    return fieldE03CCRDLY.getBigDecimal();
  }

  /**
  * Set field E03CCREXM using a String value.
  */
  public void setE03CCREXM(String newvalue)
  {
    fieldE03CCREXM.setString(newvalue);
  }

  /**
  * Get value of field E03CCREXM as a String.
  */
  public String getE03CCREXM()
  {
    return fieldE03CCREXM.getString();
  }

  /**
  * Set numeric field E03CCREXM using a BigDecimal value.
  */
  public void setE03CCREXM(BigDecimal newvalue)
  {
    fieldE03CCREXM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E03CCREXM as a BigDecimal.
  */
  public BigDecimal getBigDecimalE03CCREXM()
  {
    return fieldE03CCREXM.getBigDecimal();
  }

  /**
  * Set field E03CCREXD using a String value.
  */
  public void setE03CCREXD(String newvalue)
  {
    fieldE03CCREXD.setString(newvalue);
  }

  /**
  * Get value of field E03CCREXD as a String.
  */
  public String getE03CCREXD()
  {
    return fieldE03CCREXD.getString();
  }

  /**
  * Set numeric field E03CCREXD using a BigDecimal value.
  */
  public void setE03CCREXD(BigDecimal newvalue)
  {
    fieldE03CCREXD.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E03CCREXD as a BigDecimal.
  */
  public BigDecimal getBigDecimalE03CCREXD()
  {
    return fieldE03CCREXD.getBigDecimal();
  }

  /**
  * Set field E03CCREXY using a String value.
  */
  public void setE03CCREXY(String newvalue)
  {
    fieldE03CCREXY.setString(newvalue);
  }

  /**
  * Get value of field E03CCREXY as a String.
  */
  public String getE03CCREXY()
  {
    return fieldE03CCREXY.getString();
  }

  /**
  * Set numeric field E03CCREXY using a BigDecimal value.
  */
  public void setE03CCREXY(BigDecimal newvalue)
  {
    fieldE03CCREXY.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E03CCREXY as a BigDecimal.
  */
  public BigDecimal getBigDecimalE03CCREXY()
  {
    return fieldE03CCREXY.getBigDecimal();
  }

  /**
  * Set field E03CCRISMA using a String value.
  */
  public void setE03CCRISMA(String newvalue)
  {
    fieldE03CCRISMA.setString(newvalue);
  }

  /**
  * Get value of field E03CCRISMA as a String.
  */
  public String getE03CCRISMA()
  {
    return fieldE03CCRISMA.getString();
  }

  /**
  * Set numeric field E03CCRISMA using a BigDecimal value.
  */
  public void setE03CCRISMA(BigDecimal newvalue)
  {
    fieldE03CCRISMA.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E03CCRISMA as a BigDecimal.
  */
  public BigDecimal getBigDecimalE03CCRISMA()
  {
    return fieldE03CCRISMA.getBigDecimal();
  }

  /**
  * Set field E03CCRISDA using a String value.
  */
  public void setE03CCRISDA(String newvalue)
  {
    fieldE03CCRISDA.setString(newvalue);
  }

  /**
  * Get value of field E03CCRISDA as a String.
  */
  public String getE03CCRISDA()
  {
    return fieldE03CCRISDA.getString();
  }

  /**
  * Set numeric field E03CCRISDA using a BigDecimal value.
  */
  public void setE03CCRISDA(BigDecimal newvalue)
  {
    fieldE03CCRISDA.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E03CCRISDA as a BigDecimal.
  */
  public BigDecimal getBigDecimalE03CCRISDA()
  {
    return fieldE03CCRISDA.getBigDecimal();
  }

  /**
  * Set field E03CCRISYA using a String value.
  */
  public void setE03CCRISYA(String newvalue)
  {
    fieldE03CCRISYA.setString(newvalue);
  }

  /**
  * Get value of field E03CCRISYA as a String.
  */
  public String getE03CCRISYA()
  {
    return fieldE03CCRISYA.getString();
  }

  /**
  * Set numeric field E03CCRISYA using a BigDecimal value.
  */
  public void setE03CCRISYA(BigDecimal newvalue)
  {
    fieldE03CCRISYA.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E03CCRISYA as a BigDecimal.
  */
  public BigDecimal getBigDecimalE03CCRISYA()
  {
    return fieldE03CCRISYA.getBigDecimal();
  }

  /**
  * Set field E03CCRDLMA using a String value.
  */
  public void setE03CCRDLMA(String newvalue)
  {
    fieldE03CCRDLMA.setString(newvalue);
  }

  /**
  * Get value of field E03CCRDLMA as a String.
  */
  public String getE03CCRDLMA()
  {
    return fieldE03CCRDLMA.getString();
  }

  /**
  * Set numeric field E03CCRDLMA using a BigDecimal value.
  */
  public void setE03CCRDLMA(BigDecimal newvalue)
  {
    fieldE03CCRDLMA.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E03CCRDLMA as a BigDecimal.
  */
  public BigDecimal getBigDecimalE03CCRDLMA()
  {
    return fieldE03CCRDLMA.getBigDecimal();
  }

  /**
  * Set field E03CCRDLDA using a String value.
  */
  public void setE03CCRDLDA(String newvalue)
  {
    fieldE03CCRDLDA.setString(newvalue);
  }

  /**
  * Get value of field E03CCRDLDA as a String.
  */
  public String getE03CCRDLDA()
  {
    return fieldE03CCRDLDA.getString();
  }

  /**
  * Set numeric field E03CCRDLDA using a BigDecimal value.
  */
  public void setE03CCRDLDA(BigDecimal newvalue)
  {
    fieldE03CCRDLDA.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E03CCRDLDA as a BigDecimal.
  */
  public BigDecimal getBigDecimalE03CCRDLDA()
  {
    return fieldE03CCRDLDA.getBigDecimal();
  }

  /**
  * Set field E03CCRDLYA using a String value.
  */
  public void setE03CCRDLYA(String newvalue)
  {
    fieldE03CCRDLYA.setString(newvalue);
  }

  /**
  * Get value of field E03CCRDLYA as a String.
  */
  public String getE03CCRDLYA()
  {
    return fieldE03CCRDLYA.getString();
  }

  /**
  * Set numeric field E03CCRDLYA using a BigDecimal value.
  */
  public void setE03CCRDLYA(BigDecimal newvalue)
  {
    fieldE03CCRDLYA.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E03CCRDLYA as a BigDecimal.
  */
  public BigDecimal getBigDecimalE03CCRDLYA()
  {
    return fieldE03CCRDLYA.getBigDecimal();
  }

  /**
  * Set field E03CCREXMA using a String value.
  */
  public void setE03CCREXMA(String newvalue)
  {
    fieldE03CCREXMA.setString(newvalue);
  }

  /**
  * Get value of field E03CCREXMA as a String.
  */
  public String getE03CCREXMA()
  {
    return fieldE03CCREXMA.getString();
  }

  /**
  * Set numeric field E03CCREXMA using a BigDecimal value.
  */
  public void setE03CCREXMA(BigDecimal newvalue)
  {
    fieldE03CCREXMA.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E03CCREXMA as a BigDecimal.
  */
  public BigDecimal getBigDecimalE03CCREXMA()
  {
    return fieldE03CCREXMA.getBigDecimal();
  }

  /**
  * Set field E03CCREXDA using a String value.
  */
  public void setE03CCREXDA(String newvalue)
  {
    fieldE03CCREXDA.setString(newvalue);
  }

  /**
  * Get value of field E03CCREXDA as a String.
  */
  public String getE03CCREXDA()
  {
    return fieldE03CCREXDA.getString();
  }

  /**
  * Set numeric field E03CCREXDA using a BigDecimal value.
  */
  public void setE03CCREXDA(BigDecimal newvalue)
  {
    fieldE03CCREXDA.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E03CCREXDA as a BigDecimal.
  */
  public BigDecimal getBigDecimalE03CCREXDA()
  {
    return fieldE03CCREXDA.getBigDecimal();
  }

  /**
  * Set field E03CCREXYA using a String value.
  */
  public void setE03CCREXYA(String newvalue)
  {
    fieldE03CCREXYA.setString(newvalue);
  }

  /**
  * Get value of field E03CCREXYA as a String.
  */
  public String getE03CCREXYA()
  {
    return fieldE03CCREXYA.getString();
  }

  /**
  * Set numeric field E03CCREXYA using a BigDecimal value.
  */
  public void setE03CCREXYA(BigDecimal newvalue)
  {
    fieldE03CCREXYA.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E03CCREXYA as a BigDecimal.
  */
  public BigDecimal getBigDecimalE03CCREXYA()
  {
    return fieldE03CCREXYA.getBigDecimal();
  }

  /**
  * Set field E03CCRATG using a String value.
  */
  public void setE03CCRATG(String newvalue)
  {
    fieldE03CCRATG.setString(newvalue);
  }

  /**
  * Get value of field E03CCRATG as a String.
  */
  public String getE03CCRATG()
  {
    return fieldE03CCRATG.getString();
  }

  /**
  * Set field E03CCRSTS using a String value.
  */
  public void setE03CCRSTS(String newvalue)
  {
    fieldE03CCRSTS.setString(newvalue);
  }

  /**
  * Get value of field E03CCRSTS as a String.
  */
  public String getE03CCRSTS()
  {
    return fieldE03CCRSTS.getString();
  }

  /**
  * Set field E03CCRDSC using a String value.
  */
  public void setE03CCRDSC(String newvalue)
  {
    fieldE03CCRDSC.setString(newvalue);
  }

  /**
  * Get value of field E03CCRDSC as a String.
  */
  public String getE03CCRDSC()
  {
    return fieldE03CCRDSC.getString();
  }

  /**
  * Set field E03CCRSTSA using a String value.
  */
  public void setE03CCRSTSA(String newvalue)
  {
    fieldE03CCRSTSA.setString(newvalue);
  }

  /**
  * Get value of field E03CCRSTSA as a String.
  */
  public String getE03CCRSTSA()
  {
    return fieldE03CCRSTSA.getString();
  }

  /**
  * Set field E03CCRDSCA using a String value.
  */
  public void setE03CCRDSCA(String newvalue)
  {
    fieldE03CCRDSCA.setString(newvalue);
  }

  /**
  * Get value of field E03CCRDSCA as a String.
  */
  public String getE03CCRDSCA()
  {
    return fieldE03CCRDSCA.getString();
  }

  /**
  * Set field E03CCRUSR using a String value.
  */
  public void setE03CCRUSR(String newvalue)
  {
    fieldE03CCRUSR.setString(newvalue);
  }

  /**
  * Get value of field E03CCRUSR as a String.
  */
  public String getE03CCRUSR()
  {
    return fieldE03CCRUSR.getString();
  }

  /**
  * Set field E03CCRUSRA using a String value.
  */
  public void setE03CCRUSRA(String newvalue)
  {
    fieldE03CCRUSRA.setString(newvalue);
  }

  /**
  * Get value of field E03CCRUSRA as a String.
  */
  public String getE03CCRUSRA()
  {
    return fieldE03CCRUSRA.getString();
  }

  /**
  * Set field E03CCRBRN using a String value.
  */
  public void setE03CCRBRN(String newvalue)
  {
    fieldE03CCRBRN.setString(newvalue);
  }

  /**
  * Get value of field E03CCRBRN as a String.
  */
  public String getE03CCRBRN()
  {
    return fieldE03CCRBRN.getString();
  }

  /**
  * Set numeric field E03CCRBRN using a BigDecimal value.
  */
  public void setE03CCRBRN(BigDecimal newvalue)
  {
    fieldE03CCRBRN.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E03CCRBRN as a BigDecimal.
  */
  public BigDecimal getBigDecimalE03CCRBRN()
  {
    return fieldE03CCRBRN.getBigDecimal();
  }

  /**
  * Set field E03CCRBRNA using a String value.
  */
  public void setE03CCRBRNA(String newvalue)
  {
    fieldE03CCRBRNA.setString(newvalue);
  }

  /**
  * Get value of field E03CCRBRNA as a String.
  */
  public String getE03CCRBRNA()
  {
    return fieldE03CCRBRNA.getString();
  }

  /**
  * Set numeric field E03CCRBRNA using a BigDecimal value.
  */
  public void setE03CCRBRNA(BigDecimal newvalue)
  {
    fieldE03CCRBRNA.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E03CCRBRNA as a BigDecimal.
  */
  public BigDecimal getBigDecimalE03CCRBRNA()
  {
    return fieldE03CCRBRNA.getBigDecimal();
  }

}
