package datapro.eibs.beans;
 
import datapro.eibs.sockets.*;
import java.io.*;
import java.math.*;

import java.util.*;

/**
* Class generated by AS/400 CRTCLASS command from ECH531001 physical file definition.
* 
* File level identifier is 1050902164708.
* Record format level identifier is 482613EC2D465.
*/

public class ECH531001Message extends MessageRecord
{
  final static String fldnames[] = {
                                     "H01USERID",
                                     "H01PROGRM",
                                     "H01TIMSYS",
                                     "H01SCRCOD",
                                     "H01OPECOD",
                                     "H01FLGMAS",
                                     "H01FLGWK1",
                                     "H01FLGWK2",
                                     "H01FLGWK3",
                                     "E01SELBNK",
                                     "E01SELBRN",
                                     "E01SELOSTA",
                                     "E01SELFSTA",
                                     "E01SELID1",
                                     "E01SELID2",
                                     "E01SELID3",
                                     "E01SELFD1",
                                     "E01SELFD2",
                                     "E01SELFD3",
                                     "E01CHDBNK",
                                     "E01CHDBRN",
                                     "E01CHDCCY",
                                     "E01CHDACC",
                                     "E01CHDACD",
                                     "E01CHDPRO",
                                     "E01CHDCUN",
                                     "E01CHDNA1",
                                     "E01CHDOFC",
                                     "E01DSCOFC",
                                     "E01CHDRQ1",
                                     "E01CHDRQ2",
                                     "E01CHDRQ3",
                                     "E01CHDNCB",
                                     "E01CHDTCB",
                                     "E01CHDICK",
                                     "E01CHDFCK",
                                     "E01CHDNTC",
                                     "E01CHDDBR",
                                     "E01CHDDES",
                                     "E01CHDACT",
                                     "E01CHDSTS",
                                     "E01CHDSDS",
                                     "E01OPECDE"
                                   };
  final static String tnames[] = {
                                   "H01USERID",
                                   "H01PROGRM",
                                   "H01TIMSYS",
                                   "H01SCRCOD",
                                   "H01OPECOD",
                                   "H01FLGMAS",
                                   "H01FLGWK1",
                                   "H01FLGWK2",
                                   "H01FLGWK3",
                                   "E01SELBNK",
                                   "E01SELBRN",
                                   "E01SELOSTA",
                                   "E01SELFSTA",
                                   "E01SELID1",
                                   "E01SELID2",
                                   "E01SELID3",
                                   "E01SELFD1",
                                   "E01SELFD2",
                                   "E01SELFD3",
                                   "E01CHDBNK",
                                   "E01CHDBRN",
                                   "E01CHDCCY",
                                   "E01CHDACC",
                                   "E01CHDACD",
                                   "E01CHDPRO",
                                   "E01CHDCUN",
                                   "E01CHDNA1",
                                   "E01CHDOFC",
                                   "E01DSCOFC",
                                   "E01CHDRQ1",
                                   "E01CHDRQ2",
                                   "E01CHDRQ3",
                                   "E01CHDNCB",
                                   "E01CHDTCB",
                                   "E01CHDICK",
                                   "E01CHDFCK",
                                   "E01CHDNTC",
                                   "E01CHDDBR",
                                   "E01CHDDES",
                                   "E01CHDACT",
                                   "E01CHDSTS",
                                   "E01CHDSDS",
                                   "E01OPECDE"
                                 };
  final static String fid = "1050902164708";
  final static String rid = "482613EC2D465";
  final static String fmtname = "ECH531001";
  final int FIELDCOUNT = 43;
  private static Hashtable tlookup = new Hashtable();
  private CharacterField fieldH01USERID = null;
  private CharacterField fieldH01PROGRM = null;
  private CharacterField fieldH01TIMSYS = null;
  private CharacterField fieldH01SCRCOD = null;
  private CharacterField fieldH01OPECOD = null;
  private CharacterField fieldH01FLGMAS = null;
  private CharacterField fieldH01FLGWK1 = null;
  private CharacterField fieldH01FLGWK2 = null;
  private CharacterField fieldH01FLGWK3 = null;
  private CharacterField fieldE01SELBNK = null;
  private DecimalField fieldE01SELBRN = null;
  private CharacterField fieldE01SELOSTA = null;
  private CharacterField fieldE01SELFSTA = null;
  private DecimalField fieldE01SELID1 = null;
  private DecimalField fieldE01SELID2 = null;
  private DecimalField fieldE01SELID3 = null;
  private DecimalField fieldE01SELFD1 = null;
  private DecimalField fieldE01SELFD2 = null;
  private DecimalField fieldE01SELFD3 = null;
  private CharacterField fieldE01CHDBNK = null;
  private DecimalField fieldE01CHDBRN = null;
  private CharacterField fieldE01CHDCCY = null;
  private DecimalField fieldE01CHDACC = null;
  private CharacterField fieldE01CHDACD = null;
  private CharacterField fieldE01CHDPRO = null;
  private DecimalField fieldE01CHDCUN = null;
  private CharacterField fieldE01CHDNA1 = null;
  private CharacterField fieldE01CHDOFC = null;
  private CharacterField fieldE01DSCOFC = null;
  private DecimalField fieldE01CHDRQ1 = null;
  private DecimalField fieldE01CHDRQ2 = null;
  private DecimalField fieldE01CHDRQ3 = null;
  private DecimalField fieldE01CHDNCB = null;
  private DecimalField fieldE01CHDTCB = null;
  private DecimalField fieldE01CHDICK = null;
  private DecimalField fieldE01CHDFCK = null;
  private DecimalField fieldE01CHDNTC = null;
  private DecimalField fieldE01CHDDBR = null;
  private DecimalField fieldE01CHDDES = null;
  private CharacterField fieldE01CHDACT = null;
  private CharacterField fieldE01CHDSTS = null;
  private CharacterField fieldE01CHDSDS = null;
  private CharacterField fieldE01OPECDE = null;

  /**
  * Constructor for ECH531001Message.
  */
  public ECH531001Message()
  {
    createFields();
    initialize();
  }

  /**
  * Create fields for this message.
  * This method implements the abstract method in the MessageRecord superclass.
  */
  protected void createFields()
  {
    recordsize = 287;
    fileid = fid;
    recordid = rid;
    message = new byte[getByteLength()];
    formatname = fmtname;
    fieldnames = fldnames;
    tagnames = tnames;
    fields = new MessageField[FIELDCOUNT];

    fields[0] = fieldH01USERID =
    new CharacterField(message, HEADERSIZE + 0, 10, "H01USERID");
    fields[1] = fieldH01PROGRM =
    new CharacterField(message, HEADERSIZE + 10, 10, "H01PROGRM");
    fields[2] = fieldH01TIMSYS =
    new CharacterField(message, HEADERSIZE + 20, 12, "H01TIMSYS");
    fields[3] = fieldH01SCRCOD =
    new CharacterField(message, HEADERSIZE + 32, 2, "H01SCRCOD");
    fields[4] = fieldH01OPECOD =
    new CharacterField(message, HEADERSIZE + 34, 4, "H01OPECOD");
    fields[5] = fieldH01FLGMAS =
    new CharacterField(message, HEADERSIZE + 38, 1, "H01FLGMAS");
    fields[6] = fieldH01FLGWK1 =
    new CharacterField(message, HEADERSIZE + 39, 1, "H01FLGWK1");
    fields[7] = fieldH01FLGWK2 =
    new CharacterField(message, HEADERSIZE + 40, 1, "H01FLGWK2");
    fields[8] = fieldH01FLGWK3 =
    new CharacterField(message, HEADERSIZE + 41, 1, "H01FLGWK3");
    fields[9] = fieldE01SELBNK =
    new CharacterField(message, HEADERSIZE + 42, 2, "E01SELBNK");
    fields[10] = fieldE01SELBRN =
    new DecimalField(message, HEADERSIZE + 44, 4, 0, "E01SELBRN");
    fields[11] = fieldE01SELOSTA =
    new CharacterField(message, HEADERSIZE + 48, 4, "E01SELOSTA");
    fields[12] = fieldE01SELFSTA =
    new CharacterField(message, HEADERSIZE + 52, 4, "E01SELFSTA");
    fields[13] = fieldE01SELID1 =
    new DecimalField(message, HEADERSIZE + 56, 3, 0, "E01SELID1");
    fields[14] = fieldE01SELID2 =
    new DecimalField(message, HEADERSIZE + 59, 3, 0, "E01SELID2");
    fields[15] = fieldE01SELID3 =
    new DecimalField(message, HEADERSIZE + 62, 3, 0, "E01SELID3");
    fields[16] = fieldE01SELFD1 =
    new DecimalField(message, HEADERSIZE + 65, 3, 0, "E01SELFD1");
    fields[17] = fieldE01SELFD2 =
    new DecimalField(message, HEADERSIZE + 68, 3, 0, "E01SELFD2");
    fields[18] = fieldE01SELFD3 =
    new DecimalField(message, HEADERSIZE + 71, 3, 0, "E01SELFD3");
    fields[19] = fieldE01CHDBNK =
    new CharacterField(message, HEADERSIZE + 74, 2, "E01CHDBNK");
    fields[20] = fieldE01CHDBRN =
    new DecimalField(message, HEADERSIZE + 76, 4, 0, "E01CHDBRN");
    fields[21] = fieldE01CHDCCY =
    new CharacterField(message, HEADERSIZE + 80, 3, "E01CHDCCY");
    fields[22] = fieldE01CHDACC =
    new DecimalField(message, HEADERSIZE + 83, 13, 0, "E01CHDACC");
    fields[23] = fieldE01CHDACD =
    new CharacterField(message, HEADERSIZE + 96, 2, "E01CHDACD");
    fields[24] = fieldE01CHDPRO =
    new CharacterField(message, HEADERSIZE + 98, 4, "E01CHDPRO");
    fields[25] = fieldE01CHDCUN =
    new DecimalField(message, HEADERSIZE + 102, 10, 0, "E01CHDCUN");
    fields[26] = fieldE01CHDNA1 =
    new CharacterField(message, HEADERSIZE + 112, 45, "E01CHDNA1");
    fields[27] = fieldE01CHDOFC =
    new CharacterField(message, HEADERSIZE + 157, 4, "E01CHDOFC");
    fields[28] = fieldE01DSCOFC =
    new CharacterField(message, HEADERSIZE + 161, 35, "E01DSCOFC");
    fields[29] = fieldE01CHDRQ1 =
    new DecimalField(message, HEADERSIZE + 196, 3, 0, "E01CHDRQ1");
    fields[30] = fieldE01CHDRQ2 =
    new DecimalField(message, HEADERSIZE + 199, 3, 0, "E01CHDRQ2");
    fields[31] = fieldE01CHDRQ3 =
    new DecimalField(message, HEADERSIZE + 202, 3, 0, "E01CHDRQ3");
    fields[32] = fieldE01CHDNCB =
    new DecimalField(message, HEADERSIZE + 205, 5, 0, "E01CHDNCB");
    fields[33] = fieldE01CHDTCB =
    new DecimalField(message, HEADERSIZE + 210, 3, 0, "E01CHDTCB");
    fields[34] = fieldE01CHDICK =
    new DecimalField(message, HEADERSIZE + 213, 10, 0, "E01CHDICK");
    fields[35] = fieldE01CHDFCK =
    new DecimalField(message, HEADERSIZE + 223, 10, 0, "E01CHDFCK");
    fields[36] = fieldE01CHDNTC =
    new DecimalField(message, HEADERSIZE + 233, 5, 0, "E01CHDNTC");
    fields[37] = fieldE01CHDDBR =
    new DecimalField(message, HEADERSIZE + 238, 4, 0, "E01CHDDBR");
    fields[38] = fieldE01CHDDES =
    new DecimalField(message, HEADERSIZE + 242, 4, 0, "E01CHDDES");
    fields[39] = fieldE01CHDACT =
    new CharacterField(message, HEADERSIZE + 246, 1, "E01CHDACT");
    fields[40] = fieldE01CHDSTS =
    new CharacterField(message, HEADERSIZE + 247, 4, "E01CHDSTS");
    fields[41] = fieldE01CHDSDS =
    new CharacterField(message, HEADERSIZE + 251, 35, "E01CHDSDS");
    fields[42] = fieldE01OPECDE =
    new CharacterField(message, HEADERSIZE + 286, 1, "E01OPECDE");

    synchronized (tlookup)
    {
      if (tlookup.isEmpty())
      {
        for (int i = 0; i < tnames.length; i++)
          tlookup.put(tnames[i], new Integer(i));
      }
    }

    taglookup = tlookup;
  }

  /**
  * Set field H01USERID using a String value.
  */
  public void setH01USERID(String newvalue)
  {
    fieldH01USERID.setString(newvalue);
  }

  /**
  * Get value of field H01USERID as a String.
  */
  public String getH01USERID()
  {
    return fieldH01USERID.getString();
  }

  /**
  * Set field H01PROGRM using a String value.
  */
  public void setH01PROGRM(String newvalue)
  {
    fieldH01PROGRM.setString(newvalue);
  }

  /**
  * Get value of field H01PROGRM as a String.
  */
  public String getH01PROGRM()
  {
    return fieldH01PROGRM.getString();
  }

  /**
  * Set field H01TIMSYS using a String value.
  */
  public void setH01TIMSYS(String newvalue)
  {
    fieldH01TIMSYS.setString(newvalue);
  }

  /**
  * Get value of field H01TIMSYS as a String.
  */
  public String getH01TIMSYS()
  {
    return fieldH01TIMSYS.getString();
  }

  /**
  * Set field H01SCRCOD using a String value.
  */
  public void setH01SCRCOD(String newvalue)
  {
    fieldH01SCRCOD.setString(newvalue);
  }

  /**
  * Get value of field H01SCRCOD as a String.
  */
  public String getH01SCRCOD()
  {
    return fieldH01SCRCOD.getString();
  }

  /**
  * Set field H01OPECOD using a String value.
  */
  public void setH01OPECOD(String newvalue)
  {
    fieldH01OPECOD.setString(newvalue);
  }

  /**
  * Get value of field H01OPECOD as a String.
  */
  public String getH01OPECOD()
  {
    return fieldH01OPECOD.getString();
  }

  /**
  * Set field H01FLGMAS using a String value.
  */
  public void setH01FLGMAS(String newvalue)
  {
    fieldH01FLGMAS.setString(newvalue);
  }

  /**
  * Get value of field H01FLGMAS as a String.
  */
  public String getH01FLGMAS()
  {
    return fieldH01FLGMAS.getString();
  }

  /**
  * Set field H01FLGWK1 using a String value.
  */
  public void setH01FLGWK1(String newvalue)
  {
    fieldH01FLGWK1.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK1 as a String.
  */
  public String getH01FLGWK1()
  {
    return fieldH01FLGWK1.getString();
  }

  /**
  * Set field H01FLGWK2 using a String value.
  */
  public void setH01FLGWK2(String newvalue)
  {
    fieldH01FLGWK2.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK2 as a String.
  */
  public String getH01FLGWK2()
  {
    return fieldH01FLGWK2.getString();
  }

  /**
  * Set field H01FLGWK3 using a String value.
  */
  public void setH01FLGWK3(String newvalue)
  {
    fieldH01FLGWK3.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK3 as a String.
  */
  public String getH01FLGWK3()
  {
    return fieldH01FLGWK3.getString();
  }

  /**
  * Set field E01SELBNK using a String value.
  */
  public void setE01SELBNK(String newvalue)
  {
    fieldE01SELBNK.setString(newvalue);
  }

  /**
  * Get value of field E01SELBNK as a String.
  */
  public String getE01SELBNK()
  {
    return fieldE01SELBNK.getString();
  }

  /**
  * Set field E01SELBRN using a String value.
  */
  public void setE01SELBRN(String newvalue)
  {
    fieldE01SELBRN.setString(newvalue);
  }

  /**
  * Get value of field E01SELBRN as a String.
  */
  public String getE01SELBRN()
  {
    return fieldE01SELBRN.getString();
  }

  /**
  * Set numeric field E01SELBRN using a BigDecimal value.
  */
  public void setE01SELBRN(BigDecimal newvalue)
  {
    fieldE01SELBRN.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01SELBRN as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01SELBRN()
  {
    return fieldE01SELBRN.getBigDecimal();
  }

  /**
  * Set field E01SELOSTA using a String value.
  */
  public void setE01SELOSTA(String newvalue)
  {
    fieldE01SELOSTA.setString(newvalue);
  }

  /**
  * Get value of field E01SELOSTA as a String.
  */
  public String getE01SELOSTA()
  {
    return fieldE01SELOSTA.getString();
  }

  /**
  * Set field E01SELFSTA using a String value.
  */
  public void setE01SELFSTA(String newvalue)
  {
    fieldE01SELFSTA.setString(newvalue);
  }

  /**
  * Get value of field E01SELFSTA as a String.
  */
  public String getE01SELFSTA()
  {
    return fieldE01SELFSTA.getString();
  }

  /**
  * Set field E01SELID1 using a String value.
  */
  public void setE01SELID1(String newvalue)
  {
    fieldE01SELID1.setString(newvalue);
  }

  /**
  * Get value of field E01SELID1 as a String.
  */
  public String getE01SELID1()
  {
    return fieldE01SELID1.getString();
  }

  /**
  * Set numeric field E01SELID1 using a BigDecimal value.
  */
  public void setE01SELID1(BigDecimal newvalue)
  {
    fieldE01SELID1.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01SELID1 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01SELID1()
  {
    return fieldE01SELID1.getBigDecimal();
  }

  /**
  * Set field E01SELID2 using a String value.
  */
  public void setE01SELID2(String newvalue)
  {
    fieldE01SELID2.setString(newvalue);
  }

  /**
  * Get value of field E01SELID2 as a String.
  */
  public String getE01SELID2()
  {
    return fieldE01SELID2.getString();
  }

  /**
  * Set numeric field E01SELID2 using a BigDecimal value.
  */
  public void setE01SELID2(BigDecimal newvalue)
  {
    fieldE01SELID2.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01SELID2 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01SELID2()
  {
    return fieldE01SELID2.getBigDecimal();
  }

  /**
  * Set field E01SELID3 using a String value.
  */
  public void setE01SELID3(String newvalue)
  {
    fieldE01SELID3.setString(newvalue);
  }

  /**
  * Get value of field E01SELID3 as a String.
  */
  public String getE01SELID3()
  {
    return fieldE01SELID3.getString();
  }

  /**
  * Set numeric field E01SELID3 using a BigDecimal value.
  */
  public void setE01SELID3(BigDecimal newvalue)
  {
    fieldE01SELID3.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01SELID3 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01SELID3()
  {
    return fieldE01SELID3.getBigDecimal();
  }

  /**
  * Set field E01SELFD1 using a String value.
  */
  public void setE01SELFD1(String newvalue)
  {
    fieldE01SELFD1.setString(newvalue);
  }

  /**
  * Get value of field E01SELFD1 as a String.
  */
  public String getE01SELFD1()
  {
    return fieldE01SELFD1.getString();
  }

  /**
  * Set numeric field E01SELFD1 using a BigDecimal value.
  */
  public void setE01SELFD1(BigDecimal newvalue)
  {
    fieldE01SELFD1.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01SELFD1 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01SELFD1()
  {
    return fieldE01SELFD1.getBigDecimal();
  }

  /**
  * Set field E01SELFD2 using a String value.
  */
  public void setE01SELFD2(String newvalue)
  {
    fieldE01SELFD2.setString(newvalue);
  }

  /**
  * Get value of field E01SELFD2 as a String.
  */
  public String getE01SELFD2()
  {
    return fieldE01SELFD2.getString();
  }

  /**
  * Set numeric field E01SELFD2 using a BigDecimal value.
  */
  public void setE01SELFD2(BigDecimal newvalue)
  {
    fieldE01SELFD2.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01SELFD2 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01SELFD2()
  {
    return fieldE01SELFD2.getBigDecimal();
  }

  /**
  * Set field E01SELFD3 using a String value.
  */
  public void setE01SELFD3(String newvalue)
  {
    fieldE01SELFD3.setString(newvalue);
  }

  /**
  * Get value of field E01SELFD3 as a String.
  */
  public String getE01SELFD3()
  {
    return fieldE01SELFD3.getString();
  }

  /**
  * Set numeric field E01SELFD3 using a BigDecimal value.
  */
  public void setE01SELFD3(BigDecimal newvalue)
  {
    fieldE01SELFD3.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01SELFD3 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01SELFD3()
  {
    return fieldE01SELFD3.getBigDecimal();
  }

  /**
  * Set field E01CHDBNK using a String value.
  */
  public void setE01CHDBNK(String newvalue)
  {
    fieldE01CHDBNK.setString(newvalue);
  }

  /**
  * Get value of field E01CHDBNK as a String.
  */
  public String getE01CHDBNK()
  {
    return fieldE01CHDBNK.getString();
  }

  /**
  * Set field E01CHDBRN using a String value.
  */
  public void setE01CHDBRN(String newvalue)
  {
    fieldE01CHDBRN.setString(newvalue);
  }

  /**
  * Get value of field E01CHDBRN as a String.
  */
  public String getE01CHDBRN()
  {
    return fieldE01CHDBRN.getString();
  }

  /**
  * Set numeric field E01CHDBRN using a BigDecimal value.
  */
  public void setE01CHDBRN(BigDecimal newvalue)
  {
    fieldE01CHDBRN.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CHDBRN as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CHDBRN()
  {
    return fieldE01CHDBRN.getBigDecimal();
  }

  /**
  * Set field E01CHDCCY using a String value.
  */
  public void setE01CHDCCY(String newvalue)
  {
    fieldE01CHDCCY.setString(newvalue);
  }

  /**
  * Get value of field E01CHDCCY as a String.
  */
  public String getE01CHDCCY()
  {
    return fieldE01CHDCCY.getString();
  }

  /**
  * Set field E01CHDACC using a String value.
  */
  public void setE01CHDACC(String newvalue)
  {
    fieldE01CHDACC.setString(newvalue);
  }

  /**
  * Get value of field E01CHDACC as a String.
  */
  public String getE01CHDACC()
  {
    return fieldE01CHDACC.getString();
  }

  /**
  * Set numeric field E01CHDACC using a BigDecimal value.
  */
  public void setE01CHDACC(BigDecimal newvalue)
  {
    fieldE01CHDACC.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CHDACC as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CHDACC()
  {
    return fieldE01CHDACC.getBigDecimal();
  }

  /**
  * Set field E01CHDACD using a String value.
  */
  public void setE01CHDACD(String newvalue)
  {
    fieldE01CHDACD.setString(newvalue);
  }

  /**
  * Get value of field E01CHDACD as a String.
  */
  public String getE01CHDACD()
  {
    return fieldE01CHDACD.getString();
  }

  /**
  * Set field E01CHDPRO using a String value.
  */
  public void setE01CHDPRO(String newvalue)
  {
    fieldE01CHDPRO.setString(newvalue);
  }

  /**
  * Get value of field E01CHDPRO as a String.
  */
  public String getE01CHDPRO()
  {
    return fieldE01CHDPRO.getString();
  }

  /**
  * Set field E01CHDCUN using a String value.
  */
  public void setE01CHDCUN(String newvalue)
  {
    fieldE01CHDCUN.setString(newvalue);
  }

  /**
  * Get value of field E01CHDCUN as a String.
  */
  public String getE01CHDCUN()
  {
    return fieldE01CHDCUN.getString();
  }

  /**
  * Set numeric field E01CHDCUN using a BigDecimal value.
  */
  public void setE01CHDCUN(BigDecimal newvalue)
  {
    fieldE01CHDCUN.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CHDCUN as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CHDCUN()
  {
    return fieldE01CHDCUN.getBigDecimal();
  }

  /**
  * Set field E01CHDNA1 using a String value.
  */
  public void setE01CHDNA1(String newvalue)
  {
    fieldE01CHDNA1.setString(newvalue);
  }

  /**
  * Get value of field E01CHDNA1 as a String.
  */
  public String getE01CHDNA1()
  {
    return fieldE01CHDNA1.getString();
  }

  /**
  * Set field E01CHDOFC using a String value.
  */
  public void setE01CHDOFC(String newvalue)
  {
    fieldE01CHDOFC.setString(newvalue);
  }

  /**
  * Get value of field E01CHDOFC as a String.
  */
  public String getE01CHDOFC()
  {
    return fieldE01CHDOFC.getString();
  }

  /**
  * Set field E01DSCOFC using a String value.
  */
  public void setE01DSCOFC(String newvalue)
  {
    fieldE01DSCOFC.setString(newvalue);
  }

  /**
  * Get value of field E01DSCOFC as a String.
  */
  public String getE01DSCOFC()
  {
    return fieldE01DSCOFC.getString();
  }

  /**
  * Set field E01CHDRQ1 using a String value.
  */
  public void setE01CHDRQ1(String newvalue)
  {
    fieldE01CHDRQ1.setString(newvalue);
  }

  /**
  * Get value of field E01CHDRQ1 as a String.
  */
  public String getE01CHDRQ1()
  {
    return fieldE01CHDRQ1.getString();
  }

  /**
  * Set numeric field E01CHDRQ1 using a BigDecimal value.
  */
  public void setE01CHDRQ1(BigDecimal newvalue)
  {
    fieldE01CHDRQ1.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CHDRQ1 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CHDRQ1()
  {
    return fieldE01CHDRQ1.getBigDecimal();
  }

  /**
  * Set field E01CHDRQ2 using a String value.
  */
  public void setE01CHDRQ2(String newvalue)
  {
    fieldE01CHDRQ2.setString(newvalue);
  }

  /**
  * Get value of field E01CHDRQ2 as a String.
  */
  public String getE01CHDRQ2()
  {
    return fieldE01CHDRQ2.getString();
  }

  /**
  * Set numeric field E01CHDRQ2 using a BigDecimal value.
  */
  public void setE01CHDRQ2(BigDecimal newvalue)
  {
    fieldE01CHDRQ2.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CHDRQ2 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CHDRQ2()
  {
    return fieldE01CHDRQ2.getBigDecimal();
  }

  /**
  * Set field E01CHDRQ3 using a String value.
  */
  public void setE01CHDRQ3(String newvalue)
  {
    fieldE01CHDRQ3.setString(newvalue);
  }

  /**
  * Get value of field E01CHDRQ3 as a String.
  */
  public String getE01CHDRQ3()
  {
    return fieldE01CHDRQ3.getString();
  }

  /**
  * Set numeric field E01CHDRQ3 using a BigDecimal value.
  */
  public void setE01CHDRQ3(BigDecimal newvalue)
  {
    fieldE01CHDRQ3.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CHDRQ3 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CHDRQ3()
  {
    return fieldE01CHDRQ3.getBigDecimal();
  }

  /**
  * Set field E01CHDNCB using a String value.
  */
  public void setE01CHDNCB(String newvalue)
  {
    fieldE01CHDNCB.setString(newvalue);
  }

  /**
  * Get value of field E01CHDNCB as a String.
  */
  public String getE01CHDNCB()
  {
    return fieldE01CHDNCB.getString();
  }

  /**
  * Set numeric field E01CHDNCB using a BigDecimal value.
  */
  public void setE01CHDNCB(BigDecimal newvalue)
  {
    fieldE01CHDNCB.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CHDNCB as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CHDNCB()
  {
    return fieldE01CHDNCB.getBigDecimal();
  }

  /**
  * Set field E01CHDTCB using a String value.
  */
  public void setE01CHDTCB(String newvalue)
  {
    fieldE01CHDTCB.setString(newvalue);
  }

  /**
  * Get value of field E01CHDTCB as a String.
  */
  public String getE01CHDTCB()
  {
    return fieldE01CHDTCB.getString();
  }

  /**
  * Set numeric field E01CHDTCB using a BigDecimal value.
  */
  public void setE01CHDTCB(BigDecimal newvalue)
  {
    fieldE01CHDTCB.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CHDTCB as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CHDTCB()
  {
    return fieldE01CHDTCB.getBigDecimal();
  }

  /**
  * Set field E01CHDICK using a String value.
  */
  public void setE01CHDICK(String newvalue)
  {
    fieldE01CHDICK.setString(newvalue);
  }

  /**
  * Get value of field E01CHDICK as a String.
  */
  public String getE01CHDICK()
  {
    return fieldE01CHDICK.getString();
  }

  /**
  * Set numeric field E01CHDICK using a BigDecimal value.
  */
  public void setE01CHDICK(BigDecimal newvalue)
  {
    fieldE01CHDICK.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CHDICK as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CHDICK()
  {
    return fieldE01CHDICK.getBigDecimal();
  }

  /**
  * Set field E01CHDFCK using a String value.
  */
  public void setE01CHDFCK(String newvalue)
  {
    fieldE01CHDFCK.setString(newvalue);
  }

  /**
  * Get value of field E01CHDFCK as a String.
  */
  public String getE01CHDFCK()
  {
    return fieldE01CHDFCK.getString();
  }

  /**
  * Set numeric field E01CHDFCK using a BigDecimal value.
  */
  public void setE01CHDFCK(BigDecimal newvalue)
  {
    fieldE01CHDFCK.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CHDFCK as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CHDFCK()
  {
    return fieldE01CHDFCK.getBigDecimal();
  }

  /**
  * Set field E01CHDNTC using a String value.
  */
  public void setE01CHDNTC(String newvalue)
  {
    fieldE01CHDNTC.setString(newvalue);
  }

  /**
  * Get value of field E01CHDNTC as a String.
  */
  public String getE01CHDNTC()
  {
    return fieldE01CHDNTC.getString();
  }

  /**
  * Set numeric field E01CHDNTC using a BigDecimal value.
  */
  public void setE01CHDNTC(BigDecimal newvalue)
  {
    fieldE01CHDNTC.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CHDNTC as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CHDNTC()
  {
    return fieldE01CHDNTC.getBigDecimal();
  }

  /**
  * Set field E01CHDDBR using a String value.
  */
  public void setE01CHDDBR(String newvalue)
  {
    fieldE01CHDDBR.setString(newvalue);
  }

  /**
  * Get value of field E01CHDDBR as a String.
  */
  public String getE01CHDDBR()
  {
    return fieldE01CHDDBR.getString();
  }

  /**
  * Set numeric field E01CHDDBR using a BigDecimal value.
  */
  public void setE01CHDDBR(BigDecimal newvalue)
  {
    fieldE01CHDDBR.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CHDDBR as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CHDDBR()
  {
    return fieldE01CHDDBR.getBigDecimal();
  }

  /**
  * Set field E01CHDDES using a String value.
  */
  public void setE01CHDDES(String newvalue)
  {
    fieldE01CHDDES.setString(newvalue);
  }

  /**
  * Get value of field E01CHDDES as a String.
  */
  public String getE01CHDDES()
  {
    return fieldE01CHDDES.getString();
  }

  /**
  * Set numeric field E01CHDDES using a BigDecimal value.
  */
  public void setE01CHDDES(BigDecimal newvalue)
  {
    fieldE01CHDDES.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CHDDES as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CHDDES()
  {
    return fieldE01CHDDES.getBigDecimal();
  }

  /**
  * Set field E01CHDACT using a String value.
  */
  public void setE01CHDACT(String newvalue)
  {
    fieldE01CHDACT.setString(newvalue);
  }

  /**
  * Get value of field E01CHDACT as a String.
  */
  public String getE01CHDACT()
  {
    return fieldE01CHDACT.getString();
  }

  /**
  * Set field E01CHDSTS using a String value.
  */
  public void setE01CHDSTS(String newvalue)
  {
    fieldE01CHDSTS.setString(newvalue);
  }

  /**
  * Get value of field E01CHDSTS as a String.
  */
  public String getE01CHDSTS()
  {
    return fieldE01CHDSTS.getString();
  }

  /**
  * Set field E01CHDSDS using a String value.
  */
  public void setE01CHDSDS(String newvalue)
  {
    fieldE01CHDSDS.setString(newvalue);
  }

  /**
  * Get value of field E01CHDSDS as a String.
  */
  public String getE01CHDSDS()
  {
    return fieldE01CHDSDS.getString();
  }

  /**
  * Set field E01OPECDE using a String value.
  */
  public void setE01OPECDE(String newvalue)
  {
    fieldE01OPECDE.setString(newvalue);
  }

  /**
  * Get value of field E01OPECDE as a String.
  */
  public String getE01OPECDE()
  {
    return fieldE01OPECDE.getString();
  }

}
