package datapro.eibs.beans;

import datapro.eibs.sockets.*;
import java.io.*;
import java.math.*;

import java.util.*;

/**
* Class generated by AS/400 CRTCLASS command from EDD400201 physical file definition.
* 
* File level identifier is 1060517151825.
* Record format level identifier is 47366F3B8B608.
*/

public class EDD400201Message extends MessageRecord
{
  final static String fldnames[] = {
                                     "H01USERID",
                                     "H01PROGRM",
                                     "H01TIMSYS",
                                     "H01SCRCOD",
                                     "H01OPECOD",
                                     "H01FLGMAS",
                                     "H01FLGWK1",
                                     "H01FLGWK2",
                                     "H01FLGWK3",
                                     "E01DDCBNK",
                                     "E01DDCCIA",
                                     "E01DDCZON",
                                     "E01DDCPTY",
                                     "E01DDCFRQ",
                                     "E01DDCCUN",
                                     "E01DDCDBK",
                                     "E01DDCDBR",
                                     "E01DDCDCY",
                                     "E01DDCDGL",
                                     "E01DDCDAC",
                                     "E01DDCCBK",
                                     "E01DDCCBR",
                                     "E01DDCCCY",
                                     "E01DDCCGL",
                                     "E01DDCCAC",
                                     "E01DDCLP1",
                                     "E01DDCLP2",
                                     "E01DDCLP3",
                                     "E01DDCBTH",
                                     "E01DDCTBK",
                                     "E01DDCTBR",
                                     "E01DDCTCY",
                                     "E01DDCTGL",
                                     "E01DDCTAC",
                                     "E01DDCFPO",
                                     "E01DDCCOM",
                                     "E01DDCIVA",
                                     "E01DDCTXN",
                                     "E01DDCRBK",
                                     "E01DDCRBR",
                                     "E01DDCRCY",
                                     "E01DDCRGL",
                                     "E01DDCRAC",
                                     "E01DDCRFP",
                                     "E01DDCRCO",
                                     "E01DDCRIV",
                                     "E01DDCRTX",
                                     "E01DDCUC1",
                                     "E01DDCUC2",
                                     "E01DDCUC3",
                                     "E01DDCUC4",
                                     "E01DDCTEE",
                                     "E01DDCTEM",
                                     "E01DDCLTD",
                                     "E01DDCYTD",
                                     "E01DDCREL",
                                     "E01DDCEMP",
                                     "E01DDCAF1",
                                     "E01DDCAF2",
                                     "E01DDCAF3",
                                     "E01DDCLA1",
                                     "E01DDCLA2",
                                     "E01DDCLA3",
                                     "E01CUSNA1",
                                     "E01CIADSC",
                                     "E01RELDSC",
                                     "E01UC1DSC",
                                     "E01UC2DSC",
                                     "E01UC3DSC",
                                     "E01UC4DSC",
                                     "E01AMOUNT",
                                     "E01VALDT1",
                                     "E01VALDT2",
                                     "E01VALDT3",
                                     "E01CNORCD",
                                     "E01CNODSC",
                                     "E01DEBCRE"
                                   };
  final static String tnames[] = {
                                   "H01USERID",
                                   "H01PROGRM",
                                   "H01TIMSYS",
                                   "H01SCRCOD",
                                   "H01OPECOD",
                                   "H01FLGMAS",
                                   "H01FLGWK1",
                                   "H01FLGWK2",
                                   "H01FLGWK3",
                                   "E01DDCBNK",
                                   "E01DDCCIA",
                                   "E01DDCZON",
                                   "E01DDCPTY",
                                   "E01DDCFRQ",
                                   "E01DDCCUN",
                                   "E01DDCDBK",
                                   "E01DDCDBR",
                                   "E01DDCDCY",
                                   "E01DDCDGL",
                                   "E01DDCDAC",
                                   "E01DDCCBK",
                                   "E01DDCCBR",
                                   "E01DDCCCY",
                                   "E01DDCCGL",
                                   "E01DDCCAC",
                                   "E01DDCLP1",
                                   "E01DDCLP2",
                                   "E01DDCLP3",
                                   "E01DDCBTH",
                                   "E01DDCTBK",
                                   "E01DDCTBR",
                                   "E01DDCTCY",
                                   "E01DDCTGL",
                                   "E01DDCTAC",
                                   "E01DDCFPO",
                                   "E01DDCCOM",
                                   "E01DDCIVA",
                                   "E01DDCTXN",
                                   "E01DDCRBK",
                                   "E01DDCRBR",
                                   "E01DDCRCY",
                                   "E01DDCRGL",
                                   "E01DDCRAC",
                                   "E01DDCRFP",
                                   "E01DDCRCO",
                                   "E01DDCRIV",
                                   "E01DDCRTX",
                                   "E01DDCUC1",
                                   "E01DDCUC2",
                                   "E01DDCUC3",
                                   "E01DDCUC4",
                                   "E01DDCTEE",
                                   "E01DDCTEM",
                                   "E01DDCLTD",
                                   "E01DDCYTD",
                                   "E01DDCREL",
                                   "E01DDCEMP",
                                   "E01DDCAF1",
                                   "E01DDCAF2",
                                   "E01DDCAF3",
                                   "E01DDCLA1",
                                   "E01DDCLA2",
                                   "E01DDCLA3",
                                   "E01CUSNA1",
                                   "E01CIADSC",
                                   "E01RELDSC",
                                   "E01UC1DSC",
                                   "E01UC2DSC",
                                   "E01UC3DSC",
                                   "E01UC4DSC",
                                   "E01AMOUNT",
                                   "E01VALDT1",
                                   "E01VALDT2",
                                   "E01VALDT3",
                                   "E01CNORCD",
                                   "E01CNODSC",
                                   "E01DEBCRE"
                                 };
  final static String fid = "1060517151825";
  final static String rid = "47366F3B8B608";
  final static String fmtname = "EDD400201";
  final int FIELDCOUNT = 77;
  private static Hashtable tlookup = new Hashtable();
  private CharacterField fieldH01USERID = null;
  private CharacterField fieldH01PROGRM = null;
  private CharacterField fieldH01TIMSYS = null;
  private CharacterField fieldH01SCRCOD = null;
  private CharacterField fieldH01OPECOD = null;
  private CharacterField fieldH01FLGMAS = null;
  private CharacterField fieldH01FLGWK1 = null;
  private CharacterField fieldH01FLGWK2 = null;
  private CharacterField fieldH01FLGWK3 = null;
  private CharacterField fieldE01DDCBNK = null;
  private CharacterField fieldE01DDCCIA = null;
  private CharacterField fieldE01DDCZON = null;
  private CharacterField fieldE01DDCPTY = null;
  private CharacterField fieldE01DDCFRQ = null;
  private DecimalField fieldE01DDCCUN = null;
  private CharacterField fieldE01DDCDBK = null;
  private DecimalField fieldE01DDCDBR = null;
  private CharacterField fieldE01DDCDCY = null;
  private DecimalField fieldE01DDCDGL = null;
  private DecimalField fieldE01DDCDAC = null;
  private CharacterField fieldE01DDCCBK = null;
  private DecimalField fieldE01DDCCBR = null;
  private CharacterField fieldE01DDCCCY = null;
  private DecimalField fieldE01DDCCGL = null;
  private DecimalField fieldE01DDCCAC = null;
  private DecimalField fieldE01DDCLP1 = null;
  private DecimalField fieldE01DDCLP2 = null;
  private DecimalField fieldE01DDCLP3 = null;
  private DecimalField fieldE01DDCBTH = null;
  private CharacterField fieldE01DDCTBK = null;
  private DecimalField fieldE01DDCTBR = null;
  private CharacterField fieldE01DDCTCY = null;
  private DecimalField fieldE01DDCTGL = null;
  private DecimalField fieldE01DDCTAC = null;
  private CharacterField fieldE01DDCFPO = null;
  private DecimalField fieldE01DDCCOM = null;
  private CharacterField fieldE01DDCIVA = null;
  private CharacterField fieldE01DDCTXN = null;
  private CharacterField fieldE01DDCRBK = null;
  private DecimalField fieldE01DDCRBR = null;
  private CharacterField fieldE01DDCRCY = null;
  private DecimalField fieldE01DDCRGL = null;
  private DecimalField fieldE01DDCRAC = null;
  private CharacterField fieldE01DDCRFP = null;
  private DecimalField fieldE01DDCRCO = null;
  private CharacterField fieldE01DDCRIV = null;
  private CharacterField fieldE01DDCRTX = null;
  private CharacterField fieldE01DDCUC1 = null;
  private CharacterField fieldE01DDCUC2 = null;
  private CharacterField fieldE01DDCUC3 = null;
  private CharacterField fieldE01DDCUC4 = null;
  private DecimalField fieldE01DDCTEE = null;
  private DecimalField fieldE01DDCTEM = null;
  private DecimalField fieldE01DDCLTD = null;
  private DecimalField fieldE01DDCYTD = null;
  private CharacterField fieldE01DDCREL = null;
  private DecimalField fieldE01DDCEMP = null;
  private DecimalField fieldE01DDCAF1 = null;
  private DecimalField fieldE01DDCAF2 = null;
  private DecimalField fieldE01DDCAF3 = null;
  private DecimalField fieldE01DDCLA1 = null;
  private DecimalField fieldE01DDCLA2 = null;
  private DecimalField fieldE01DDCLA3 = null;
  private CharacterField fieldE01CUSNA1 = null;
  private CharacterField fieldE01CIADSC = null;
  private CharacterField fieldE01RELDSC = null;
  private CharacterField fieldE01UC1DSC = null;
  private CharacterField fieldE01UC2DSC = null;
  private CharacterField fieldE01UC3DSC = null;
  private CharacterField fieldE01UC4DSC = null;
  private DecimalField fieldE01AMOUNT = null;
  private DecimalField fieldE01VALDT1 = null;
  private DecimalField fieldE01VALDT2 = null;
  private DecimalField fieldE01VALDT3 = null;
  private CharacterField fieldE01CNORCD = null;
  private CharacterField fieldE01CNODSC = null;
  private CharacterField fieldE01DEBCRE = null;

  /**
  * Constructor for EDD400201Message.
  */
  public EDD400201Message()
  {
    createFields();
    initialize();
  }

  /**
  * Create fields for this message.
  * This method implements the abstract method in the MessageRecord superclass.
  */
  protected void createFields()
  {
    recordsize = 707;
    fileid = fid;
    recordid = rid;
    message = new byte[getByteLength()];
    formatname = fmtname;
    fieldnames = fldnames;
    tagnames = tnames;
    fields = new MessageField[FIELDCOUNT];

    fields[0] = fieldH01USERID =
    new CharacterField(message, HEADERSIZE + 0, 10, "H01USERID");
    fields[1] = fieldH01PROGRM =
    new CharacterField(message, HEADERSIZE + 10, 10, "H01PROGRM");
    fields[2] = fieldH01TIMSYS =
    new CharacterField(message, HEADERSIZE + 20, 12, "H01TIMSYS");
    fields[3] = fieldH01SCRCOD =
    new CharacterField(message, HEADERSIZE + 32, 2, "H01SCRCOD");
    fields[4] = fieldH01OPECOD =
    new CharacterField(message, HEADERSIZE + 34, 4, "H01OPECOD");
    fields[5] = fieldH01FLGMAS =
    new CharacterField(message, HEADERSIZE + 38, 1, "H01FLGMAS");
    fields[6] = fieldH01FLGWK1 =
    new CharacterField(message, HEADERSIZE + 39, 1, "H01FLGWK1");
    fields[7] = fieldH01FLGWK2 =
    new CharacterField(message, HEADERSIZE + 40, 1, "H01FLGWK2");
    fields[8] = fieldH01FLGWK3 =
    new CharacterField(message, HEADERSIZE + 41, 1, "H01FLGWK3");
    fields[9] = fieldE01DDCBNK =
    new CharacterField(message, HEADERSIZE + 42, 2, "E01DDCBNK");
    fields[10] = fieldE01DDCCIA =
    new CharacterField(message, HEADERSIZE + 44, 4, "E01DDCCIA");
    fields[11] = fieldE01DDCZON =
    new CharacterField(message, HEADERSIZE + 48, 1, "E01DDCZON");
    fields[12] = fieldE01DDCPTY =
    new CharacterField(message, HEADERSIZE + 49, 1, "E01DDCPTY");
    fields[13] = fieldE01DDCFRQ =
    new CharacterField(message, HEADERSIZE + 50, 2, "E01DDCFRQ");
    fields[14] = fieldE01DDCCUN =
    new DecimalField(message, HEADERSIZE + 52, 10, 0, "E01DDCCUN");
    fields[15] = fieldE01DDCDBK =
    new CharacterField(message, HEADERSIZE + 62, 2, "E01DDCDBK");
    fields[16] = fieldE01DDCDBR =
    new DecimalField(message, HEADERSIZE + 64, 4, 0, "E01DDCDBR");
    fields[17] = fieldE01DDCDCY =
    new CharacterField(message, HEADERSIZE + 68, 3, "E01DDCDCY");
    fields[18] = fieldE01DDCDGL =
    new DecimalField(message, HEADERSIZE + 71, 17, 0, "E01DDCDGL");
    fields[19] = fieldE01DDCDAC =
    new DecimalField(message, HEADERSIZE + 88, 13, 0, "E01DDCDAC");
    fields[20] = fieldE01DDCCBK =
    new CharacterField(message, HEADERSIZE + 101, 2, "E01DDCCBK");
    fields[21] = fieldE01DDCCBR =
    new DecimalField(message, HEADERSIZE + 103, 4, 0, "E01DDCCBR");
    fields[22] = fieldE01DDCCCY =
    new CharacterField(message, HEADERSIZE + 107, 3, "E01DDCCCY");
    fields[23] = fieldE01DDCCGL =
    new DecimalField(message, HEADERSIZE + 110, 17, 0, "E01DDCCGL");
    fields[24] = fieldE01DDCCAC =
    new DecimalField(message, HEADERSIZE + 127, 13, 0, "E01DDCCAC");
    fields[25] = fieldE01DDCLP1 =
    new DecimalField(message, HEADERSIZE + 140, 3, 0, "E01DDCLP1");
    fields[26] = fieldE01DDCLP2 =
    new DecimalField(message, HEADERSIZE + 143, 3, 0, "E01DDCLP2");
    fields[27] = fieldE01DDCLP3 =
    new DecimalField(message, HEADERSIZE + 146, 3, 0, "E01DDCLP3");
    fields[28] = fieldE01DDCBTH =
    new DecimalField(message, HEADERSIZE + 149, 5, 0, "E01DDCBTH");
    fields[29] = fieldE01DDCTBK =
    new CharacterField(message, HEADERSIZE + 154, 2, "E01DDCTBK");
    fields[30] = fieldE01DDCTBR =
    new DecimalField(message, HEADERSIZE + 156, 4, 0, "E01DDCTBR");
    fields[31] = fieldE01DDCTCY =
    new CharacterField(message, HEADERSIZE + 160, 3, "E01DDCTCY");
    fields[32] = fieldE01DDCTGL =
    new DecimalField(message, HEADERSIZE + 163, 17, 0, "E01DDCTGL");
    fields[33] = fieldE01DDCTAC =
    new DecimalField(message, HEADERSIZE + 180, 13, 0, "E01DDCTAC");
    fields[34] = fieldE01DDCFPO =
    new CharacterField(message, HEADERSIZE + 193, 1, "E01DDCFPO");
    fields[35] = fieldE01DDCCOM =
    new DecimalField(message, HEADERSIZE + 194, 17, 2, "E01DDCCOM");
    fields[36] = fieldE01DDCIVA =
    new CharacterField(message, HEADERSIZE + 211, 1, "E01DDCIVA");
    fields[37] = fieldE01DDCTXN =
    new CharacterField(message, HEADERSIZE + 212, 1, "E01DDCTXN");
    fields[38] = fieldE01DDCRBK =
    new CharacterField(message, HEADERSIZE + 213, 2, "E01DDCRBK");
    fields[39] = fieldE01DDCRBR =
    new DecimalField(message, HEADERSIZE + 215, 4, 0, "E01DDCRBR");
    fields[40] = fieldE01DDCRCY =
    new CharacterField(message, HEADERSIZE + 219, 3, "E01DDCRCY");
    fields[41] = fieldE01DDCRGL =
    new DecimalField(message, HEADERSIZE + 222, 17, 0, "E01DDCRGL");
    fields[42] = fieldE01DDCRAC =
    new DecimalField(message, HEADERSIZE + 239, 13, 0, "E01DDCRAC");
    fields[43] = fieldE01DDCRFP =
    new CharacterField(message, HEADERSIZE + 252, 1, "E01DDCRFP");
    fields[44] = fieldE01DDCRCO =
    new DecimalField(message, HEADERSIZE + 253, 17, 2, "E01DDCRCO");
    fields[45] = fieldE01DDCRIV =
    new CharacterField(message, HEADERSIZE + 270, 1, "E01DDCRIV");
    fields[46] = fieldE01DDCRTX =
    new CharacterField(message, HEADERSIZE + 271, 1, "E01DDCRTX");
    fields[47] = fieldE01DDCUC1 =
    new CharacterField(message, HEADERSIZE + 272, 4, "E01DDCUC1");
    fields[48] = fieldE01DDCUC2 =
    new CharacterField(message, HEADERSIZE + 276, 4, "E01DDCUC2");
    fields[49] = fieldE01DDCUC3 =
    new CharacterField(message, HEADERSIZE + 280, 4, "E01DDCUC3");
    fields[50] = fieldE01DDCUC4 =
    new CharacterField(message, HEADERSIZE + 284, 6, "E01DDCUC4");
    fields[51] = fieldE01DDCTEE =
    new DecimalField(message, HEADERSIZE + 290, 17, 2, "E01DDCTEE");
    fields[52] = fieldE01DDCTEM =
    new DecimalField(message, HEADERSIZE + 307, 17, 2, "E01DDCTEM");
    fields[53] = fieldE01DDCLTD =
    new DecimalField(message, HEADERSIZE + 324, 17, 2, "E01DDCLTD");
    fields[54] = fieldE01DDCYTD =
    new DecimalField(message, HEADERSIZE + 341, 17, 2, "E01DDCYTD");
    fields[55] = fieldE01DDCREL =
    new CharacterField(message, HEADERSIZE + 358, 4, "E01DDCREL");
    fields[56] = fieldE01DDCEMP =
    new DecimalField(message, HEADERSIZE + 362, 6, 0, "E01DDCEMP");
    fields[57] = fieldE01DDCAF1 =
    new DecimalField(message, HEADERSIZE + 368, 3, 0, "E01DDCAF1");
    fields[58] = fieldE01DDCAF2 =
    new DecimalField(message, HEADERSIZE + 371, 3, 0, "E01DDCAF2");
    fields[59] = fieldE01DDCAF3 =
    new DecimalField(message, HEADERSIZE + 374, 3, 0, "E01DDCAF3");
    fields[60] = fieldE01DDCLA1 =
    new DecimalField(message, HEADERSIZE + 377, 3, 0, "E01DDCLA1");
    fields[61] = fieldE01DDCLA2 =
    new DecimalField(message, HEADERSIZE + 380, 3, 0, "E01DDCLA2");
    fields[62] = fieldE01DDCLA3 =
    new DecimalField(message, HEADERSIZE + 383, 3, 0, "E01DDCLA3");
    fields[63] = fieldE01CUSNA1 =
    new CharacterField(message, HEADERSIZE + 386, 45, "E01CUSNA1");
    fields[64] = fieldE01CIADSC =
    new CharacterField(message, HEADERSIZE + 431, 35, "E01CIADSC");
    fields[65] = fieldE01RELDSC =
    new CharacterField(message, HEADERSIZE + 466, 35, "E01RELDSC");
    fields[66] = fieldE01UC1DSC =
    new CharacterField(message, HEADERSIZE + 501, 35, "E01UC1DSC");
    fields[67] = fieldE01UC2DSC =
    new CharacterField(message, HEADERSIZE + 536, 35, "E01UC2DSC");
    fields[68] = fieldE01UC3DSC =
    new CharacterField(message, HEADERSIZE + 571, 35, "E01UC3DSC");
    fields[69] = fieldE01UC4DSC =
    new CharacterField(message, HEADERSIZE + 606, 35, "E01UC4DSC");
    fields[70] = fieldE01AMOUNT =
    new DecimalField(message, HEADERSIZE + 641, 17, 2, "E01AMOUNT");
    fields[71] = fieldE01VALDT1 =
    new DecimalField(message, HEADERSIZE + 658, 3, 0, "E01VALDT1");
    fields[72] = fieldE01VALDT2 =
    new DecimalField(message, HEADERSIZE + 661, 3, 0, "E01VALDT2");
    fields[73] = fieldE01VALDT3 =
    new DecimalField(message, HEADERSIZE + 664, 3, 0, "E01VALDT3");
    fields[74] = fieldE01CNORCD =
    new CharacterField(message, HEADERSIZE + 667, 4, "E01CNORCD");
    fields[75] = fieldE01CNODSC =
    new CharacterField(message, HEADERSIZE + 671, 35, "E01CNODSC");
    fields[76] = fieldE01DEBCRE =
    new CharacterField(message, HEADERSIZE + 706, 1, "E01DEBCRE");

    synchronized (tlookup)
    {
      if (tlookup.isEmpty())
      {
        for (int i = 0; i < tnames.length; i++)
          tlookup.put(tnames[i], new Integer(i));
      }
    }

    taglookup = tlookup;
  }

  /**
  * Set field H01USERID using a String value.
  */
  public void setH01USERID(String newvalue)
  {
    fieldH01USERID.setString(newvalue);
  }

  /**
  * Get value of field H01USERID as a String.
  */
  public String getH01USERID()
  {
    return fieldH01USERID.getString();
  }

  /**
  * Set field H01PROGRM using a String value.
  */
  public void setH01PROGRM(String newvalue)
  {
    fieldH01PROGRM.setString(newvalue);
  }

  /**
  * Get value of field H01PROGRM as a String.
  */
  public String getH01PROGRM()
  {
    return fieldH01PROGRM.getString();
  }

  /**
  * Set field H01TIMSYS using a String value.
  */
  public void setH01TIMSYS(String newvalue)
  {
    fieldH01TIMSYS.setString(newvalue);
  }

  /**
  * Get value of field H01TIMSYS as a String.
  */
  public String getH01TIMSYS()
  {
    return fieldH01TIMSYS.getString();
  }

  /**
  * Set field H01SCRCOD using a String value.
  */
  public void setH01SCRCOD(String newvalue)
  {
    fieldH01SCRCOD.setString(newvalue);
  }

  /**
  * Get value of field H01SCRCOD as a String.
  */
  public String getH01SCRCOD()
  {
    return fieldH01SCRCOD.getString();
  }

  /**
  * Set field H01OPECOD using a String value.
  */
  public void setH01OPECOD(String newvalue)
  {
    fieldH01OPECOD.setString(newvalue);
  }

  /**
  * Get value of field H01OPECOD as a String.
  */
  public String getH01OPECOD()
  {
    return fieldH01OPECOD.getString();
  }

  /**
  * Set field H01FLGMAS using a String value.
  */
  public void setH01FLGMAS(String newvalue)
  {
    fieldH01FLGMAS.setString(newvalue);
  }

  /**
  * Get value of field H01FLGMAS as a String.
  */
  public String getH01FLGMAS()
  {
    return fieldH01FLGMAS.getString();
  }

  /**
  * Set field H01FLGWK1 using a String value.
  */
  public void setH01FLGWK1(String newvalue)
  {
    fieldH01FLGWK1.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK1 as a String.
  */
  public String getH01FLGWK1()
  {
    return fieldH01FLGWK1.getString();
  }

  /**
  * Set field H01FLGWK2 using a String value.
  */
  public void setH01FLGWK2(String newvalue)
  {
    fieldH01FLGWK2.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK2 as a String.
  */
  public String getH01FLGWK2()
  {
    return fieldH01FLGWK2.getString();
  }

  /**
  * Set field H01FLGWK3 using a String value.
  */
  public void setH01FLGWK3(String newvalue)
  {
    fieldH01FLGWK3.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK3 as a String.
  */
  public String getH01FLGWK3()
  {
    return fieldH01FLGWK3.getString();
  }

  /**
  * Set field E01DDCBNK using a String value.
  */
  public void setE01DDCBNK(String newvalue)
  {
    fieldE01DDCBNK.setString(newvalue);
  }

  /**
  * Get value of field E01DDCBNK as a String.
  */
  public String getE01DDCBNK()
  {
    return fieldE01DDCBNK.getString();
  }

  /**
  * Set field E01DDCCIA using a String value.
  */
  public void setE01DDCCIA(String newvalue)
  {
    fieldE01DDCCIA.setString(newvalue);
  }

  /**
  * Get value of field E01DDCCIA as a String.
  */
  public String getE01DDCCIA()
  {
    return fieldE01DDCCIA.getString();
  }

  /**
  * Set field E01DDCZON using a String value.
  */
  public void setE01DDCZON(String newvalue)
  {
    fieldE01DDCZON.setString(newvalue);
  }

  /**
  * Get value of field E01DDCZON as a String.
  */
  public String getE01DDCZON()
  {
    return fieldE01DDCZON.getString();
  }

  /**
  * Set field E01DDCPTY using a String value.
  */
  public void setE01DDCPTY(String newvalue)
  {
    fieldE01DDCPTY.setString(newvalue);
  }

  /**
  * Get value of field E01DDCPTY as a String.
  */
  public String getE01DDCPTY()
  {
    return fieldE01DDCPTY.getString();
  }

  /**
  * Set field E01DDCFRQ using a String value.
  */
  public void setE01DDCFRQ(String newvalue)
  {
    fieldE01DDCFRQ.setString(newvalue);
  }

  /**
  * Get value of field E01DDCFRQ as a String.
  */
  public String getE01DDCFRQ()
  {
    return fieldE01DDCFRQ.getString();
  }

  /**
  * Set field E01DDCCUN using a String value.
  */
  public void setE01DDCCUN(String newvalue)
  {
    fieldE01DDCCUN.setString(newvalue);
  }

  /**
  * Get value of field E01DDCCUN as a String.
  */
  public String getE01DDCCUN()
  {
    return fieldE01DDCCUN.getString();
  }

  /**
  * Set numeric field E01DDCCUN using a BigDecimal value.
  */
  public void setE01DDCCUN(BigDecimal newvalue)
  {
    fieldE01DDCCUN.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DDCCUN as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DDCCUN()
  {
    return fieldE01DDCCUN.getBigDecimal();
  }

  /**
  * Set field E01DDCDBK using a String value.
  */
  public void setE01DDCDBK(String newvalue)
  {
    fieldE01DDCDBK.setString(newvalue);
  }

  /**
  * Get value of field E01DDCDBK as a String.
  */
  public String getE01DDCDBK()
  {
    return fieldE01DDCDBK.getString();
  }

  /**
  * Set field E01DDCDBR using a String value.
  */
  public void setE01DDCDBR(String newvalue)
  {
    fieldE01DDCDBR.setString(newvalue);
  }

  /**
  * Get value of field E01DDCDBR as a String.
  */
  public String getE01DDCDBR()
  {
    return fieldE01DDCDBR.getString();
  }

  /**
  * Set numeric field E01DDCDBR using a BigDecimal value.
  */
  public void setE01DDCDBR(BigDecimal newvalue)
  {
    fieldE01DDCDBR.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DDCDBR as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DDCDBR()
  {
    return fieldE01DDCDBR.getBigDecimal();
  }

  /**
  * Set field E01DDCDCY using a String value.
  */
  public void setE01DDCDCY(String newvalue)
  {
    fieldE01DDCDCY.setString(newvalue);
  }

  /**
  * Get value of field E01DDCDCY as a String.
  */
  public String getE01DDCDCY()
  {
    return fieldE01DDCDCY.getString();
  }

  /**
  * Set field E01DDCDGL using a String value.
  */
  public void setE01DDCDGL(String newvalue)
  {
    fieldE01DDCDGL.setString(newvalue);
  }

  /**
  * Get value of field E01DDCDGL as a String.
  */
  public String getE01DDCDGL()
  {
    return fieldE01DDCDGL.getString();
  }

  /**
  * Set numeric field E01DDCDGL using a BigDecimal value.
  */
  public void setE01DDCDGL(BigDecimal newvalue)
  {
    fieldE01DDCDGL.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DDCDGL as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DDCDGL()
  {
    return fieldE01DDCDGL.getBigDecimal();
  }

  /**
  * Set field E01DDCDAC using a String value.
  */
  public void setE01DDCDAC(String newvalue)
  {
    fieldE01DDCDAC.setString(newvalue);
  }

  /**
  * Get value of field E01DDCDAC as a String.
  */
  public String getE01DDCDAC()
  {
    return fieldE01DDCDAC.getString();
  }

  /**
  * Set numeric field E01DDCDAC using a BigDecimal value.
  */
  public void setE01DDCDAC(BigDecimal newvalue)
  {
    fieldE01DDCDAC.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DDCDAC as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DDCDAC()
  {
    return fieldE01DDCDAC.getBigDecimal();
  }

  /**
  * Set field E01DDCCBK using a String value.
  */
  public void setE01DDCCBK(String newvalue)
  {
    fieldE01DDCCBK.setString(newvalue);
  }

  /**
  * Get value of field E01DDCCBK as a String.
  */
  public String getE01DDCCBK()
  {
    return fieldE01DDCCBK.getString();
  }

  /**
  * Set field E01DDCCBR using a String value.
  */
  public void setE01DDCCBR(String newvalue)
  {
    fieldE01DDCCBR.setString(newvalue);
  }

  /**
  * Get value of field E01DDCCBR as a String.
  */
  public String getE01DDCCBR()
  {
    return fieldE01DDCCBR.getString();
  }

  /**
  * Set numeric field E01DDCCBR using a BigDecimal value.
  */
  public void setE01DDCCBR(BigDecimal newvalue)
  {
    fieldE01DDCCBR.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DDCCBR as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DDCCBR()
  {
    return fieldE01DDCCBR.getBigDecimal();
  }

  /**
  * Set field E01DDCCCY using a String value.
  */
  public void setE01DDCCCY(String newvalue)
  {
    fieldE01DDCCCY.setString(newvalue);
  }

  /**
  * Get value of field E01DDCCCY as a String.
  */
  public String getE01DDCCCY()
  {
    return fieldE01DDCCCY.getString();
  }

  /**
  * Set field E01DDCCGL using a String value.
  */
  public void setE01DDCCGL(String newvalue)
  {
    fieldE01DDCCGL.setString(newvalue);
  }

  /**
  * Get value of field E01DDCCGL as a String.
  */
  public String getE01DDCCGL()
  {
    return fieldE01DDCCGL.getString();
  }

  /**
  * Set numeric field E01DDCCGL using a BigDecimal value.
  */
  public void setE01DDCCGL(BigDecimal newvalue)
  {
    fieldE01DDCCGL.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DDCCGL as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DDCCGL()
  {
    return fieldE01DDCCGL.getBigDecimal();
  }

  /**
  * Set field E01DDCCAC using a String value.
  */
  public void setE01DDCCAC(String newvalue)
  {
    fieldE01DDCCAC.setString(newvalue);
  }

  /**
  * Get value of field E01DDCCAC as a String.
  */
  public String getE01DDCCAC()
  {
    return fieldE01DDCCAC.getString();
  }

  /**
  * Set numeric field E01DDCCAC using a BigDecimal value.
  */
  public void setE01DDCCAC(BigDecimal newvalue)
  {
    fieldE01DDCCAC.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DDCCAC as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DDCCAC()
  {
    return fieldE01DDCCAC.getBigDecimal();
  }

  /**
  * Set field E01DDCLP1 using a String value.
  */
  public void setE01DDCLP1(String newvalue)
  {
    fieldE01DDCLP1.setString(newvalue);
  }

  /**
  * Get value of field E01DDCLP1 as a String.
  */
  public String getE01DDCLP1()
  {
    return fieldE01DDCLP1.getString();
  }

  /**
  * Set numeric field E01DDCLP1 using a BigDecimal value.
  */
  public void setE01DDCLP1(BigDecimal newvalue)
  {
    fieldE01DDCLP1.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DDCLP1 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DDCLP1()
  {
    return fieldE01DDCLP1.getBigDecimal();
  }

  /**
  * Set field E01DDCLP2 using a String value.
  */
  public void setE01DDCLP2(String newvalue)
  {
    fieldE01DDCLP2.setString(newvalue);
  }

  /**
  * Get value of field E01DDCLP2 as a String.
  */
  public String getE01DDCLP2()
  {
    return fieldE01DDCLP2.getString();
  }

  /**
  * Set numeric field E01DDCLP2 using a BigDecimal value.
  */
  public void setE01DDCLP2(BigDecimal newvalue)
  {
    fieldE01DDCLP2.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DDCLP2 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DDCLP2()
  {
    return fieldE01DDCLP2.getBigDecimal();
  }

  /**
  * Set field E01DDCLP3 using a String value.
  */
  public void setE01DDCLP3(String newvalue)
  {
    fieldE01DDCLP3.setString(newvalue);
  }

  /**
  * Get value of field E01DDCLP3 as a String.
  */
  public String getE01DDCLP3()
  {
    return fieldE01DDCLP3.getString();
  }

  /**
  * Set numeric field E01DDCLP3 using a BigDecimal value.
  */
  public void setE01DDCLP3(BigDecimal newvalue)
  {
    fieldE01DDCLP3.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DDCLP3 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DDCLP3()
  {
    return fieldE01DDCLP3.getBigDecimal();
  }

  /**
  * Set field E01DDCBTH using a String value.
  */
  public void setE01DDCBTH(String newvalue)
  {
    fieldE01DDCBTH.setString(newvalue);
  }

  /**
  * Get value of field E01DDCBTH as a String.
  */
  public String getE01DDCBTH()
  {
    return fieldE01DDCBTH.getString();
  }

  /**
  * Set numeric field E01DDCBTH using a BigDecimal value.
  */
  public void setE01DDCBTH(BigDecimal newvalue)
  {
    fieldE01DDCBTH.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DDCBTH as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DDCBTH()
  {
    return fieldE01DDCBTH.getBigDecimal();
  }

  /**
  * Set field E01DDCTBK using a String value.
  */
  public void setE01DDCTBK(String newvalue)
  {
    fieldE01DDCTBK.setString(newvalue);
  }

  /**
  * Get value of field E01DDCTBK as a String.
  */
  public String getE01DDCTBK()
  {
    return fieldE01DDCTBK.getString();
  }

  /**
  * Set field E01DDCTBR using a String value.
  */
  public void setE01DDCTBR(String newvalue)
  {
    fieldE01DDCTBR.setString(newvalue);
  }

  /**
  * Get value of field E01DDCTBR as a String.
  */
  public String getE01DDCTBR()
  {
    return fieldE01DDCTBR.getString();
  }

  /**
  * Set numeric field E01DDCTBR using a BigDecimal value.
  */
  public void setE01DDCTBR(BigDecimal newvalue)
  {
    fieldE01DDCTBR.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DDCTBR as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DDCTBR()
  {
    return fieldE01DDCTBR.getBigDecimal();
  }

  /**
  * Set field E01DDCTCY using a String value.
  */
  public void setE01DDCTCY(String newvalue)
  {
    fieldE01DDCTCY.setString(newvalue);
  }

  /**
  * Get value of field E01DDCTCY as a String.
  */
  public String getE01DDCTCY()
  {
    return fieldE01DDCTCY.getString();
  }

  /**
  * Set field E01DDCTGL using a String value.
  */
  public void setE01DDCTGL(String newvalue)
  {
    fieldE01DDCTGL.setString(newvalue);
  }

  /**
  * Get value of field E01DDCTGL as a String.
  */
  public String getE01DDCTGL()
  {
    return fieldE01DDCTGL.getString();
  }

  /**
  * Set numeric field E01DDCTGL using a BigDecimal value.
  */
  public void setE01DDCTGL(BigDecimal newvalue)
  {
    fieldE01DDCTGL.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DDCTGL as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DDCTGL()
  {
    return fieldE01DDCTGL.getBigDecimal();
  }

  /**
  * Set field E01DDCTAC using a String value.
  */
  public void setE01DDCTAC(String newvalue)
  {
    fieldE01DDCTAC.setString(newvalue);
  }

  /**
  * Get value of field E01DDCTAC as a String.
  */
  public String getE01DDCTAC()
  {
    return fieldE01DDCTAC.getString();
  }

  /**
  * Set numeric field E01DDCTAC using a BigDecimal value.
  */
  public void setE01DDCTAC(BigDecimal newvalue)
  {
    fieldE01DDCTAC.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DDCTAC as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DDCTAC()
  {
    return fieldE01DDCTAC.getBigDecimal();
  }

  /**
  * Set field E01DDCFPO using a String value.
  */
  public void setE01DDCFPO(String newvalue)
  {
    fieldE01DDCFPO.setString(newvalue);
  }

  /**
  * Get value of field E01DDCFPO as a String.
  */
  public String getE01DDCFPO()
  {
    return fieldE01DDCFPO.getString();
  }

  /**
  * Set field E01DDCCOM using a String value.
  */
  public void setE01DDCCOM(String newvalue)
  {
    fieldE01DDCCOM.setString(newvalue);
  }

  /**
  * Get value of field E01DDCCOM as a String.
  */
  public String getE01DDCCOM()
  {
    return fieldE01DDCCOM.getString();
  }

  /**
  * Set numeric field E01DDCCOM using a BigDecimal value.
  */
  public void setE01DDCCOM(BigDecimal newvalue)
  {
    fieldE01DDCCOM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DDCCOM as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DDCCOM()
  {
    return fieldE01DDCCOM.getBigDecimal();
  }

  /**
  * Set field E01DDCIVA using a String value.
  */
  public void setE01DDCIVA(String newvalue)
  {
    fieldE01DDCIVA.setString(newvalue);
  }

  /**
  * Get value of field E01DDCIVA as a String.
  */
  public String getE01DDCIVA()
  {
    return fieldE01DDCIVA.getString();
  }

  /**
  * Set field E01DDCTXN using a String value.
  */
  public void setE01DDCTXN(String newvalue)
  {
    fieldE01DDCTXN.setString(newvalue);
  }

  /**
  * Get value of field E01DDCTXN as a String.
  */
  public String getE01DDCTXN()
  {
    return fieldE01DDCTXN.getString();
  }

  /**
  * Set field E01DDCRBK using a String value.
  */
  public void setE01DDCRBK(String newvalue)
  {
    fieldE01DDCRBK.setString(newvalue);
  }

  /**
  * Get value of field E01DDCRBK as a String.
  */
  public String getE01DDCRBK()
  {
    return fieldE01DDCRBK.getString();
  }

  /**
  * Set field E01DDCRBR using a String value.
  */
  public void setE01DDCRBR(String newvalue)
  {
    fieldE01DDCRBR.setString(newvalue);
  }

  /**
  * Get value of field E01DDCRBR as a String.
  */
  public String getE01DDCRBR()
  {
    return fieldE01DDCRBR.getString();
  }

  /**
  * Set numeric field E01DDCRBR using a BigDecimal value.
  */
  public void setE01DDCRBR(BigDecimal newvalue)
  {
    fieldE01DDCRBR.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DDCRBR as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DDCRBR()
  {
    return fieldE01DDCRBR.getBigDecimal();
  }

  /**
  * Set field E01DDCRCY using a String value.
  */
  public void setE01DDCRCY(String newvalue)
  {
    fieldE01DDCRCY.setString(newvalue);
  }

  /**
  * Get value of field E01DDCRCY as a String.
  */
  public String getE01DDCRCY()
  {
    return fieldE01DDCRCY.getString();
  }

  /**
  * Set field E01DDCRGL using a String value.
  */
  public void setE01DDCRGL(String newvalue)
  {
    fieldE01DDCRGL.setString(newvalue);
  }

  /**
  * Get value of field E01DDCRGL as a String.
  */
  public String getE01DDCRGL()
  {
    return fieldE01DDCRGL.getString();
  }

  /**
  * Set numeric field E01DDCRGL using a BigDecimal value.
  */
  public void setE01DDCRGL(BigDecimal newvalue)
  {
    fieldE01DDCRGL.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DDCRGL as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DDCRGL()
  {
    return fieldE01DDCRGL.getBigDecimal();
  }

  /**
  * Set field E01DDCRAC using a String value.
  */
  public void setE01DDCRAC(String newvalue)
  {
    fieldE01DDCRAC.setString(newvalue);
  }

  /**
  * Get value of field E01DDCRAC as a String.
  */
  public String getE01DDCRAC()
  {
    return fieldE01DDCRAC.getString();
  }

  /**
  * Set numeric field E01DDCRAC using a BigDecimal value.
  */
  public void setE01DDCRAC(BigDecimal newvalue)
  {
    fieldE01DDCRAC.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DDCRAC as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DDCRAC()
  {
    return fieldE01DDCRAC.getBigDecimal();
  }

  /**
  * Set field E01DDCRFP using a String value.
  */
  public void setE01DDCRFP(String newvalue)
  {
    fieldE01DDCRFP.setString(newvalue);
  }

  /**
  * Get value of field E01DDCRFP as a String.
  */
  public String getE01DDCRFP()
  {
    return fieldE01DDCRFP.getString();
  }

  /**
  * Set field E01DDCRCO using a String value.
  */
  public void setE01DDCRCO(String newvalue)
  {
    fieldE01DDCRCO.setString(newvalue);
  }

  /**
  * Get value of field E01DDCRCO as a String.
  */
  public String getE01DDCRCO()
  {
    return fieldE01DDCRCO.getString();
  }

  /**
  * Set numeric field E01DDCRCO using a BigDecimal value.
  */
  public void setE01DDCRCO(BigDecimal newvalue)
  {
    fieldE01DDCRCO.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DDCRCO as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DDCRCO()
  {
    return fieldE01DDCRCO.getBigDecimal();
  }

  /**
  * Set field E01DDCRIV using a String value.
  */
  public void setE01DDCRIV(String newvalue)
  {
    fieldE01DDCRIV.setString(newvalue);
  }

  /**
  * Get value of field E01DDCRIV as a String.
  */
  public String getE01DDCRIV()
  {
    return fieldE01DDCRIV.getString();
  }

  /**
  * Set field E01DDCRTX using a String value.
  */
  public void setE01DDCRTX(String newvalue)
  {
    fieldE01DDCRTX.setString(newvalue);
  }

  /**
  * Get value of field E01DDCRTX as a String.
  */
  public String getE01DDCRTX()
  {
    return fieldE01DDCRTX.getString();
  }

  /**
  * Set field E01DDCUC1 using a String value.
  */
  public void setE01DDCUC1(String newvalue)
  {
    fieldE01DDCUC1.setString(newvalue);
  }

  /**
  * Get value of field E01DDCUC1 as a String.
  */
  public String getE01DDCUC1()
  {
    return fieldE01DDCUC1.getString();
  }

  /**
  * Set field E01DDCUC2 using a String value.
  */
  public void setE01DDCUC2(String newvalue)
  {
    fieldE01DDCUC2.setString(newvalue);
  }

  /**
  * Get value of field E01DDCUC2 as a String.
  */
  public String getE01DDCUC2()
  {
    return fieldE01DDCUC2.getString();
  }

  /**
  * Set field E01DDCUC3 using a String value.
  */
  public void setE01DDCUC3(String newvalue)
  {
    fieldE01DDCUC3.setString(newvalue);
  }

  /**
  * Get value of field E01DDCUC3 as a String.
  */
  public String getE01DDCUC3()
  {
    return fieldE01DDCUC3.getString();
  }

  /**
  * Set field E01DDCUC4 using a String value.
  */
  public void setE01DDCUC4(String newvalue)
  {
    fieldE01DDCUC4.setString(newvalue);
  }

  /**
  * Get value of field E01DDCUC4 as a String.
  */
  public String getE01DDCUC4()
  {
    return fieldE01DDCUC4.getString();
  }

  /**
  * Set field E01DDCTEE using a String value.
  */
  public void setE01DDCTEE(String newvalue)
  {
    fieldE01DDCTEE.setString(newvalue);
  }

  /**
  * Get value of field E01DDCTEE as a String.
  */
  public String getE01DDCTEE()
  {
    return fieldE01DDCTEE.getString();
  }

  /**
  * Set numeric field E01DDCTEE using a BigDecimal value.
  */
  public void setE01DDCTEE(BigDecimal newvalue)
  {
    fieldE01DDCTEE.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DDCTEE as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DDCTEE()
  {
    return fieldE01DDCTEE.getBigDecimal();
  }

  /**
  * Set field E01DDCTEM using a String value.
  */
  public void setE01DDCTEM(String newvalue)
  {
    fieldE01DDCTEM.setString(newvalue);
  }

  /**
  * Get value of field E01DDCTEM as a String.
  */
  public String getE01DDCTEM()
  {
    return fieldE01DDCTEM.getString();
  }

  /**
  * Set numeric field E01DDCTEM using a BigDecimal value.
  */
  public void setE01DDCTEM(BigDecimal newvalue)
  {
    fieldE01DDCTEM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DDCTEM as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DDCTEM()
  {
    return fieldE01DDCTEM.getBigDecimal();
  }

  /**
  * Set field E01DDCLTD using a String value.
  */
  public void setE01DDCLTD(String newvalue)
  {
    fieldE01DDCLTD.setString(newvalue);
  }

  /**
  * Get value of field E01DDCLTD as a String.
  */
  public String getE01DDCLTD()
  {
    return fieldE01DDCLTD.getString();
  }

  /**
  * Set numeric field E01DDCLTD using a BigDecimal value.
  */
  public void setE01DDCLTD(BigDecimal newvalue)
  {
    fieldE01DDCLTD.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DDCLTD as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DDCLTD()
  {
    return fieldE01DDCLTD.getBigDecimal();
  }

  /**
  * Set field E01DDCYTD using a String value.
  */
  public void setE01DDCYTD(String newvalue)
  {
    fieldE01DDCYTD.setString(newvalue);
  }

  /**
  * Get value of field E01DDCYTD as a String.
  */
  public String getE01DDCYTD()
  {
    return fieldE01DDCYTD.getString();
  }

  /**
  * Set numeric field E01DDCYTD using a BigDecimal value.
  */
  public void setE01DDCYTD(BigDecimal newvalue)
  {
    fieldE01DDCYTD.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DDCYTD as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DDCYTD()
  {
    return fieldE01DDCYTD.getBigDecimal();
  }

  /**
  * Set field E01DDCREL using a String value.
  */
  public void setE01DDCREL(String newvalue)
  {
    fieldE01DDCREL.setString(newvalue);
  }

  /**
  * Get value of field E01DDCREL as a String.
  */
  public String getE01DDCREL()
  {
    return fieldE01DDCREL.getString();
  }

  /**
  * Set field E01DDCEMP using a String value.
  */
  public void setE01DDCEMP(String newvalue)
  {
    fieldE01DDCEMP.setString(newvalue);
  }

  /**
  * Get value of field E01DDCEMP as a String.
  */
  public String getE01DDCEMP()
  {
    return fieldE01DDCEMP.getString();
  }

  /**
  * Set numeric field E01DDCEMP using a BigDecimal value.
  */
  public void setE01DDCEMP(BigDecimal newvalue)
  {
    fieldE01DDCEMP.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DDCEMP as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DDCEMP()
  {
    return fieldE01DDCEMP.getBigDecimal();
  }

  /**
  * Set field E01DDCAF1 using a String value.
  */
  public void setE01DDCAF1(String newvalue)
  {
    fieldE01DDCAF1.setString(newvalue);
  }

  /**
  * Get value of field E01DDCAF1 as a String.
  */
  public String getE01DDCAF1()
  {
    return fieldE01DDCAF1.getString();
  }

  /**
  * Set numeric field E01DDCAF1 using a BigDecimal value.
  */
  public void setE01DDCAF1(BigDecimal newvalue)
  {
    fieldE01DDCAF1.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DDCAF1 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DDCAF1()
  {
    return fieldE01DDCAF1.getBigDecimal();
  }

  /**
  * Set field E01DDCAF2 using a String value.
  */
  public void setE01DDCAF2(String newvalue)
  {
    fieldE01DDCAF2.setString(newvalue);
  }

  /**
  * Get value of field E01DDCAF2 as a String.
  */
  public String getE01DDCAF2()
  {
    return fieldE01DDCAF2.getString();
  }

  /**
  * Set numeric field E01DDCAF2 using a BigDecimal value.
  */
  public void setE01DDCAF2(BigDecimal newvalue)
  {
    fieldE01DDCAF2.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DDCAF2 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DDCAF2()
  {
    return fieldE01DDCAF2.getBigDecimal();
  }

  /**
  * Set field E01DDCAF3 using a String value.
  */
  public void setE01DDCAF3(String newvalue)
  {
    fieldE01DDCAF3.setString(newvalue);
  }

  /**
  * Get value of field E01DDCAF3 as a String.
  */
  public String getE01DDCAF3()
  {
    return fieldE01DDCAF3.getString();
  }

  /**
  * Set numeric field E01DDCAF3 using a BigDecimal value.
  */
  public void setE01DDCAF3(BigDecimal newvalue)
  {
    fieldE01DDCAF3.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DDCAF3 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DDCAF3()
  {
    return fieldE01DDCAF3.getBigDecimal();
  }

  /**
  * Set field E01DDCLA1 using a String value.
  */
  public void setE01DDCLA1(String newvalue)
  {
    fieldE01DDCLA1.setString(newvalue);
  }

  /**
  * Get value of field E01DDCLA1 as a String.
  */
  public String getE01DDCLA1()
  {
    return fieldE01DDCLA1.getString();
  }

  /**
  * Set numeric field E01DDCLA1 using a BigDecimal value.
  */
  public void setE01DDCLA1(BigDecimal newvalue)
  {
    fieldE01DDCLA1.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DDCLA1 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DDCLA1()
  {
    return fieldE01DDCLA1.getBigDecimal();
  }

  /**
  * Set field E01DDCLA2 using a String value.
  */
  public void setE01DDCLA2(String newvalue)
  {
    fieldE01DDCLA2.setString(newvalue);
  }

  /**
  * Get value of field E01DDCLA2 as a String.
  */
  public String getE01DDCLA2()
  {
    return fieldE01DDCLA2.getString();
  }

  /**
  * Set numeric field E01DDCLA2 using a BigDecimal value.
  */
  public void setE01DDCLA2(BigDecimal newvalue)
  {
    fieldE01DDCLA2.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DDCLA2 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DDCLA2()
  {
    return fieldE01DDCLA2.getBigDecimal();
  }

  /**
  * Set field E01DDCLA3 using a String value.
  */
  public void setE01DDCLA3(String newvalue)
  {
    fieldE01DDCLA3.setString(newvalue);
  }

  /**
  * Get value of field E01DDCLA3 as a String.
  */
  public String getE01DDCLA3()
  {
    return fieldE01DDCLA3.getString();
  }

  /**
  * Set numeric field E01DDCLA3 using a BigDecimal value.
  */
  public void setE01DDCLA3(BigDecimal newvalue)
  {
    fieldE01DDCLA3.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DDCLA3 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DDCLA3()
  {
    return fieldE01DDCLA3.getBigDecimal();
  }

  /**
  * Set field E01CUSNA1 using a String value.
  */
  public void setE01CUSNA1(String newvalue)
  {
    fieldE01CUSNA1.setString(newvalue);
  }

  /**
  * Get value of field E01CUSNA1 as a String.
  */
  public String getE01CUSNA1()
  {
    return fieldE01CUSNA1.getString();
  }

  /**
  * Set field E01CIADSC using a String value.
  */
  public void setE01CIADSC(String newvalue)
  {
    fieldE01CIADSC.setString(newvalue);
  }

  /**
  * Get value of field E01CIADSC as a String.
  */
  public String getE01CIADSC()
  {
    return fieldE01CIADSC.getString();
  }

  /**
  * Set field E01RELDSC using a String value.
  */
  public void setE01RELDSC(String newvalue)
  {
    fieldE01RELDSC.setString(newvalue);
  }

  /**
  * Get value of field E01RELDSC as a String.
  */
  public String getE01RELDSC()
  {
    return fieldE01RELDSC.getString();
  }

  /**
  * Set field E01UC1DSC using a String value.
  */
  public void setE01UC1DSC(String newvalue)
  {
    fieldE01UC1DSC.setString(newvalue);
  }

  /**
  * Get value of field E01UC1DSC as a String.
  */
  public String getE01UC1DSC()
  {
    return fieldE01UC1DSC.getString();
  }

  /**
  * Set field E01UC2DSC using a String value.
  */
  public void setE01UC2DSC(String newvalue)
  {
    fieldE01UC2DSC.setString(newvalue);
  }

  /**
  * Get value of field E01UC2DSC as a String.
  */
  public String getE01UC2DSC()
  {
    return fieldE01UC2DSC.getString();
  }

  /**
  * Set field E01UC3DSC using a String value.
  */
  public void setE01UC3DSC(String newvalue)
  {
    fieldE01UC3DSC.setString(newvalue);
  }

  /**
  * Get value of field E01UC3DSC as a String.
  */
  public String getE01UC3DSC()
  {
    return fieldE01UC3DSC.getString();
  }

  /**
  * Set field E01UC4DSC using a String value.
  */
  public void setE01UC4DSC(String newvalue)
  {
    fieldE01UC4DSC.setString(newvalue);
  }

  /**
  * Get value of field E01UC4DSC as a String.
  */
  public String getE01UC4DSC()
  {
    return fieldE01UC4DSC.getString();
  }

  /**
  * Set field E01AMOUNT using a String value.
  */
  public void setE01AMOUNT(String newvalue)
  {
    fieldE01AMOUNT.setString(newvalue);
  }

  /**
  * Get value of field E01AMOUNT as a String.
  */
  public String getE01AMOUNT()
  {
    return fieldE01AMOUNT.getString();
  }

  /**
  * Set numeric field E01AMOUNT using a BigDecimal value.
  */
  public void setE01AMOUNT(BigDecimal newvalue)
  {
    fieldE01AMOUNT.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01AMOUNT as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01AMOUNT()
  {
    return fieldE01AMOUNT.getBigDecimal();
  }

  /**
  * Set field E01VALDT1 using a String value.
  */
  public void setE01VALDT1(String newvalue)
  {
    fieldE01VALDT1.setString(newvalue);
  }

  /**
  * Get value of field E01VALDT1 as a String.
  */
  public String getE01VALDT1()
  {
    return fieldE01VALDT1.getString();
  }

  /**
  * Set numeric field E01VALDT1 using a BigDecimal value.
  */
  public void setE01VALDT1(BigDecimal newvalue)
  {
    fieldE01VALDT1.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01VALDT1 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01VALDT1()
  {
    return fieldE01VALDT1.getBigDecimal();
  }

  /**
  * Set field E01VALDT2 using a String value.
  */
  public void setE01VALDT2(String newvalue)
  {
    fieldE01VALDT2.setString(newvalue);
  }

  /**
  * Get value of field E01VALDT2 as a String.
  */
  public String getE01VALDT2()
  {
    return fieldE01VALDT2.getString();
  }

  /**
  * Set numeric field E01VALDT2 using a BigDecimal value.
  */
  public void setE01VALDT2(BigDecimal newvalue)
  {
    fieldE01VALDT2.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01VALDT2 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01VALDT2()
  {
    return fieldE01VALDT2.getBigDecimal();
  }

  /**
  * Set field E01VALDT3 using a String value.
  */
  public void setE01VALDT3(String newvalue)
  {
    fieldE01VALDT3.setString(newvalue);
  }

  /**
  * Get value of field E01VALDT3 as a String.
  */
  public String getE01VALDT3()
  {
    return fieldE01VALDT3.getString();
  }

  /**
  * Set numeric field E01VALDT3 using a BigDecimal value.
  */
  public void setE01VALDT3(BigDecimal newvalue)
  {
    fieldE01VALDT3.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01VALDT3 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01VALDT3()
  {
    return fieldE01VALDT3.getBigDecimal();
  }

  /**
  * Set field E01CNORCD using a String value.
  */
  public void setE01CNORCD(String newvalue)
  {
    fieldE01CNORCD.setString(newvalue);
  }

  /**
  * Get value of field E01CNORCD as a String.
  */
  public String getE01CNORCD()
  {
    return fieldE01CNORCD.getString();
  }

  /**
  * Set field E01CNODSC using a String value.
  */
  public void setE01CNODSC(String newvalue)
  {
    fieldE01CNODSC.setString(newvalue);
  }

  /**
  * Get value of field E01CNODSC as a String.
  */
  public String getE01CNODSC()
  {
    return fieldE01CNODSC.getString();
  }

  /**
  * Set field E01DEBCRE using a String value.
  */
  public void setE01DEBCRE(String newvalue)
  {
    fieldE01DEBCRE.setString(newvalue);
  }

  /**
  * Get value of field E01DEBCRE as a String.
  */
  public String getE01DEBCRE()
  {
    return fieldE01DEBCRE.getString();
  }

}
