package datapro.eibs.beans;

import datapro.eibs.sockets.*;
import java.io.*;
import java.math.*;

import java.util.*;

/**
* Class generated by AS/400 CRTCLASS command from EDL013503 physical file definition.
* 
* File level identifier is 1030121191857.
* Record format level identifier is 337B226BD6D33.
*/

public class EDL013503Message extends MessageRecord
{
  final static String fldnames[] = {
                                     "H03USERID",
                                     "H03PROGRM",
                                     "H03TIMSYS",
                                     "H03SCRCOD",
                                     "H03OPECOD",
                                     "H03FLGMAS",
                                     "H03FLGWK1",
                                     "H03FLGWK2",
                                     "H03FLGWK3",
                                     "E03DEAACC",
                                     "E03DLDNDR",
                                     "E03DEAACD",
                                     "E03DEAPRO",
                                     "E03DEATYP",
                                     "E03DEACUN",
                                     "E03CUSNA1",
                                     "E03DSCPRO",
                                     "E03DLSNST",
                                     "E03DLSOST",
                                     "E03DLSDT1",
                                     "E03DLSDT2",
                                     "E03DLSDT3",
                                     "E03DLSUSR",
                                     "E03DLSTIM",
                                     "E03DLSOFC",
                                     "E03DSCOFC",
                                     "E03DSCUSR"
                                   };
  final static String tnames[] = {
                                   "H03USERID",
                                   "H03PROGRM",
                                   "H03TIMSYS",
                                   "H03SCRCOD",
                                   "H03OPECOD",
                                   "H03FLGMAS",
                                   "H03FLGWK1",
                                   "H03FLGWK2",
                                   "H03FLGWK3",
                                   "E03DEAACC",
                                   "E03DLDNDR",
                                   "E03DEAACD",
                                   "E03DEAPRO",
                                   "E03DEATYP",
                                   "E03DEACUN",
                                   "E03CUSNA1",
                                   "E03DSCPRO",
                                   "E03DLSNST",
                                   "E03DLSOST",
                                   "E03DLSDT1",
                                   "E03DLSDT2",
                                   "E03DLSDT3",
                                   "E03DLSUSR",
                                   "E03DLSTIM",
                                   "E03DLSOFC",
                                   "E03DSCOFC",
                                   "E03DSCUSR"
                                 };
  final static String fid = "1030121191857";
  final static String rid = "337B226BD6D33";
  final static String fmtname = "EDL013503";
  final int FIELDCOUNT = 27;
  private static Hashtable tlookup = new Hashtable();
  private CharacterField fieldH03USERID = null;
  private CharacterField fieldH03PROGRM = null;
  private CharacterField fieldH03TIMSYS = null;
  private CharacterField fieldH03SCRCOD = null;
  private CharacterField fieldH03OPECOD = null;
  private CharacterField fieldH03FLGMAS = null;
  private CharacterField fieldH03FLGWK1 = null;
  private CharacterField fieldH03FLGWK2 = null;
  private CharacterField fieldH03FLGWK3 = null;
  private DecimalField fieldE03DEAACC = null;
  private DecimalField fieldE03DLDNDR = null;
  private CharacterField fieldE03DEAACD = null;
  private CharacterField fieldE03DEAPRO = null;
  private CharacterField fieldE03DEATYP = null;
  private DecimalField fieldE03DEACUN = null;
  private CharacterField fieldE03CUSNA1 = null;
  private CharacterField fieldE03DSCPRO = null;
  private CharacterField fieldE03DLSNST = null;
  private CharacterField fieldE03DLSOST = null;
  private DecimalField fieldE03DLSDT1 = null;
  private DecimalField fieldE03DLSDT2 = null;
  private DecimalField fieldE03DLSDT3 = null;
  private CharacterField fieldE03DLSUSR = null;
  private DecimalField fieldE03DLSTIM = null;
  private CharacterField fieldE03DLSOFC = null;
  private CharacterField fieldE03DSCOFC = null;
  private CharacterField fieldE03DSCUSR = null;

  /**
  * Constructor for EDL013503Message.
  */
  public EDL013503Message()
  {
    createFields();
    initialize();
  }

  /**
  * Create fields for this message.
  * This method implements the abstract method in the MessageRecord superclass.
  */
  protected void createFields()
  {
    recordsize = 267;
    fileid = fid;
    recordid = rid;
    message = new byte[getByteLength()];
    formatname = fmtname;
    fieldnames = fldnames;
    tagnames = tnames;
    fields = new MessageField[FIELDCOUNT];

    fields[0] = fieldH03USERID =
    new CharacterField(message, HEADERSIZE + 0, 10, "H03USERID");
    fields[1] = fieldH03PROGRM =
    new CharacterField(message, HEADERSIZE + 10, 10, "H03PROGRM");
    fields[2] = fieldH03TIMSYS =
    new CharacterField(message, HEADERSIZE + 20, 12, "H03TIMSYS");
    fields[3] = fieldH03SCRCOD =
    new CharacterField(message, HEADERSIZE + 32, 2, "H03SCRCOD");
    fields[4] = fieldH03OPECOD =
    new CharacterField(message, HEADERSIZE + 34, 4, "H03OPECOD");
    fields[5] = fieldH03FLGMAS =
    new CharacterField(message, HEADERSIZE + 38, 1, "H03FLGMAS");
    fields[6] = fieldH03FLGWK1 =
    new CharacterField(message, HEADERSIZE + 39, 1, "H03FLGWK1");
    fields[7] = fieldH03FLGWK2 =
    new CharacterField(message, HEADERSIZE + 40, 1, "H03FLGWK2");
    fields[8] = fieldH03FLGWK3 =
    new CharacterField(message, HEADERSIZE + 41, 1, "H03FLGWK3");
    fields[9] = fieldE03DEAACC =
    new DecimalField(message, HEADERSIZE + 42, 13, 0, "E03DEAACC");
    fields[10] = fieldE03DLDNDR =
    new DecimalField(message, HEADERSIZE + 55, 10, 0, "E03DLDNDR");
    fields[11] = fieldE03DEAACD =
    new CharacterField(message, HEADERSIZE + 65, 2, "E03DEAACD");
    fields[12] = fieldE03DEAPRO =
    new CharacterField(message, HEADERSIZE + 67, 4, "E03DEAPRO");
    fields[13] = fieldE03DEATYP =
    new CharacterField(message, HEADERSIZE + 71, 4, "E03DEATYP");
    fields[14] = fieldE03DEACUN =
    new DecimalField(message, HEADERSIZE + 75, 10, 0, "E03DEACUN");
    fields[15] = fieldE03CUSNA1 =
    new CharacterField(message, HEADERSIZE + 85, 45, "E03CUSNA1");
    fields[16] = fieldE03DSCPRO =
    new CharacterField(message, HEADERSIZE + 130, 35, "E03DSCPRO");
    fields[17] = fieldE03DLSNST =
    new CharacterField(message, HEADERSIZE + 165, 1, "E03DLSNST");
    fields[18] = fieldE03DLSOST =
    new CharacterField(message, HEADERSIZE + 166, 1, "E03DLSOST");
    fields[19] = fieldE03DLSDT1 =
    new DecimalField(message, HEADERSIZE + 167, 3, 0, "E03DLSDT1");
    fields[20] = fieldE03DLSDT2 =
    new DecimalField(message, HEADERSIZE + 170, 3, 0, "E03DLSDT2");
    fields[21] = fieldE03DLSDT3 =
    new DecimalField(message, HEADERSIZE + 173, 3, 0, "E03DLSDT3");
    fields[22] = fieldE03DLSUSR =
    new CharacterField(message, HEADERSIZE + 176, 10, "E03DLSUSR");
    fields[23] = fieldE03DLSTIM =
    new DecimalField(message, HEADERSIZE + 186, 7, 0, "E03DLSTIM");
    fields[24] = fieldE03DLSOFC =
    new CharacterField(message, HEADERSIZE + 193, 4, "E03DLSOFC");
    fields[25] = fieldE03DSCOFC =
    new CharacterField(message, HEADERSIZE + 197, 35, "E03DSCOFC");
    fields[26] = fieldE03DSCUSR =
    new CharacterField(message, HEADERSIZE + 232, 35, "E03DSCUSR");

    synchronized (tlookup)
    {
      if (tlookup.isEmpty())
      {
        for (int i = 0; i < tnames.length; i++)
          tlookup.put(tnames[i], new Integer(i));
      }
    }

    taglookup = tlookup;
  }

  /**
  * Set field H03USERID using a String value.
  */
  public void setH03USERID(String newvalue)
  {
    fieldH03USERID.setString(newvalue);
  }

  /**
  * Get value of field H03USERID as a String.
  */
  public String getH03USERID()
  {
    return fieldH03USERID.getString();
  }

  /**
  * Set field H03PROGRM using a String value.
  */
  public void setH03PROGRM(String newvalue)
  {
    fieldH03PROGRM.setString(newvalue);
  }

  /**
  * Get value of field H03PROGRM as a String.
  */
  public String getH03PROGRM()
  {
    return fieldH03PROGRM.getString();
  }

  /**
  * Set field H03TIMSYS using a String value.
  */
  public void setH03TIMSYS(String newvalue)
  {
    fieldH03TIMSYS.setString(newvalue);
  }

  /**
  * Get value of field H03TIMSYS as a String.
  */
  public String getH03TIMSYS()
  {
    return fieldH03TIMSYS.getString();
  }

  /**
  * Set field H03SCRCOD using a String value.
  */
  public void setH03SCRCOD(String newvalue)
  {
    fieldH03SCRCOD.setString(newvalue);
  }

  /**
  * Get value of field H03SCRCOD as a String.
  */
  public String getH03SCRCOD()
  {
    return fieldH03SCRCOD.getString();
  }

  /**
  * Set field H03OPECOD using a String value.
  */
  public void setH03OPECOD(String newvalue)
  {
    fieldH03OPECOD.setString(newvalue);
  }

  /**
  * Get value of field H03OPECOD as a String.
  */
  public String getH03OPECOD()
  {
    return fieldH03OPECOD.getString();
  }

  /**
  * Set field H03FLGMAS using a String value.
  */
  public void setH03FLGMAS(String newvalue)
  {
    fieldH03FLGMAS.setString(newvalue);
  }

  /**
  * Get value of field H03FLGMAS as a String.
  */
  public String getH03FLGMAS()
  {
    return fieldH03FLGMAS.getString();
  }

  /**
  * Set field H03FLGWK1 using a String value.
  */
  public void setH03FLGWK1(String newvalue)
  {
    fieldH03FLGWK1.setString(newvalue);
  }

  /**
  * Get value of field H03FLGWK1 as a String.
  */
  public String getH03FLGWK1()
  {
    return fieldH03FLGWK1.getString();
  }

  /**
  * Set field H03FLGWK2 using a String value.
  */
  public void setH03FLGWK2(String newvalue)
  {
    fieldH03FLGWK2.setString(newvalue);
  }

  /**
  * Get value of field H03FLGWK2 as a String.
  */
  public String getH03FLGWK2()
  {
    return fieldH03FLGWK2.getString();
  }

  /**
  * Set field H03FLGWK3 using a String value.
  */
  public void setH03FLGWK3(String newvalue)
  {
    fieldH03FLGWK3.setString(newvalue);
  }

  /**
  * Get value of field H03FLGWK3 as a String.
  */
  public String getH03FLGWK3()
  {
    return fieldH03FLGWK3.getString();
  }

  /**
  * Set field E03DEAACC using a String value.
  */
  public void setE03DEAACC(String newvalue)
  {
    fieldE03DEAACC.setString(newvalue);
  }

  /**
  * Get value of field E03DEAACC as a String.
  */
  public String getE03DEAACC()
  {
    return fieldE03DEAACC.getString();
  }

  /**
  * Set numeric field E03DEAACC using a BigDecimal value.
  */
  public void setE03DEAACC(BigDecimal newvalue)
  {
    fieldE03DEAACC.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E03DEAACC as a BigDecimal.
  */
  public BigDecimal getBigDecimalE03DEAACC()
  {
    return fieldE03DEAACC.getBigDecimal();
  }

  /**
  * Set field E03DLDNDR using a String value.
  */
  public void setE03DLDNDR(String newvalue)
  {
    fieldE03DLDNDR.setString(newvalue);
  }

  /**
  * Get value of field E03DLDNDR as a String.
  */
  public String getE03DLDNDR()
  {
    return fieldE03DLDNDR.getString();
  }

  /**
  * Set numeric field E03DLDNDR using a BigDecimal value.
  */
  public void setE03DLDNDR(BigDecimal newvalue)
  {
    fieldE03DLDNDR.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E03DLDNDR as a BigDecimal.
  */
  public BigDecimal getBigDecimalE03DLDNDR()
  {
    return fieldE03DLDNDR.getBigDecimal();
  }

  /**
  * Set field E03DEAACD using a String value.
  */
  public void setE03DEAACD(String newvalue)
  {
    fieldE03DEAACD.setString(newvalue);
  }

  /**
  * Get value of field E03DEAACD as a String.
  */
  public String getE03DEAACD()
  {
    return fieldE03DEAACD.getString();
  }

  /**
  * Set field E03DEAPRO using a String value.
  */
  public void setE03DEAPRO(String newvalue)
  {
    fieldE03DEAPRO.setString(newvalue);
  }

  /**
  * Get value of field E03DEAPRO as a String.
  */
  public String getE03DEAPRO()
  {
    return fieldE03DEAPRO.getString();
  }

  /**
  * Set field E03DEATYP using a String value.
  */
  public void setE03DEATYP(String newvalue)
  {
    fieldE03DEATYP.setString(newvalue);
  }

  /**
  * Get value of field E03DEATYP as a String.
  */
  public String getE03DEATYP()
  {
    return fieldE03DEATYP.getString();
  }

  /**
  * Set field E03DEACUN using a String value.
  */
  public void setE03DEACUN(String newvalue)
  {
    fieldE03DEACUN.setString(newvalue);
  }

  /**
  * Get value of field E03DEACUN as a String.
  */
  public String getE03DEACUN()
  {
    return fieldE03DEACUN.getString();
  }

  /**
  * Set numeric field E03DEACUN using a BigDecimal value.
  */
  public void setE03DEACUN(BigDecimal newvalue)
  {
    fieldE03DEACUN.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E03DEACUN as a BigDecimal.
  */
  public BigDecimal getBigDecimalE03DEACUN()
  {
    return fieldE03DEACUN.getBigDecimal();
  }

  /**
  * Set field E03CUSNA1 using a String value.
  */
  public void setE03CUSNA1(String newvalue)
  {
    fieldE03CUSNA1.setString(newvalue);
  }

  /**
  * Get value of field E03CUSNA1 as a String.
  */
  public String getE03CUSNA1()
  {
    return fieldE03CUSNA1.getString();
  }

  /**
  * Set field E03DSCPRO using a String value.
  */
  public void setE03DSCPRO(String newvalue)
  {
    fieldE03DSCPRO.setString(newvalue);
  }

  /**
  * Get value of field E03DSCPRO as a String.
  */
  public String getE03DSCPRO()
  {
    return fieldE03DSCPRO.getString();
  }

  /**
  * Set field E03DLSNST using a String value.
  */
  public void setE03DLSNST(String newvalue)
  {
    fieldE03DLSNST.setString(newvalue);
  }

  /**
  * Get value of field E03DLSNST as a String.
  */
  public String getE03DLSNST()
  {
    return fieldE03DLSNST.getString();
  }

  /**
  * Set field E03DLSOST using a String value.
  */
  public void setE03DLSOST(String newvalue)
  {
    fieldE03DLSOST.setString(newvalue);
  }

  /**
  * Get value of field E03DLSOST as a String.
  */
  public String getE03DLSOST()
  {
    return fieldE03DLSOST.getString();
  }

  /**
  * Set field E03DLSDT1 using a String value.
  */
  public void setE03DLSDT1(String newvalue)
  {
    fieldE03DLSDT1.setString(newvalue);
  }

  /**
  * Get value of field E03DLSDT1 as a String.
  */
  public String getE03DLSDT1()
  {
    return fieldE03DLSDT1.getString();
  }

  /**
  * Set numeric field E03DLSDT1 using a BigDecimal value.
  */
  public void setE03DLSDT1(BigDecimal newvalue)
  {
    fieldE03DLSDT1.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E03DLSDT1 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE03DLSDT1()
  {
    return fieldE03DLSDT1.getBigDecimal();
  }

  /**
  * Set field E03DLSDT2 using a String value.
  */
  public void setE03DLSDT2(String newvalue)
  {
    fieldE03DLSDT2.setString(newvalue);
  }

  /**
  * Get value of field E03DLSDT2 as a String.
  */
  public String getE03DLSDT2()
  {
    return fieldE03DLSDT2.getString();
  }

  /**
  * Set numeric field E03DLSDT2 using a BigDecimal value.
  */
  public void setE03DLSDT2(BigDecimal newvalue)
  {
    fieldE03DLSDT2.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E03DLSDT2 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE03DLSDT2()
  {
    return fieldE03DLSDT2.getBigDecimal();
  }

  /**
  * Set field E03DLSDT3 using a String value.
  */
  public void setE03DLSDT3(String newvalue)
  {
    fieldE03DLSDT3.setString(newvalue);
  }

  /**
  * Get value of field E03DLSDT3 as a String.
  */
  public String getE03DLSDT3()
  {
    return fieldE03DLSDT3.getString();
  }

  /**
  * Set numeric field E03DLSDT3 using a BigDecimal value.
  */
  public void setE03DLSDT3(BigDecimal newvalue)
  {
    fieldE03DLSDT3.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E03DLSDT3 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE03DLSDT3()
  {
    return fieldE03DLSDT3.getBigDecimal();
  }

  /**
  * Set field E03DLSUSR using a String value.
  */
  public void setE03DLSUSR(String newvalue)
  {
    fieldE03DLSUSR.setString(newvalue);
  }

  /**
  * Get value of field E03DLSUSR as a String.
  */
  public String getE03DLSUSR()
  {
    return fieldE03DLSUSR.getString();
  }

  /**
  * Set field E03DLSTIM using a String value.
  */
  public void setE03DLSTIM(String newvalue)
  {
    fieldE03DLSTIM.setString(newvalue);
  }

  /**
  * Get value of field E03DLSTIM as a String.
  */
  public String getE03DLSTIM()
  {
    return fieldE03DLSTIM.getString();
  }

  /**
  * Set numeric field E03DLSTIM using a BigDecimal value.
  */
  public void setE03DLSTIM(BigDecimal newvalue)
  {
    fieldE03DLSTIM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E03DLSTIM as a BigDecimal.
  */
  public BigDecimal getBigDecimalE03DLSTIM()
  {
    return fieldE03DLSTIM.getBigDecimal();
  }

  /**
  * Set field E03DLSOFC using a String value.
  */
  public void setE03DLSOFC(String newvalue)
  {
    fieldE03DLSOFC.setString(newvalue);
  }

  /**
  * Get value of field E03DLSOFC as a String.
  */
  public String getE03DLSOFC()
  {
    return fieldE03DLSOFC.getString();
  }

  /**
  * Set field E03DSCOFC using a String value.
  */
  public void setE03DSCOFC(String newvalue)
  {
    fieldE03DSCOFC.setString(newvalue);
  }

  /**
  * Get value of field E03DSCOFC as a String.
  */
  public String getE03DSCOFC()
  {
    return fieldE03DSCOFC.getString();
  }

  /**
  * Set field E03DSCUSR using a String value.
  */
  public void setE03DSCUSR(String newvalue)
  {
    fieldE03DSCUSR.setString(newvalue);
  }

  /**
  * Get value of field E03DSCUSR as a String.
  */
  public String getE03DSCUSR()
  {
    return fieldE03DSCUSR.getString();
  }

}
