package datapro.eibs.beans;


import datapro.eibs.sockets.*;
import java.io.*;
import java.math.*;

import java.util.*;

/**
* Class generated by AS/400 CRTCLASS command from EDP070301 physical file definition.
* 
* File level identifier is 1060403113458.
* Record format level identifier is 4818AF0648708.
*/

public class EDP070301Message extends MessageRecord
{
  final static String fldnames[] = {
                                     "H01USERID",
                                     "H01PROGRM",
                                     "H01TIMSYS",
                                     "H01SCRCOD",
                                     "H01OPECOD",
                                     "H01FLGMAS",
                                     "H01FLGWK1",
                                     "H01FLGWK2",
                                     "H01FLGWK3",
                                     "E01CNTLAN",
                                     "E01DPXCFO",
                                     "E01DPXDSC",
                                     "E01DPXCLI",
                                     "E01DPXDLI",
                                     "E01DPXGLN",
                                     "E01DPXDSG",
                                     "E01DPXSEC",
                                     "E01DPXLIN",
                                     "E01DSCLIN",
                                     "E01DPXEXP",
                                     "E01DPXFO1",
                                     "E01DPXFO2",
                                     "E01DPXFO3",
                                     "E01DPXFO4",
                                     "E01DPXFO5",
                                     "E01DPXDF1",
                                     "E01DPXDF2",
                                     "E01DPXDF3",
                                     "E01DPXDF4",
                                     "E01DPXDF5",
                                     "E01DPXIBS",
                                     "E01DPXCAC",
                                     "E01DPXMLS",
                                     "E01DPXMLR",
                                     "E01DPXSLS",
                                     "E01DPXSLR",
                                     "E01DPXLME",
                                     "E01RECPOS",
                                     "E01OPECDE"
                                   };
  final static String tnames[] = {
                                   "H01USERID",
                                   "H01PROGRM",
                                   "H01TIMSYS",
                                   "H01SCRCOD",
                                   "H01OPECOD",
                                   "H01FLGMAS",
                                   "H01FLGWK1",
                                   "H01FLGWK2",
                                   "H01FLGWK3",
                                   "E01CNTLAN",
                                   "E01DPXCFO",
                                   "E01DPXDSC",
                                   "E01DPXCLI",
                                   "E01DPXDLI",
                                   "E01DPXGLN",
                                   "E01DPXDSG",
                                   "E01DPXSEC",
                                   "E01DPXLIN",
                                   "E01DSCLIN",
                                   "E01DPXEXP",
                                   "E01DPXFO1",
                                   "E01DPXFO2",
                                   "E01DPXFO3",
                                   "E01DPXFO4",
                                   "E01DPXFO5",
                                   "E01DPXDF1",
                                   "E01DPXDF2",
                                   "E01DPXDF3",
                                   "E01DPXDF4",
                                   "E01DPXDF5",
                                   "E01DPXIBS",
                                   "E01DPXCAC",
                                   "E01DPXMLS",
                                   "E01DPXMLR",
                                   "E01DPXSLS",
                                   "E01DPXSLR",
                                   "E01DPXLME",
                                   "E01RECPOS",
                                   "E01OPECDE"
                                 };
  final static String fid = "1060403113458";
  final static String rid = "4818AF0648708";
  final static String fmtname = "EDP070301";
  final int FIELDCOUNT = 39;
  private static Hashtable tlookup = new Hashtable();
  private CharacterField fieldH01USERID = null;
  private CharacterField fieldH01PROGRM = null;
  private CharacterField fieldH01TIMSYS = null;
  private CharacterField fieldH01SCRCOD = null;
  private CharacterField fieldH01OPECOD = null;
  private CharacterField fieldH01FLGMAS = null;
  private CharacterField fieldH01FLGWK1 = null;
  private CharacterField fieldH01FLGWK2 = null;
  private CharacterField fieldH01FLGWK3 = null;
  private CharacterField fieldE01CNTLAN = null;
  private CharacterField fieldE01DPXCFO = null;
  private CharacterField fieldE01DPXDSC = null;
  private CharacterField fieldE01DPXCLI = null;
  private CharacterField fieldE01DPXDLI = null;
  private DecimalField fieldE01DPXGLN = null;
  private CharacterField fieldE01DPXDSG = null;
  private DecimalField fieldE01DPXSEC = null;
  private CharacterField fieldE01DPXLIN = null;
  private CharacterField fieldE01DSCLIN = null;
  private CharacterField fieldE01DPXEXP = null;
  private CharacterField fieldE01DPXFO1 = null;
  private CharacterField fieldE01DPXFO2 = null;
  private CharacterField fieldE01DPXFO3 = null;
  private CharacterField fieldE01DPXFO4 = null;
  private CharacterField fieldE01DPXFO5 = null;
  private CharacterField fieldE01DPXDF1 = null;
  private CharacterField fieldE01DPXDF2 = null;
  private CharacterField fieldE01DPXDF3 = null;
  private CharacterField fieldE01DPXDF4 = null;
  private CharacterField fieldE01DPXDF5 = null;
  private CharacterField fieldE01DPXIBS = null;
  private CharacterField fieldE01DPXCAC = null;
  private DecimalField fieldE01DPXMLS = null;
  private DecimalField fieldE01DPXMLR = null;
  private DecimalField fieldE01DPXSLS = null;
  private DecimalField fieldE01DPXSLR = null;
  private DecimalField fieldE01DPXLME = null;
  private DecimalField fieldE01RECPOS = null;
  private CharacterField fieldE01OPECDE = null;

  /**
  * Constructor for EDP070301Message.
  */
  public EDP070301Message()
  {
    createFields();
    initialize();
  }

  /**
  * Create fields for this message.
  * This method implements the abstract method in the MessageRecord superclass.
  */
  protected void createFields()
  {
    recordsize = 628;
    fileid = fid;
    recordid = rid;
    message = new byte[getByteLength()];
    formatname = fmtname;
    fieldnames = fldnames;
    tagnames = tnames;
    fields = new MessageField[FIELDCOUNT];

    fields[0] = fieldH01USERID =
    new CharacterField(message, HEADERSIZE + 0, 10, "H01USERID");
    fields[1] = fieldH01PROGRM =
    new CharacterField(message, HEADERSIZE + 10, 10, "H01PROGRM");
    fields[2] = fieldH01TIMSYS =
    new CharacterField(message, HEADERSIZE + 20, 12, "H01TIMSYS");
    fields[3] = fieldH01SCRCOD =
    new CharacterField(message, HEADERSIZE + 32, 2, "H01SCRCOD");
    fields[4] = fieldH01OPECOD =
    new CharacterField(message, HEADERSIZE + 34, 4, "H01OPECOD");
    fields[5] = fieldH01FLGMAS =
    new CharacterField(message, HEADERSIZE + 38, 1, "H01FLGMAS");
    fields[6] = fieldH01FLGWK1 =
    new CharacterField(message, HEADERSIZE + 39, 1, "H01FLGWK1");
    fields[7] = fieldH01FLGWK2 =
    new CharacterField(message, HEADERSIZE + 40, 1, "H01FLGWK2");
    fields[8] = fieldH01FLGWK3 =
    new CharacterField(message, HEADERSIZE + 41, 1, "H01FLGWK3");
    fields[9] = fieldE01CNTLAN =
    new CharacterField(message, HEADERSIZE + 42, 1, "E01CNTLAN");
    fields[10] = fieldE01DPXCFO =
    new CharacterField(message, HEADERSIZE + 43, 1, "E01DPXCFO");
    fields[11] = fieldE01DPXDSC =
    new CharacterField(message, HEADERSIZE + 44, 35, "E01DPXDSC");
    fields[12] = fieldE01DPXCLI =
    new CharacterField(message, HEADERSIZE + 79, 4, "E01DPXCLI");
    fields[13] = fieldE01DPXDLI =
    new CharacterField(message, HEADERSIZE + 83, 35, "E01DPXDLI");
    fields[14] = fieldE01DPXGLN =
    new DecimalField(message, HEADERSIZE + 118, 17, 0, "E01DPXGLN");
    fields[15] = fieldE01DPXDSG =
    new CharacterField(message, HEADERSIZE + 135, 35, "E01DPXDSG");
    fields[16] = fieldE01DPXSEC =
    new DecimalField(message, HEADERSIZE + 170, 6, 0, "E01DPXSEC");
    fields[17] = fieldE01DPXLIN =
    new CharacterField(message, HEADERSIZE + 176, 1, "E01DPXLIN");
    fields[18] = fieldE01DSCLIN =
    new CharacterField(message, HEADERSIZE + 177, 35, "E01DSCLIN");
    fields[19] = fieldE01DPXEXP =
    new CharacterField(message, HEADERSIZE + 212, 200, "E01DPXEXP");
    fields[20] = fieldE01DPXFO1 =
    new CharacterField(message, HEADERSIZE + 412, 2, "E01DPXFO1");
    fields[21] = fieldE01DPXFO2 =
    new CharacterField(message, HEADERSIZE + 414, 2, "E01DPXFO2");
    fields[22] = fieldE01DPXFO3 =
    new CharacterField(message, HEADERSIZE + 416, 2, "E01DPXFO3");
    fields[23] = fieldE01DPXFO4 =
    new CharacterField(message, HEADERSIZE + 418, 2, "E01DPXFO4");
    fields[24] = fieldE01DPXFO5 =
    new CharacterField(message, HEADERSIZE + 420, 2, "E01DPXFO5");
    fields[25] = fieldE01DPXDF1 =
    new CharacterField(message, HEADERSIZE + 422, 35, "E01DPXDF1");
    fields[26] = fieldE01DPXDF2 =
    new CharacterField(message, HEADERSIZE + 457, 35, "E01DPXDF2");
    fields[27] = fieldE01DPXDF3 =
    new CharacterField(message, HEADERSIZE + 492, 35, "E01DPXDF3");
    fields[28] = fieldE01DPXDF4 =
    new CharacterField(message, HEADERSIZE + 527, 35, "E01DPXDF4");
    fields[29] = fieldE01DPXDF5 =
    new CharacterField(message, HEADERSIZE + 562, 35, "E01DPXDF5");
    fields[30] = fieldE01DPXIBS =
    new CharacterField(message, HEADERSIZE + 597, 1, "E01DPXIBS");
    fields[31] = fieldE01DPXCAC =
    new CharacterField(message, HEADERSIZE + 598, 1, "E01DPXCAC");
    fields[32] = fieldE01DPXMLS =
    new DecimalField(message, HEADERSIZE + 599, 4, 0, "E01DPXMLS");
    fields[33] = fieldE01DPXMLR =
    new DecimalField(message, HEADERSIZE + 603, 4, 0, "E01DPXMLR");
    fields[34] = fieldE01DPXSLS =
    new DecimalField(message, HEADERSIZE + 607, 4, 0, "E01DPXSLS");
    fields[35] = fieldE01DPXSLR =
    new DecimalField(message, HEADERSIZE + 611, 4, 0, "E01DPXSLR");
    fields[36] = fieldE01DPXLME =
    new DecimalField(message, HEADERSIZE + 615, 4, 0, "E01DPXLME");
    fields[37] = fieldE01RECPOS =
    new DecimalField(message, HEADERSIZE + 619, 8, 0, "E01RECPOS");
    fields[38] = fieldE01OPECDE =
    new CharacterField(message, HEADERSIZE + 627, 1, "E01OPECDE");

    synchronized (tlookup)
    {
      if (tlookup.isEmpty())
      {
        for (int i = 0; i < tnames.length; i++)
          tlookup.put(tnames[i], new Integer(i));
      }
    }

    taglookup = tlookup;
  }

  /**
  * Set field H01USERID using a String value.
  */
  public void setH01USERID(String newvalue)
  {
    fieldH01USERID.setString(newvalue);
  }

  /**
  * Get value of field H01USERID as a String.
  */
  public String getH01USERID()
  {
    return fieldH01USERID.getString();
  }

  /**
  * Set field H01PROGRM using a String value.
  */
  public void setH01PROGRM(String newvalue)
  {
    fieldH01PROGRM.setString(newvalue);
  }

  /**
  * Get value of field H01PROGRM as a String.
  */
  public String getH01PROGRM()
  {
    return fieldH01PROGRM.getString();
  }

  /**
  * Set field H01TIMSYS using a String value.
  */
  public void setH01TIMSYS(String newvalue)
  {
    fieldH01TIMSYS.setString(newvalue);
  }

  /**
  * Get value of field H01TIMSYS as a String.
  */
  public String getH01TIMSYS()
  {
    return fieldH01TIMSYS.getString();
  }

  /**
  * Set field H01SCRCOD using a String value.
  */
  public void setH01SCRCOD(String newvalue)
  {
    fieldH01SCRCOD.setString(newvalue);
  }

  /**
  * Get value of field H01SCRCOD as a String.
  */
  public String getH01SCRCOD()
  {
    return fieldH01SCRCOD.getString();
  }

  /**
  * Set field H01OPECOD using a String value.
  */
  public void setH01OPECOD(String newvalue)
  {
    fieldH01OPECOD.setString(newvalue);
  }

  /**
  * Get value of field H01OPECOD as a String.
  */
  public String getH01OPECOD()
  {
    return fieldH01OPECOD.getString();
  }

  /**
  * Set field H01FLGMAS using a String value.
  */
  public void setH01FLGMAS(String newvalue)
  {
    fieldH01FLGMAS.setString(newvalue);
  }

  /**
  * Get value of field H01FLGMAS as a String.
  */
  public String getH01FLGMAS()
  {
    return fieldH01FLGMAS.getString();
  }

  /**
  * Set field H01FLGWK1 using a String value.
  */
  public void setH01FLGWK1(String newvalue)
  {
    fieldH01FLGWK1.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK1 as a String.
  */
  public String getH01FLGWK1()
  {
    return fieldH01FLGWK1.getString();
  }

  /**
  * Set field H01FLGWK2 using a String value.
  */
  public void setH01FLGWK2(String newvalue)
  {
    fieldH01FLGWK2.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK2 as a String.
  */
  public String getH01FLGWK2()
  {
    return fieldH01FLGWK2.getString();
  }

  /**
  * Set field H01FLGWK3 using a String value.
  */
  public void setH01FLGWK3(String newvalue)
  {
    fieldH01FLGWK3.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK3 as a String.
  */
  public String getH01FLGWK3()
  {
    return fieldH01FLGWK3.getString();
  }

  /**
  * Set field E01CNTLAN using a String value.
  */
  public void setE01CNTLAN(String newvalue)
  {
    fieldE01CNTLAN.setString(newvalue);
  }

  /**
  * Get value of field E01CNTLAN as a String.
  */
  public String getE01CNTLAN()
  {
    return fieldE01CNTLAN.getString();
  }

  /**
  * Set field E01DPXCFO using a String value.
  */
  public void setE01DPXCFO(String newvalue)
  {
    fieldE01DPXCFO.setString(newvalue);
  }

  /**
  * Get value of field E01DPXCFO as a String.
  */
  public String getE01DPXCFO()
  {
    return fieldE01DPXCFO.getString();
  }

  /**
  * Set field E01DPXDSC using a String value.
  */
  public void setE01DPXDSC(String newvalue)
  {
    fieldE01DPXDSC.setString(newvalue);
  }

  /**
  * Get value of field E01DPXDSC as a String.
  */
  public String getE01DPXDSC()
  {
    return fieldE01DPXDSC.getString();
  }

  /**
  * Set field E01DPXCLI using a String value.
  */
  public void setE01DPXCLI(String newvalue)
  {
    fieldE01DPXCLI.setString(newvalue);
  }

  /**
  * Get value of field E01DPXCLI as a String.
  */
  public String getE01DPXCLI()
  {
    return fieldE01DPXCLI.getString();
  }

  /**
  * Set field E01DPXDLI using a String value.
  */
  public void setE01DPXDLI(String newvalue)
  {
    fieldE01DPXDLI.setString(newvalue);
  }

  /**
  * Get value of field E01DPXDLI as a String.
  */
  public String getE01DPXDLI()
  {
    return fieldE01DPXDLI.getString();
  }

  /**
  * Set field E01DPXGLN using a String value.
  */
  public void setE01DPXGLN(String newvalue)
  {
    fieldE01DPXGLN.setString(newvalue);
  }

  /**
  * Get value of field E01DPXGLN as a String.
  */
  public String getE01DPXGLN()
  {
    return fieldE01DPXGLN.getString();
  }

  /**
  * Set numeric field E01DPXGLN using a BigDecimal value.
  */
  public void setE01DPXGLN(BigDecimal newvalue)
  {
    fieldE01DPXGLN.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DPXGLN as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DPXGLN()
  {
    return fieldE01DPXGLN.getBigDecimal();
  }

  /**
  * Set field E01DPXDSG using a String value.
  */
  public void setE01DPXDSG(String newvalue)
  {
    fieldE01DPXDSG.setString(newvalue);
  }

  /**
  * Get value of field E01DPXDSG as a String.
  */
  public String getE01DPXDSG()
  {
    return fieldE01DPXDSG.getString();
  }

  /**
  * Set field E01DPXSEC using a String value.
  */
  public void setE01DPXSEC(String newvalue)
  {
    fieldE01DPXSEC.setString(newvalue);
  }

  /**
  * Get value of field E01DPXSEC as a String.
  */
  public String getE01DPXSEC()
  {
    return fieldE01DPXSEC.getString();
  }

  /**
  * Set numeric field E01DPXSEC using a BigDecimal value.
  */
  public void setE01DPXSEC(BigDecimal newvalue)
  {
    fieldE01DPXSEC.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DPXSEC as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DPXSEC()
  {
    return fieldE01DPXSEC.getBigDecimal();
  }

  /**
  * Set field E01DPXLIN using a String value.
  */
  public void setE01DPXLIN(String newvalue)
  {
    fieldE01DPXLIN.setString(newvalue);
  }

  /**
  * Get value of field E01DPXLIN as a String.
  */
  public String getE01DPXLIN()
  {
    return fieldE01DPXLIN.getString();
  }

  /**
  * Set field E01DSCLIN using a String value.
  */
  public void setE01DSCLIN(String newvalue)
  {
    fieldE01DSCLIN.setString(newvalue);
  }

  /**
  * Get value of field E01DSCLIN as a String.
  */
  public String getE01DSCLIN()
  {
    return fieldE01DSCLIN.getString();
  }

  /**
  * Set field E01DPXEXP using a String value.
  */
  public void setE01DPXEXP(String newvalue)
  {
    fieldE01DPXEXP.setString(newvalue);
  }

  /**
  * Get value of field E01DPXEXP as a String.
  */
  public String getE01DPXEXP()
  {
    return fieldE01DPXEXP.getString();
  }

  /**
  * Set field E01DPXFO1 using a String value.
  */
  public void setE01DPXFO1(String newvalue)
  {
    fieldE01DPXFO1.setString(newvalue);
  }

  /**
  * Get value of field E01DPXFO1 as a String.
  */
  public String getE01DPXFO1()
  {
    return fieldE01DPXFO1.getString();
  }

  /**
  * Set field E01DPXFO2 using a String value.
  */
  public void setE01DPXFO2(String newvalue)
  {
    fieldE01DPXFO2.setString(newvalue);
  }

  /**
  * Get value of field E01DPXFO2 as a String.
  */
  public String getE01DPXFO2()
  {
    return fieldE01DPXFO2.getString();
  }

  /**
  * Set field E01DPXFO3 using a String value.
  */
  public void setE01DPXFO3(String newvalue)
  {
    fieldE01DPXFO3.setString(newvalue);
  }

  /**
  * Get value of field E01DPXFO3 as a String.
  */
  public String getE01DPXFO3()
  {
    return fieldE01DPXFO3.getString();
  }

  /**
  * Set field E01DPXFO4 using a String value.
  */
  public void setE01DPXFO4(String newvalue)
  {
    fieldE01DPXFO4.setString(newvalue);
  }

  /**
  * Get value of field E01DPXFO4 as a String.
  */
  public String getE01DPXFO4()
  {
    return fieldE01DPXFO4.getString();
  }

  /**
  * Set field E01DPXFO5 using a String value.
  */
  public void setE01DPXFO5(String newvalue)
  {
    fieldE01DPXFO5.setString(newvalue);
  }

  /**
  * Get value of field E01DPXFO5 as a String.
  */
  public String getE01DPXFO5()
  {
    return fieldE01DPXFO5.getString();
  }

  /**
  * Set field E01DPXDF1 using a String value.
  */
  public void setE01DPXDF1(String newvalue)
  {
    fieldE01DPXDF1.setString(newvalue);
  }

  /**
  * Get value of field E01DPXDF1 as a String.
  */
  public String getE01DPXDF1()
  {
    return fieldE01DPXDF1.getString();
  }

  /**
  * Set field E01DPXDF2 using a String value.
  */
  public void setE01DPXDF2(String newvalue)
  {
    fieldE01DPXDF2.setString(newvalue);
  }

  /**
  * Get value of field E01DPXDF2 as a String.
  */
  public String getE01DPXDF2()
  {
    return fieldE01DPXDF2.getString();
  }

  /**
  * Set field E01DPXDF3 using a String value.
  */
  public void setE01DPXDF3(String newvalue)
  {
    fieldE01DPXDF3.setString(newvalue);
  }

  /**
  * Get value of field E01DPXDF3 as a String.
  */
  public String getE01DPXDF3()
  {
    return fieldE01DPXDF3.getString();
  }

  /**
  * Set field E01DPXDF4 using a String value.
  */
  public void setE01DPXDF4(String newvalue)
  {
    fieldE01DPXDF4.setString(newvalue);
  }

  /**
  * Get value of field E01DPXDF4 as a String.
  */
  public String getE01DPXDF4()
  {
    return fieldE01DPXDF4.getString();
  }

  /**
  * Set field E01DPXDF5 using a String value.
  */
  public void setE01DPXDF5(String newvalue)
  {
    fieldE01DPXDF5.setString(newvalue);
  }

  /**
  * Get value of field E01DPXDF5 as a String.
  */
  public String getE01DPXDF5()
  {
    return fieldE01DPXDF5.getString();
  }

  /**
  * Set field E01DPXIBS using a String value.
  */
  public void setE01DPXIBS(String newvalue)
  {
    fieldE01DPXIBS.setString(newvalue);
  }

  /**
  * Get value of field E01DPXIBS as a String.
  */
  public String getE01DPXIBS()
  {
    return fieldE01DPXIBS.getString();
  }

  /**
  * Set field E01DPXCAC using a String value.
  */
  public void setE01DPXCAC(String newvalue)
  {
    fieldE01DPXCAC.setString(newvalue);
  }

  /**
  * Get value of field E01DPXCAC as a String.
  */
  public String getE01DPXCAC()
  {
    return fieldE01DPXCAC.getString();
  }

  /**
  * Set field E01DPXMLS using a String value.
  */
  public void setE01DPXMLS(String newvalue)
  {
    fieldE01DPXMLS.setString(newvalue);
  }

  /**
  * Get value of field E01DPXMLS as a String.
  */
  public String getE01DPXMLS()
  {
    return fieldE01DPXMLS.getString();
  }

  /**
  * Set numeric field E01DPXMLS using a BigDecimal value.
  */
  public void setE01DPXMLS(BigDecimal newvalue)
  {
    fieldE01DPXMLS.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DPXMLS as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DPXMLS()
  {
    return fieldE01DPXMLS.getBigDecimal();
  }

  /**
  * Set field E01DPXMLR using a String value.
  */
  public void setE01DPXMLR(String newvalue)
  {
    fieldE01DPXMLR.setString(newvalue);
  }

  /**
  * Get value of field E01DPXMLR as a String.
  */
  public String getE01DPXMLR()
  {
    return fieldE01DPXMLR.getString();
  }

  /**
  * Set numeric field E01DPXMLR using a BigDecimal value.
  */
  public void setE01DPXMLR(BigDecimal newvalue)
  {
    fieldE01DPXMLR.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DPXMLR as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DPXMLR()
  {
    return fieldE01DPXMLR.getBigDecimal();
  }

  /**
  * Set field E01DPXSLS using a String value.
  */
  public void setE01DPXSLS(String newvalue)
  {
    fieldE01DPXSLS.setString(newvalue);
  }

  /**
  * Get value of field E01DPXSLS as a String.
  */
  public String getE01DPXSLS()
  {
    return fieldE01DPXSLS.getString();
  }

  /**
  * Set numeric field E01DPXSLS using a BigDecimal value.
  */
  public void setE01DPXSLS(BigDecimal newvalue)
  {
    fieldE01DPXSLS.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DPXSLS as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DPXSLS()
  {
    return fieldE01DPXSLS.getBigDecimal();
  }

  /**
  * Set field E01DPXSLR using a String value.
  */
  public void setE01DPXSLR(String newvalue)
  {
    fieldE01DPXSLR.setString(newvalue);
  }

  /**
  * Get value of field E01DPXSLR as a String.
  */
  public String getE01DPXSLR()
  {
    return fieldE01DPXSLR.getString();
  }

  /**
  * Set numeric field E01DPXSLR using a BigDecimal value.
  */
  public void setE01DPXSLR(BigDecimal newvalue)
  {
    fieldE01DPXSLR.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DPXSLR as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DPXSLR()
  {
    return fieldE01DPXSLR.getBigDecimal();
  }

  /**
  * Set field E01DPXLME using a String value.
  */
  public void setE01DPXLME(String newvalue)
  {
    fieldE01DPXLME.setString(newvalue);
  }

  /**
  * Get value of field E01DPXLME as a String.
  */
  public String getE01DPXLME()
  {
    return fieldE01DPXLME.getString();
  }

  /**
  * Set numeric field E01DPXLME using a BigDecimal value.
  */
  public void setE01DPXLME(BigDecimal newvalue)
  {
    fieldE01DPXLME.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DPXLME as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DPXLME()
  {
    return fieldE01DPXLME.getBigDecimal();
  }

  /**
  * Set field E01RECPOS using a String value.
  */
  public void setE01RECPOS(String newvalue)
  {
    fieldE01RECPOS.setString(newvalue);
  }

  /**
  * Get value of field E01RECPOS as a String.
  */
  public String getE01RECPOS()
  {
    return fieldE01RECPOS.getString();
  }

  /**
  * Set numeric field E01RECPOS using a BigDecimal value.
  */
  public void setE01RECPOS(BigDecimal newvalue)
  {
    fieldE01RECPOS.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01RECPOS as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01RECPOS()
  {
    return fieldE01RECPOS.getBigDecimal();
  }

  /**
  * Set field E01OPECDE using a String value.
  */
  public void setE01OPECDE(String newvalue)
  {
    fieldE01OPECDE.setString(newvalue);
  }

  /**
  * Get value of field E01OPECDE as a String.
  */
  public String getE01OPECDE()
  {
    return fieldE01OPECDE.getString();
  }

}
