package datapro.eibs.beans;


import datapro.eibs.sockets.*;
import java.io.*;
import java.math.*;

import java.util.*;

/**
* Class generated by AS/400 CRTCLASS command from EDP074501 physical file definition.
* 
* File level identifier is 1060403113512.
* Record format level identifier is 408CFB9566F3C.
*/

public class EDP074501Message extends MessageRecord
{
  final static String fldnames[] = {
                                     "H02USERID",
                                     "H02PROGRM",
                                     "H02TIMSYS",
                                     "H02SCRCOD",
                                     "H02OPECOD",
                                     "H02FLGMAS",
                                     "H02FLGWK1",
                                     "H02FLGWK2",
                                     "H02FLGWK3",
                                     "E01CNTLAN",
                                     "E02DPVNPR",
                                     "E02DPVM00",
                                     "E02DPVM01",
                                     "E02DPVM02",
                                     "E02DPVM03",
                                     "E02DPVM04",
                                     "E02DPVM05",
                                     "E02DPVM06",
                                     "E02DPVM07",
                                     "E02DPVM08",
                                     "E02DPVM09",
                                     "E02DPVM10",
                                     "E02DPVM98",
                                     "E02DPVM99",
                                     "E02DPVC00",
                                     "E02DPVC01",
                                     "E02DPVC02",
                                     "E02DPVC03",
                                     "E02DPVC04",
                                     "E02DPVC05",
                                     "E02DPVC06",
                                     "E02DPVC07",
                                     "E02DPVC08",
                                     "E02DPVC09",
                                     "E02DPVC10",
                                     "E02DPVC98",
                                     "E02DPVC99",
                                     "E02DPVUSR",
                                     "E02OPECDE"
                                   };
  final static String tnames[] = {
                                   "H02USERID",
                                   "H02PROGRM",
                                   "H02TIMSYS",
                                   "H02SCRCOD",
                                   "H02OPECOD",
                                   "H02FLGMAS",
                                   "H02FLGWK1",
                                   "H02FLGWK2",
                                   "H02FLGWK3",
                                   "E01CNTLAN",
                                   "E02DPVNPR",
                                   "E02DPVM00",
                                   "E02DPVM01",
                                   "E02DPVM02",
                                   "E02DPVM03",
                                   "E02DPVM04",
                                   "E02DPVM05",
                                   "E02DPVM06",
                                   "E02DPVM07",
                                   "E02DPVM08",
                                   "E02DPVM09",
                                   "E02DPVM10",
                                   "E02DPVM98",
                                   "E02DPVM99",
                                   "E02DPVC00",
                                   "E02DPVC01",
                                   "E02DPVC02",
                                   "E02DPVC03",
                                   "E02DPVC04",
                                   "E02DPVC05",
                                   "E02DPVC06",
                                   "E02DPVC07",
                                   "E02DPVC08",
                                   "E02DPVC09",
                                   "E02DPVC10",
                                   "E02DPVC98",
                                   "E02DPVC99",
                                   "E02DPVUSR",
                                   "E02OPECDE"
                                 };
  final static String fid = "1060403113512";
  final static String rid = "408CFB9566F3C";
  final static String fmtname = "EDP074501";
  final int FIELDCOUNT = 39;
  private static Hashtable tlookup = new Hashtable();
  private CharacterField fieldH02USERID = null;
  private CharacterField fieldH02PROGRM = null;
  private CharacterField fieldH02TIMSYS = null;
  private CharacterField fieldH02SCRCOD = null;
  private CharacterField fieldH02OPECOD = null;
  private CharacterField fieldH02FLGMAS = null;
  private CharacterField fieldH02FLGWK1 = null;
  private CharacterField fieldH02FLGWK2 = null;
  private CharacterField fieldH02FLGWK3 = null;
  private CharacterField fieldE01CNTLAN = null;
  private DecimalField fieldE02DPVNPR = null;
  private CharacterField fieldE02DPVM00 = null;
  private CharacterField fieldE02DPVM01 = null;
  private CharacterField fieldE02DPVM02 = null;
  private CharacterField fieldE02DPVM03 = null;
  private CharacterField fieldE02DPVM04 = null;
  private CharacterField fieldE02DPVM05 = null;
  private CharacterField fieldE02DPVM06 = null;
  private CharacterField fieldE02DPVM07 = null;
  private CharacterField fieldE02DPVM08 = null;
  private CharacterField fieldE02DPVM09 = null;
  private CharacterField fieldE02DPVM10 = null;
  private CharacterField fieldE02DPVM98 = null;
  private CharacterField fieldE02DPVM99 = null;
  private CharacterField fieldE02DPVC00 = null;
  private CharacterField fieldE02DPVC01 = null;
  private CharacterField fieldE02DPVC02 = null;
  private CharacterField fieldE02DPVC03 = null;
  private CharacterField fieldE02DPVC04 = null;
  private CharacterField fieldE02DPVC05 = null;
  private CharacterField fieldE02DPVC06 = null;
  private CharacterField fieldE02DPVC07 = null;
  private CharacterField fieldE02DPVC08 = null;
  private CharacterField fieldE02DPVC09 = null;
  private CharacterField fieldE02DPVC10 = null;
  private CharacterField fieldE02DPVC98 = null;
  private CharacterField fieldE02DPVC99 = null;
  private CharacterField fieldE02DPVUSR = null;
  private CharacterField fieldE02OPECDE = null;

  /**
  * Constructor for EDP074501Message.
  */
  public EDP074501Message()
  {
    createFields();
    initialize();
  }

  /**
  * Create fields for this message.
  * This method implements the abstract method in the MessageRecord superclass.
  */
  protected void createFields()
  {
    recordsize = 9193;
    fileid = fid;
    recordid = rid;
    message = new byte[getByteLength()];
    formatname = fmtname;
    fieldnames = fldnames;
    tagnames = tnames;
    fields = new MessageField[FIELDCOUNT];

    fields[0] = fieldH02USERID =
    new CharacterField(message, HEADERSIZE + 0, 10, "H02USERID");
    fields[1] = fieldH02PROGRM =
    new CharacterField(message, HEADERSIZE + 10, 10, "H02PROGRM");
    fields[2] = fieldH02TIMSYS =
    new CharacterField(message, HEADERSIZE + 20, 12, "H02TIMSYS");
    fields[3] = fieldH02SCRCOD =
    new CharacterField(message, HEADERSIZE + 32, 2, "H02SCRCOD");
    fields[4] = fieldH02OPECOD =
    new CharacterField(message, HEADERSIZE + 34, 4, "H02OPECOD");
    fields[5] = fieldH02FLGMAS =
    new CharacterField(message, HEADERSIZE + 38, 1, "H02FLGMAS");
    fields[6] = fieldH02FLGWK1 =
    new CharacterField(message, HEADERSIZE + 39, 1, "H02FLGWK1");
    fields[7] = fieldH02FLGWK2 =
    new CharacterField(message, HEADERSIZE + 40, 1, "H02FLGWK2");
    fields[8] = fieldH02FLGWK3 =
    new CharacterField(message, HEADERSIZE + 41, 1, "H02FLGWK3");
    fields[9] = fieldE01CNTLAN =
    new CharacterField(message, HEADERSIZE + 42, 1, "E01CNTLAN");
    fields[10] = fieldE02DPVNPR =
    new DecimalField(message, HEADERSIZE + 43, 13, 0, "E02DPVNPR");
    fields[11] = fieldE02DPVM00 =
    new CharacterField(message, HEADERSIZE + 56, 2, "E02DPVM00");
    fields[12] = fieldE02DPVM01 =
    new CharacterField(message, HEADERSIZE + 58, 2, "E02DPVM01");
    fields[13] = fieldE02DPVM02 =
    new CharacterField(message, HEADERSIZE + 60, 2, "E02DPVM02");
    fields[14] = fieldE02DPVM03 =
    new CharacterField(message, HEADERSIZE + 62, 2, "E02DPVM03");
    fields[15] = fieldE02DPVM04 =
    new CharacterField(message, HEADERSIZE + 64, 2, "E02DPVM04");
    fields[16] = fieldE02DPVM05 =
    new CharacterField(message, HEADERSIZE + 66, 2, "E02DPVM05");
    fields[17] = fieldE02DPVM06 =
    new CharacterField(message, HEADERSIZE + 68, 2, "E02DPVM06");
    fields[18] = fieldE02DPVM07 =
    new CharacterField(message, HEADERSIZE + 70, 2, "E02DPVM07");
    fields[19] = fieldE02DPVM08 =
    new CharacterField(message, HEADERSIZE + 72, 2, "E02DPVM08");
    fields[20] = fieldE02DPVM09 =
    new CharacterField(message, HEADERSIZE + 74, 2, "E02DPVM09");
    fields[21] = fieldE02DPVM10 =
    new CharacterField(message, HEADERSIZE + 76, 2, "E02DPVM10");
    fields[22] = fieldE02DPVM98 =
    new CharacterField(message, HEADERSIZE + 78, 2, "E02DPVM98");
    fields[23] = fieldE02DPVM99 =
    new CharacterField(message, HEADERSIZE + 80, 2, "E02DPVM99");
    fields[24] = fieldE02DPVC00 =
    new CharacterField(message, HEADERSIZE + 82, 700, "E02DPVC00");
    fields[25] = fieldE02DPVC01 =
    new CharacterField(message, HEADERSIZE + 782, 700, "E02DPVC01");
    fields[26] = fieldE02DPVC02 =
    new CharacterField(message, HEADERSIZE + 1482, 700, "E02DPVC02");
    fields[27] = fieldE02DPVC03 =
    new CharacterField(message, HEADERSIZE + 2182, 700, "E02DPVC03");
    fields[28] = fieldE02DPVC04 =
    new CharacterField(message, HEADERSIZE + 2882, 700, "E02DPVC04");
    fields[29] = fieldE02DPVC05 =
    new CharacterField(message, HEADERSIZE + 3582, 700, "E02DPVC05");
    fields[30] = fieldE02DPVC06 =
    new CharacterField(message, HEADERSIZE + 4282, 700, "E02DPVC06");
    fields[31] = fieldE02DPVC07 =
    new CharacterField(message, HEADERSIZE + 4982, 700, "E02DPVC07");
    fields[32] = fieldE02DPVC08 =
    new CharacterField(message, HEADERSIZE + 5682, 700, "E02DPVC08");
    fields[33] = fieldE02DPVC09 =
    new CharacterField(message, HEADERSIZE + 6382, 700, "E02DPVC09");
    fields[34] = fieldE02DPVC10 =
    new CharacterField(message, HEADERSIZE + 7082, 700, "E02DPVC10");
    fields[35] = fieldE02DPVC98 =
    new CharacterField(message, HEADERSIZE + 7782, 700, "E02DPVC98");
    fields[36] = fieldE02DPVC99 =
    new CharacterField(message, HEADERSIZE + 8482, 700, "E02DPVC99");
    fields[37] = fieldE02DPVUSR =
    new CharacterField(message, HEADERSIZE + 9182, 10, "E02DPVUSR");
    fields[38] = fieldE02OPECDE =
    new CharacterField(message, HEADERSIZE + 9192, 1, "E02OPECDE");

    synchronized (tlookup)
    {
      if (tlookup.isEmpty())
      {
        for (int i = 0; i < tnames.length; i++)
          tlookup.put(tnames[i], new Integer(i));
      }
    }

    taglookup = tlookup;
  }

  /**
  * Set field H02USERID using a String value.
  */
  public void setH02USERID(String newvalue)
  {
    fieldH02USERID.setString(newvalue);
  }

  /**
  * Get value of field H02USERID as a String.
  */
  public String getH02USERID()
  {
    return fieldH02USERID.getString();
  }

  /**
  * Set field H02PROGRM using a String value.
  */
  public void setH02PROGRM(String newvalue)
  {
    fieldH02PROGRM.setString(newvalue);
  }

  /**
  * Get value of field H02PROGRM as a String.
  */
  public String getH02PROGRM()
  {
    return fieldH02PROGRM.getString();
  }

  /**
  * Set field H02TIMSYS using a String value.
  */
  public void setH02TIMSYS(String newvalue)
  {
    fieldH02TIMSYS.setString(newvalue);
  }

  /**
  * Get value of field H02TIMSYS as a String.
  */
  public String getH02TIMSYS()
  {
    return fieldH02TIMSYS.getString();
  }

  /**
  * Set field H02SCRCOD using a String value.
  */
  public void setH02SCRCOD(String newvalue)
  {
    fieldH02SCRCOD.setString(newvalue);
  }

  /**
  * Get value of field H02SCRCOD as a String.
  */
  public String getH02SCRCOD()
  {
    return fieldH02SCRCOD.getString();
  }

  /**
  * Set field H02OPECOD using a String value.
  */
  public void setH02OPECOD(String newvalue)
  {
    fieldH02OPECOD.setString(newvalue);
  }

  /**
  * Get value of field H02OPECOD as a String.
  */
  public String getH02OPECOD()
  {
    return fieldH02OPECOD.getString();
  }

  /**
  * Set field H02FLGMAS using a String value.
  */
  public void setH02FLGMAS(String newvalue)
  {
    fieldH02FLGMAS.setString(newvalue);
  }

  /**
  * Get value of field H02FLGMAS as a String.
  */
  public String getH02FLGMAS()
  {
    return fieldH02FLGMAS.getString();
  }

  /**
  * Set field H02FLGWK1 using a String value.
  */
  public void setH02FLGWK1(String newvalue)
  {
    fieldH02FLGWK1.setString(newvalue);
  }

  /**
  * Get value of field H02FLGWK1 as a String.
  */
  public String getH02FLGWK1()
  {
    return fieldH02FLGWK1.getString();
  }

  /**
  * Set field H02FLGWK2 using a String value.
  */
  public void setH02FLGWK2(String newvalue)
  {
    fieldH02FLGWK2.setString(newvalue);
  }

  /**
  * Get value of field H02FLGWK2 as a String.
  */
  public String getH02FLGWK2()
  {
    return fieldH02FLGWK2.getString();
  }

  /**
  * Set field H02FLGWK3 using a String value.
  */
  public void setH02FLGWK3(String newvalue)
  {
    fieldH02FLGWK3.setString(newvalue);
  }

  /**
  * Get value of field H02FLGWK3 as a String.
  */
  public String getH02FLGWK3()
  {
    return fieldH02FLGWK3.getString();
  }

  /**
  * Set field E01CNTLAN using a String value.
  */
  public void setE01CNTLAN(String newvalue)
  {
    fieldE01CNTLAN.setString(newvalue);
  }

  /**
  * Get value of field E01CNTLAN as a String.
  */
  public String getE01CNTLAN()
  {
    return fieldE01CNTLAN.getString();
  }

  /**
  * Set field E02DPVNPR using a String value.
  */
  public void setE02DPVNPR(String newvalue)
  {
    fieldE02DPVNPR.setString(newvalue);
  }

  /**
  * Get value of field E02DPVNPR as a String.
  */
  public String getE02DPVNPR()
  {
    return fieldE02DPVNPR.getString();
  }

  /**
  * Set numeric field E02DPVNPR using a BigDecimal value.
  */
  public void setE02DPVNPR(BigDecimal newvalue)
  {
    fieldE02DPVNPR.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E02DPVNPR as a BigDecimal.
  */
  public BigDecimal getBigDecimalE02DPVNPR()
  {
    return fieldE02DPVNPR.getBigDecimal();
  }

  /**
  * Set field E02DPVM00 using a String value.
  */
  public void setE02DPVM00(String newvalue)
  {
    fieldE02DPVM00.setString(newvalue);
  }

  /**
  * Get value of field E02DPVM00 as a String.
  */
  public String getE02DPVM00()
  {
    return fieldE02DPVM00.getString();
  }

  /**
  * Set field E02DPVM01 using a String value.
  */
  public void setE02DPVM01(String newvalue)
  {
    fieldE02DPVM01.setString(newvalue);
  }

  /**
  * Get value of field E02DPVM01 as a String.
  */
  public String getE02DPVM01()
  {
    return fieldE02DPVM01.getString();
  }

  /**
  * Set field E02DPVM02 using a String value.
  */
  public void setE02DPVM02(String newvalue)
  {
    fieldE02DPVM02.setString(newvalue);
  }

  /**
  * Get value of field E02DPVM02 as a String.
  */
  public String getE02DPVM02()
  {
    return fieldE02DPVM02.getString();
  }

  /**
  * Set field E02DPVM03 using a String value.
  */
  public void setE02DPVM03(String newvalue)
  {
    fieldE02DPVM03.setString(newvalue);
  }

  /**
  * Get value of field E02DPVM03 as a String.
  */
  public String getE02DPVM03()
  {
    return fieldE02DPVM03.getString();
  }

  /**
  * Set field E02DPVM04 using a String value.
  */
  public void setE02DPVM04(String newvalue)
  {
    fieldE02DPVM04.setString(newvalue);
  }

  /**
  * Get value of field E02DPVM04 as a String.
  */
  public String getE02DPVM04()
  {
    return fieldE02DPVM04.getString();
  }

  /**
  * Set field E02DPVM05 using a String value.
  */
  public void setE02DPVM05(String newvalue)
  {
    fieldE02DPVM05.setString(newvalue);
  }

  /**
  * Get value of field E02DPVM05 as a String.
  */
  public String getE02DPVM05()
  {
    return fieldE02DPVM05.getString();
  }

  /**
  * Set field E02DPVM06 using a String value.
  */
  public void setE02DPVM06(String newvalue)
  {
    fieldE02DPVM06.setString(newvalue);
  }

  /**
  * Get value of field E02DPVM06 as a String.
  */
  public String getE02DPVM06()
  {
    return fieldE02DPVM06.getString();
  }

  /**
  * Set field E02DPVM07 using a String value.
  */
  public void setE02DPVM07(String newvalue)
  {
    fieldE02DPVM07.setString(newvalue);
  }

  /**
  * Get value of field E02DPVM07 as a String.
  */
  public String getE02DPVM07()
  {
    return fieldE02DPVM07.getString();
  }

  /**
  * Set field E02DPVM08 using a String value.
  */
  public void setE02DPVM08(String newvalue)
  {
    fieldE02DPVM08.setString(newvalue);
  }

  /**
  * Get value of field E02DPVM08 as a String.
  */
  public String getE02DPVM08()
  {
    return fieldE02DPVM08.getString();
  }

  /**
  * Set field E02DPVM09 using a String value.
  */
  public void setE02DPVM09(String newvalue)
  {
    fieldE02DPVM09.setString(newvalue);
  }

  /**
  * Get value of field E02DPVM09 as a String.
  */
  public String getE02DPVM09()
  {
    return fieldE02DPVM09.getString();
  }

  /**
  * Set field E02DPVM10 using a String value.
  */
  public void setE02DPVM10(String newvalue)
  {
    fieldE02DPVM10.setString(newvalue);
  }

  /**
  * Get value of field E02DPVM10 as a String.
  */
  public String getE02DPVM10()
  {
    return fieldE02DPVM10.getString();
  }

  /**
  * Set field E02DPVM98 using a String value.
  */
  public void setE02DPVM98(String newvalue)
  {
    fieldE02DPVM98.setString(newvalue);
  }

  /**
  * Get value of field E02DPVM98 as a String.
  */
  public String getE02DPVM98()
  {
    return fieldE02DPVM98.getString();
  }

  /**
  * Set field E02DPVM99 using a String value.
  */
  public void setE02DPVM99(String newvalue)
  {
    fieldE02DPVM99.setString(newvalue);
  }

  /**
  * Get value of field E02DPVM99 as a String.
  */
  public String getE02DPVM99()
  {
    return fieldE02DPVM99.getString();
  }

  /**
  * Set field E02DPVC00 using a String value.
  */
  public void setE02DPVC00(String newvalue)
  {
    fieldE02DPVC00.setString(newvalue);
  }

  /**
  * Get value of field E02DPVC00 as a String.
  */
  public String getE02DPVC00()
  {
    return fieldE02DPVC00.getString();
  }

  /**
  * Set field E02DPVC01 using a String value.
  */
  public void setE02DPVC01(String newvalue)
  {
    fieldE02DPVC01.setString(newvalue);
  }

  /**
  * Get value of field E02DPVC01 as a String.
  */
  public String getE02DPVC01()
  {
    return fieldE02DPVC01.getString();
  }

  /**
  * Set field E02DPVC02 using a String value.
  */
  public void setE02DPVC02(String newvalue)
  {
    fieldE02DPVC02.setString(newvalue);
  }

  /**
  * Get value of field E02DPVC02 as a String.
  */
  public String getE02DPVC02()
  {
    return fieldE02DPVC02.getString();
  }

  /**
  * Set field E02DPVC03 using a String value.
  */
  public void setE02DPVC03(String newvalue)
  {
    fieldE02DPVC03.setString(newvalue);
  }

  /**
  * Get value of field E02DPVC03 as a String.
  */
  public String getE02DPVC03()
  {
    return fieldE02DPVC03.getString();
  }

  /**
  * Set field E02DPVC04 using a String value.
  */
  public void setE02DPVC04(String newvalue)
  {
    fieldE02DPVC04.setString(newvalue);
  }

  /**
  * Get value of field E02DPVC04 as a String.
  */
  public String getE02DPVC04()
  {
    return fieldE02DPVC04.getString();
  }

  /**
  * Set field E02DPVC05 using a String value.
  */
  public void setE02DPVC05(String newvalue)
  {
    fieldE02DPVC05.setString(newvalue);
  }

  /**
  * Get value of field E02DPVC05 as a String.
  */
  public String getE02DPVC05()
  {
    return fieldE02DPVC05.getString();
  }

  /**
  * Set field E02DPVC06 using a String value.
  */
  public void setE02DPVC06(String newvalue)
  {
    fieldE02DPVC06.setString(newvalue);
  }

  /**
  * Get value of field E02DPVC06 as a String.
  */
  public String getE02DPVC06()
  {
    return fieldE02DPVC06.getString();
  }

  /**
  * Set field E02DPVC07 using a String value.
  */
  public void setE02DPVC07(String newvalue)
  {
    fieldE02DPVC07.setString(newvalue);
  }

  /**
  * Get value of field E02DPVC07 as a String.
  */
  public String getE02DPVC07()
  {
    return fieldE02DPVC07.getString();
  }

  /**
  * Set field E02DPVC08 using a String value.
  */
  public void setE02DPVC08(String newvalue)
  {
    fieldE02DPVC08.setString(newvalue);
  }

  /**
  * Get value of field E02DPVC08 as a String.
  */
  public String getE02DPVC08()
  {
    return fieldE02DPVC08.getString();
  }

  /**
  * Set field E02DPVC09 using a String value.
  */
  public void setE02DPVC09(String newvalue)
  {
    fieldE02DPVC09.setString(newvalue);
  }

  /**
  * Get value of field E02DPVC09 as a String.
  */
  public String getE02DPVC09()
  {
    return fieldE02DPVC09.getString();
  }

  /**
  * Set field E02DPVC10 using a String value.
  */
  public void setE02DPVC10(String newvalue)
  {
    fieldE02DPVC10.setString(newvalue);
  }

  /**
  * Get value of field E02DPVC10 as a String.
  */
  public String getE02DPVC10()
  {
    return fieldE02DPVC10.getString();
  }

  /**
  * Set field E02DPVC98 using a String value.
  */
  public void setE02DPVC98(String newvalue)
  {
    fieldE02DPVC98.setString(newvalue);
  }

  /**
  * Get value of field E02DPVC98 as a String.
  */
  public String getE02DPVC98()
  {
    return fieldE02DPVC98.getString();
  }

  /**
  * Set field E02DPVC99 using a String value.
  */
  public void setE02DPVC99(String newvalue)
  {
    fieldE02DPVC99.setString(newvalue);
  }

  /**
  * Get value of field E02DPVC99 as a String.
  */
  public String getE02DPVC99()
  {
    return fieldE02DPVC99.getString();
  }

  /**
  * Set field E02DPVUSR using a String value.
  */
  public void setE02DPVUSR(String newvalue)
  {
    fieldE02DPVUSR.setString(newvalue);
  }

  /**
  * Get value of field E02DPVUSR as a String.
  */
  public String getE02DPVUSR()
  {
    return fieldE02DPVUSR.getString();
  }

  /**
  * Set field E02OPECDE using a String value.
  */
  public void setE02OPECDE(String newvalue)
  {
    fieldE02OPECDE.setString(newvalue);
  }

  /**
  * Get value of field E02OPECDE as a String.
  */
  public String getE02OPECDE()
  {
    return fieldE02OPECDE.getString();
  }

}
