package datapro.eibs.beans;

import datapro.eibs.sockets.*;
import java.io.*;
import java.math.*;

import java.util.*;

/**
* Class generated by AS/400 CRTCLASS command from EGC049005 physical file definition.
* 
* File level identifier is 1030121191925.
* Record format level identifier is 53548B71BDE3D.
*/

public class EGC049005Message extends MessageRecord
{
  final static String fldnames[] = {
                                     "H05USERID",
                                     "H05PROGRM",
                                     "H05TIMSYS",
                                     "H05SCRCOD",
                                     "H05OPECOD",
                                     "H05FLGMAS",
                                     "H05FLGWK1",
                                     "H05FLGWK2",
                                     "H05FLGWK3",
                                     "E05CUSCUN",
                                     "E05CUSNA1",
                                     "E05CUSSTS",
                                     "E05CLSACC",
                                     "E05ACCNUM",
                                     "E05BNKNUM",
                                     "E05BRNNUM",
                                     "E05CCYCDE",
                                     "E05ACCTYP",
                                     "E05TYPDSC",
                                     "E05PROCDE",
                                     "E05PRODSC",
                                     "E05BSEPRI",
                                     "E05BSEINT",
                                     "E05BSEOTH",
                                     "E05BSETOT",
                                     "E05ACCSTS",
                                     "E05OPEDT1",
                                     "E05OPEDT2",
                                     "E05OPEDT3",
                                     "E05INDOPE"
                                   };
  final static String tnames[] = {
                                   "H05USERID",
                                   "H05PROGRM",
                                   "H05TIMSYS",
                                   "H05SCRCOD",
                                   "H05OPECOD",
                                   "H05FLGMAS",
                                   "H05FLGWK1",
                                   "H05FLGWK2",
                                   "H05FLGWK3",
                                   "E05CUSCUN",
                                   "E05CUSNA1",
                                   "E05CUSSTS",
                                   "E05CLSACC",
                                   "E05ACCNUM",
                                   "E05BNKNUM",
                                   "E05BRNNUM",
                                   "E05CCYCDE",
                                   "E05ACCTYP",
                                   "E05TYPDSC",
                                   "E05PROCDE",
                                   "E05PRODSC",
                                   "E05BSEPRI",
                                   "E05BSEINT",
                                   "E05BSEOTH",
                                   "E05BSETOT",
                                   "E05ACCSTS",
                                   "E05OPEDT1",
                                   "E05OPEDT2",
                                   "E05OPEDT3",
                                   "E05INDOPE"
                                 };
  final static String fid = "1030121191925";
  final static String rid = "53548B71BDE3D";
  final static String fmtname = "EGC049005";
  final int FIELDCOUNT = 30;
  private static Hashtable tlookup = new Hashtable();
  private CharacterField fieldH05USERID = null;
  private CharacterField fieldH05PROGRM = null;
  private CharacterField fieldH05TIMSYS = null;
  private CharacterField fieldH05SCRCOD = null;
  private CharacterField fieldH05OPECOD = null;
  private CharacterField fieldH05FLGMAS = null;
  private CharacterField fieldH05FLGWK1 = null;
  private CharacterField fieldH05FLGWK2 = null;
  private CharacterField fieldH05FLGWK3 = null;
  private DecimalField fieldE05CUSCUN = null;
  private CharacterField fieldE05CUSNA1 = null;
  private CharacterField fieldE05CUSSTS = null;
  private DecimalField fieldE05CLSACC = null;
  private DecimalField fieldE05ACCNUM = null;
  private CharacterField fieldE05BNKNUM = null;
  private DecimalField fieldE05BRNNUM = null;
  private CharacterField fieldE05CCYCDE = null;
  private CharacterField fieldE05ACCTYP = null;
  private CharacterField fieldE05TYPDSC = null;
  private CharacterField fieldE05PROCDE = null;
  private CharacterField fieldE05PRODSC = null;
  private DecimalField fieldE05BSEPRI = null;
  private DecimalField fieldE05BSEINT = null;
  private DecimalField fieldE05BSEOTH = null;
  private DecimalField fieldE05BSETOT = null;
  private CharacterField fieldE05ACCSTS = null;
  private DecimalField fieldE05OPEDT1 = null;
  private DecimalField fieldE05OPEDT2 = null;
  private DecimalField fieldE05OPEDT3 = null;
  private CharacterField fieldE05INDOPE = null;

  /**
  * Constructor for EGC049005Message.
  */
  public EGC049005Message()
  {
    createFields();
    initialize();
  }

  /**
  * Create fields for this message.
  * This method implements the abstract method in the MessageRecord superclass.
  */
  protected void createFields()
  {
    recordsize = 313;
    fileid = fid;
    recordid = rid;
    message = new byte[getByteLength()];
    formatname = fmtname;
    fieldnames = fldnames;
    tagnames = tnames;
    fields = new MessageField[FIELDCOUNT];

    fields[0] = fieldH05USERID =
    new CharacterField(message, HEADERSIZE + 0, 10, "H05USERID");
    fields[1] = fieldH05PROGRM =
    new CharacterField(message, HEADERSIZE + 10, 10, "H05PROGRM");
    fields[2] = fieldH05TIMSYS =
    new CharacterField(message, HEADERSIZE + 20, 12, "H05TIMSYS");
    fields[3] = fieldH05SCRCOD =
    new CharacterField(message, HEADERSIZE + 32, 2, "H05SCRCOD");
    fields[4] = fieldH05OPECOD =
    new CharacterField(message, HEADERSIZE + 34, 4, "H05OPECOD");
    fields[5] = fieldH05FLGMAS =
    new CharacterField(message, HEADERSIZE + 38, 1, "H05FLGMAS");
    fields[6] = fieldH05FLGWK1 =
    new CharacterField(message, HEADERSIZE + 39, 1, "H05FLGWK1");
    fields[7] = fieldH05FLGWK2 =
    new CharacterField(message, HEADERSIZE + 40, 1, "H05FLGWK2");
    fields[8] = fieldH05FLGWK3 =
    new CharacterField(message, HEADERSIZE + 41, 1, "H05FLGWK3");
    fields[9] = fieldE05CUSCUN =
    new DecimalField(message, HEADERSIZE + 42, 10, 0, "E05CUSCUN");
    fields[10] = fieldE05CUSNA1 =
    new CharacterField(message, HEADERSIZE + 52, 45, "E05CUSNA1");
    fields[11] = fieldE05CUSSTS =
    new CharacterField(message, HEADERSIZE + 97, 20, "E05CUSSTS");
    fields[12] = fieldE05CLSACC =
    new DecimalField(message, HEADERSIZE + 117, 3, 0, "E05CLSACC");
    fields[13] = fieldE05ACCNUM =
    new DecimalField(message, HEADERSIZE + 120, 13, 0, "E05ACCNUM");
    fields[14] = fieldE05BNKNUM =
    new CharacterField(message, HEADERSIZE + 133, 2, "E05BNKNUM");
    fields[15] = fieldE05BRNNUM =
    new DecimalField(message, HEADERSIZE + 135, 4, 0, "E05BRNNUM");
    fields[16] = fieldE05CCYCDE =
    new CharacterField(message, HEADERSIZE + 139, 3, "E05CCYCDE");
    fields[17] = fieldE05ACCTYP =
    new CharacterField(message, HEADERSIZE + 142, 4, "E05ACCTYP");
    fields[18] = fieldE05TYPDSC =
    new CharacterField(message, HEADERSIZE + 146, 35, "E05TYPDSC");
    fields[19] = fieldE05PROCDE =
    new CharacterField(message, HEADERSIZE + 181, 4, "E05PROCDE");
    fields[20] = fieldE05PRODSC =
    new CharacterField(message, HEADERSIZE + 185, 35, "E05PRODSC");
    fields[21] = fieldE05BSEPRI =
    new DecimalField(message, HEADERSIZE + 220, 17, 2, "E05BSEPRI");
    fields[22] = fieldE05BSEINT =
    new DecimalField(message, HEADERSIZE + 237, 17, 2, "E05BSEINT");
    fields[23] = fieldE05BSEOTH =
    new DecimalField(message, HEADERSIZE + 254, 17, 2, "E05BSEOTH");
    fields[24] = fieldE05BSETOT =
    new DecimalField(message, HEADERSIZE + 271, 17, 2, "E05BSETOT");
    fields[25] = fieldE05ACCSTS =
    new CharacterField(message, HEADERSIZE + 288, 15, "E05ACCSTS");
    fields[26] = fieldE05OPEDT1 =
    new DecimalField(message, HEADERSIZE + 303, 3, 0, "E05OPEDT1");
    fields[27] = fieldE05OPEDT2 =
    new DecimalField(message, HEADERSIZE + 306, 3, 0, "E05OPEDT2");
    fields[28] = fieldE05OPEDT3 =
    new DecimalField(message, HEADERSIZE + 309, 3, 0, "E05OPEDT3");
    fields[29] = fieldE05INDOPE =
    new CharacterField(message, HEADERSIZE + 312, 1, "E05INDOPE");

    synchronized (tlookup)
    {
      if (tlookup.isEmpty())
      {
        for (int i = 0; i < tnames.length; i++)
          tlookup.put(tnames[i], new Integer(i));
      }
    }

    taglookup = tlookup;
  }

  /**
  * Set field H05USERID using a String value.
  */
  public void setH05USERID(String newvalue)
  {
    fieldH05USERID.setString(newvalue);
  }

  /**
  * Get value of field H05USERID as a String.
  */
  public String getH05USERID()
  {
    return fieldH05USERID.getString();
  }

  /**
  * Set field H05PROGRM using a String value.
  */
  public void setH05PROGRM(String newvalue)
  {
    fieldH05PROGRM.setString(newvalue);
  }

  /**
  * Get value of field H05PROGRM as a String.
  */
  public String getH05PROGRM()
  {
    return fieldH05PROGRM.getString();
  }

  /**
  * Set field H05TIMSYS using a String value.
  */
  public void setH05TIMSYS(String newvalue)
  {
    fieldH05TIMSYS.setString(newvalue);
  }

  /**
  * Get value of field H05TIMSYS as a String.
  */
  public String getH05TIMSYS()
  {
    return fieldH05TIMSYS.getString();
  }

  /**
  * Set field H05SCRCOD using a String value.
  */
  public void setH05SCRCOD(String newvalue)
  {
    fieldH05SCRCOD.setString(newvalue);
  }

  /**
  * Get value of field H05SCRCOD as a String.
  */
  public String getH05SCRCOD()
  {
    return fieldH05SCRCOD.getString();
  }

  /**
  * Set field H05OPECOD using a String value.
  */
  public void setH05OPECOD(String newvalue)
  {
    fieldH05OPECOD.setString(newvalue);
  }

  /**
  * Get value of field H05OPECOD as a String.
  */
  public String getH05OPECOD()
  {
    return fieldH05OPECOD.getString();
  }

  /**
  * Set field H05FLGMAS using a String value.
  */
  public void setH05FLGMAS(String newvalue)
  {
    fieldH05FLGMAS.setString(newvalue);
  }

  /**
  * Get value of field H05FLGMAS as a String.
  */
  public String getH05FLGMAS()
  {
    return fieldH05FLGMAS.getString();
  }

  /**
  * Set field H05FLGWK1 using a String value.
  */
  public void setH05FLGWK1(String newvalue)
  {
    fieldH05FLGWK1.setString(newvalue);
  }

  /**
  * Get value of field H05FLGWK1 as a String.
  */
  public String getH05FLGWK1()
  {
    return fieldH05FLGWK1.getString();
  }

  /**
  * Set field H05FLGWK2 using a String value.
  */
  public void setH05FLGWK2(String newvalue)
  {
    fieldH05FLGWK2.setString(newvalue);
  }

  /**
  * Get value of field H05FLGWK2 as a String.
  */
  public String getH05FLGWK2()
  {
    return fieldH05FLGWK2.getString();
  }

  /**
  * Set field H05FLGWK3 using a String value.
  */
  public void setH05FLGWK3(String newvalue)
  {
    fieldH05FLGWK3.setString(newvalue);
  }

  /**
  * Get value of field H05FLGWK3 as a String.
  */
  public String getH05FLGWK3()
  {
    return fieldH05FLGWK3.getString();
  }

  /**
  * Set field E05CUSCUN using a String value.
  */
  public void setE05CUSCUN(String newvalue)
  {
    fieldE05CUSCUN.setString(newvalue);
  }

  /**
  * Get value of field E05CUSCUN as a String.
  */
  public String getE05CUSCUN()
  {
    return fieldE05CUSCUN.getString();
  }

  /**
  * Set numeric field E05CUSCUN using a BigDecimal value.
  */
  public void setE05CUSCUN(BigDecimal newvalue)
  {
    fieldE05CUSCUN.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05CUSCUN as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05CUSCUN()
  {
    return fieldE05CUSCUN.getBigDecimal();
  }

  /**
  * Set field E05CUSNA1 using a String value.
  */
  public void setE05CUSNA1(String newvalue)
  {
    fieldE05CUSNA1.setString(newvalue);
  }

  /**
  * Get value of field E05CUSNA1 as a String.
  */
  public String getE05CUSNA1()
  {
    return fieldE05CUSNA1.getString();
  }

  /**
  * Set field E05CUSSTS using a String value.
  */
  public void setE05CUSSTS(String newvalue)
  {
    fieldE05CUSSTS.setString(newvalue);
  }

  /**
  * Get value of field E05CUSSTS as a String.
  */
  public String getE05CUSSTS()
  {
    return fieldE05CUSSTS.getString();
  }

  /**
  * Set field E05CLSACC using a String value.
  */
  public void setE05CLSACC(String newvalue)
  {
    fieldE05CLSACC.setString(newvalue);
  }

  /**
  * Get value of field E05CLSACC as a String.
  */
  public String getE05CLSACC()
  {
    return fieldE05CLSACC.getString();
  }

  /**
  * Set numeric field E05CLSACC using a BigDecimal value.
  */
  public void setE05CLSACC(BigDecimal newvalue)
  {
    fieldE05CLSACC.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05CLSACC as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05CLSACC()
  {
    return fieldE05CLSACC.getBigDecimal();
  }

  /**
  * Set field E05ACCNUM using a String value.
  */
  public void setE05ACCNUM(String newvalue)
  {
    fieldE05ACCNUM.setString(newvalue);
  }

  /**
  * Get value of field E05ACCNUM as a String.
  */
  public String getE05ACCNUM()
  {
    return fieldE05ACCNUM.getString();
  }

  /**
  * Set numeric field E05ACCNUM using a BigDecimal value.
  */
  public void setE05ACCNUM(BigDecimal newvalue)
  {
    fieldE05ACCNUM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05ACCNUM as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05ACCNUM()
  {
    return fieldE05ACCNUM.getBigDecimal();
  }

  /**
  * Set field E05BNKNUM using a String value.
  */
  public void setE05BNKNUM(String newvalue)
  {
    fieldE05BNKNUM.setString(newvalue);
  }

  /**
  * Get value of field E05BNKNUM as a String.
  */
  public String getE05BNKNUM()
  {
    return fieldE05BNKNUM.getString();
  }

  /**
  * Set field E05BRNNUM using a String value.
  */
  public void setE05BRNNUM(String newvalue)
  {
    fieldE05BRNNUM.setString(newvalue);
  }

  /**
  * Get value of field E05BRNNUM as a String.
  */
  public String getE05BRNNUM()
  {
    return fieldE05BRNNUM.getString();
  }

  /**
  * Set numeric field E05BRNNUM using a BigDecimal value.
  */
  public void setE05BRNNUM(BigDecimal newvalue)
  {
    fieldE05BRNNUM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05BRNNUM as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05BRNNUM()
  {
    return fieldE05BRNNUM.getBigDecimal();
  }

  /**
  * Set field E05CCYCDE using a String value.
  */
  public void setE05CCYCDE(String newvalue)
  {
    fieldE05CCYCDE.setString(newvalue);
  }

  /**
  * Get value of field E05CCYCDE as a String.
  */
  public String getE05CCYCDE()
  {
    return fieldE05CCYCDE.getString();
  }

  /**
  * Set field E05ACCTYP using a String value.
  */
  public void setE05ACCTYP(String newvalue)
  {
    fieldE05ACCTYP.setString(newvalue);
  }

  /**
  * Get value of field E05ACCTYP as a String.
  */
  public String getE05ACCTYP()
  {
    return fieldE05ACCTYP.getString();
  }

  /**
  * Set field E05TYPDSC using a String value.
  */
  public void setE05TYPDSC(String newvalue)
  {
    fieldE05TYPDSC.setString(newvalue);
  }

  /**
  * Get value of field E05TYPDSC as a String.
  */
  public String getE05TYPDSC()
  {
    return fieldE05TYPDSC.getString();
  }

  /**
  * Set field E05PROCDE using a String value.
  */
  public void setE05PROCDE(String newvalue)
  {
    fieldE05PROCDE.setString(newvalue);
  }

  /**
  * Get value of field E05PROCDE as a String.
  */
  public String getE05PROCDE()
  {
    return fieldE05PROCDE.getString();
  }

  /**
  * Set field E05PRODSC using a String value.
  */
  public void setE05PRODSC(String newvalue)
  {
    fieldE05PRODSC.setString(newvalue);
  }

  /**
  * Get value of field E05PRODSC as a String.
  */
  public String getE05PRODSC()
  {
    return fieldE05PRODSC.getString();
  }

  /**
  * Set field E05BSEPRI using a String value.
  */
  public void setE05BSEPRI(String newvalue)
  {
    fieldE05BSEPRI.setString(newvalue);
  }

  /**
  * Get value of field E05BSEPRI as a String.
  */
  public String getE05BSEPRI()
  {
    return fieldE05BSEPRI.getString();
  }

  /**
  * Set numeric field E05BSEPRI using a BigDecimal value.
  */
  public void setE05BSEPRI(BigDecimal newvalue)
  {
    fieldE05BSEPRI.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05BSEPRI as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05BSEPRI()
  {
    return fieldE05BSEPRI.getBigDecimal();
  }

  /**
  * Set field E05BSEINT using a String value.
  */
  public void setE05BSEINT(String newvalue)
  {
    fieldE05BSEINT.setString(newvalue);
  }

  /**
  * Get value of field E05BSEINT as a String.
  */
  public String getE05BSEINT()
  {
    return fieldE05BSEINT.getString();
  }

  /**
  * Set numeric field E05BSEINT using a BigDecimal value.
  */
  public void setE05BSEINT(BigDecimal newvalue)
  {
    fieldE05BSEINT.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05BSEINT as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05BSEINT()
  {
    return fieldE05BSEINT.getBigDecimal();
  }

  /**
  * Set field E05BSEOTH using a String value.
  */
  public void setE05BSEOTH(String newvalue)
  {
    fieldE05BSEOTH.setString(newvalue);
  }

  /**
  * Get value of field E05BSEOTH as a String.
  */
  public String getE05BSEOTH()
  {
    return fieldE05BSEOTH.getString();
  }

  /**
  * Set numeric field E05BSEOTH using a BigDecimal value.
  */
  public void setE05BSEOTH(BigDecimal newvalue)
  {
    fieldE05BSEOTH.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05BSEOTH as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05BSEOTH()
  {
    return fieldE05BSEOTH.getBigDecimal();
  }

  /**
  * Set field E05BSETOT using a String value.
  */
  public void setE05BSETOT(String newvalue)
  {
    fieldE05BSETOT.setString(newvalue);
  }

  /**
  * Get value of field E05BSETOT as a String.
  */
  public String getE05BSETOT()
  {
    return fieldE05BSETOT.getString();
  }

  /**
  * Set numeric field E05BSETOT using a BigDecimal value.
  */
  public void setE05BSETOT(BigDecimal newvalue)
  {
    fieldE05BSETOT.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05BSETOT as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05BSETOT()
  {
    return fieldE05BSETOT.getBigDecimal();
  }

  /**
  * Set field E05ACCSTS using a String value.
  */
  public void setE05ACCSTS(String newvalue)
  {
    fieldE05ACCSTS.setString(newvalue);
  }

  /**
  * Get value of field E05ACCSTS as a String.
  */
  public String getE05ACCSTS()
  {
    return fieldE05ACCSTS.getString();
  }

  /**
  * Set field E05OPEDT1 using a String value.
  */
  public void setE05OPEDT1(String newvalue)
  {
    fieldE05OPEDT1.setString(newvalue);
  }

  /**
  * Get value of field E05OPEDT1 as a String.
  */
  public String getE05OPEDT1()
  {
    return fieldE05OPEDT1.getString();
  }

  /**
  * Set numeric field E05OPEDT1 using a BigDecimal value.
  */
  public void setE05OPEDT1(BigDecimal newvalue)
  {
    fieldE05OPEDT1.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05OPEDT1 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05OPEDT1()
  {
    return fieldE05OPEDT1.getBigDecimal();
  }

  /**
  * Set field E05OPEDT2 using a String value.
  */
  public void setE05OPEDT2(String newvalue)
  {
    fieldE05OPEDT2.setString(newvalue);
  }

  /**
  * Get value of field E05OPEDT2 as a String.
  */
  public String getE05OPEDT2()
  {
    return fieldE05OPEDT2.getString();
  }

  /**
  * Set numeric field E05OPEDT2 using a BigDecimal value.
  */
  public void setE05OPEDT2(BigDecimal newvalue)
  {
    fieldE05OPEDT2.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05OPEDT2 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05OPEDT2()
  {
    return fieldE05OPEDT2.getBigDecimal();
  }

  /**
  * Set field E05OPEDT3 using a String value.
  */
  public void setE05OPEDT3(String newvalue)
  {
    fieldE05OPEDT3.setString(newvalue);
  }

  /**
  * Get value of field E05OPEDT3 as a String.
  */
  public String getE05OPEDT3()
  {
    return fieldE05OPEDT3.getString();
  }

  /**
  * Set numeric field E05OPEDT3 using a BigDecimal value.
  */
  public void setE05OPEDT3(BigDecimal newvalue)
  {
    fieldE05OPEDT3.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05OPEDT3 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05OPEDT3()
  {
    return fieldE05OPEDT3.getBigDecimal();
  }

  /**
  * Set field E05INDOPE using a String value.
  */
  public void setE05INDOPE(String newvalue)
  {
    fieldE05INDOPE.setString(newvalue);
  }

  /**
  * Get value of field E05INDOPE as a String.
  */
  public String getE05INDOPE()
  {
    return fieldE05INDOPE.getString();
  }

}
