package datapro.eibs.beans;

import datapro.eibs.sockets.*;
import java.io.*;
import java.math.*;

import java.util.*;

/**
* Class generated by AS/400 CRTCLASS command from EIE021001 physical file definition.
* 
* File level identifier is 1030213182639.
* Record format level identifier is 2AF955626B94F.
*/

public class EIE021001Message extends MessageRecord
{
  final static String fldnames[] = {
                                     "H01USERID",
                                     "H01PROGRM",
                                     "H01TIMSYS",
                                     "H01SCRCOD",
                                     "H01OPECOD",
                                     "H01FLGMAS",
                                     "H01FLGWK1",
                                     "H01FLGWK2",
                                     "H01FLGWK3",
                                     "E01CPNSTS",
                                     "E01CPNIIC",
                                     "E01CPNTYP",
                                     "E01CPNPMC",
                                     "E01CPNPM1",
                                     "E01CPNPM2",
                                     "E01CPNPM3",
                                     "E01CPNPMT",
                                     "E01CPNNUM",
                                     "E01CPNAMT",
                                     "E01CPNCOM",
                                     "E01CPNPAM",
                                     "E01CPNDAM",
                                     "E01CPNTBL",
                                     "E01CPNNAR",
                                     "E01CPNDLC",
                                     "E01CPNDL1",
                                     "E01CPNDL2",
                                     "E01CPNDL3",
                                     "E01CPNDLT",
                                     "E01CPNREF",
                                     "D01ISIDSC",
                                     "D01ISIPTY",
                                     "D01ISINUM",
                                     "D01ISISER",
                                     "D01ISICUS",
                                     "D01ISISYM",
                                     "D01ISICCY",
                                     "D01ISIRTE",
                                     "D01ISIPFV",
                                     "D01ISIPFC",
                                     "D01CUSCUN",
                                     "D01CUSNME",
                                     "D01CSTCOD",
                                     "D01CSTNME",
                                     "D01STSDSC",
                                     "D01PMTDSC",
                                     "D01ORDIPT",
                                     "D01ORDIBK",
                                     "D01ORDIBR",
                                     "D01ORDICY",
                                     "D01ORDIGL",
                                     "D01ORDIAC",
                                     "D01ORDICC",
                                     "E01CPNPVI",
                                     "E01CPNCPT",
                                     "E01CPNCBK",
                                     "E01CPNCBR",
                                     "E01CPNCCY",
                                     "E01CPNCGL",
                                     "E01CPNCAC",
                                     "E01CPNCCC",
                                     "E01CPNUSC",
                                     "E01CPNUSA",
                                     "E01CPNRMK",
                                     "E01CPNACT",
                                     "E01CPNRCD",
                                     "E01CPNFL0",
                                     "E01CPNFL1",
                                     "E01CPNFL2",
                                     "E01CPNFL3",
                                     "E01CPNFL4",
                                     "E01CPNFL5",
                                     "E01CPNFL6",
                                     "E01CPNFL7",
                                     "E01CPNFL8",
                                     "E01CPNFL9"
                                   };
  final static String tnames[] = {
                                   "H01USERID",
                                   "H01PROGRM",
                                   "H01TIMSYS",
                                   "H01SCRCOD",
                                   "H01OPECOD",
                                   "H01FLGMAS",
                                   "H01FLGWK1",
                                   "H01FLGWK2",
                                   "H01FLGWK3",
                                   "E01CPNSTS",
                                   "E01CPNIIC",
                                   "E01CPNTYP",
                                   "E01CPNPMC",
                                   "E01CPNPM1",
                                   "E01CPNPM2",
                                   "E01CPNPM3",
                                   "E01CPNPMT",
                                   "E01CPNNUM",
                                   "E01CPNAMT",
                                   "E01CPNCOM",
                                   "E01CPNPAM",
                                   "E01CPNDAM",
                                   "E01CPNTBL",
                                   "E01CPNNAR",
                                   "E01CPNDLC",
                                   "E01CPNDL1",
                                   "E01CPNDL2",
                                   "E01CPNDL3",
                                   "E01CPNDLT",
                                   "E01CPNREF",
                                   "D01ISIDSC",
                                   "D01ISIPTY",
                                   "D01ISINUM",
                                   "D01ISISER",
                                   "D01ISICUS",
                                   "D01ISISYM",
                                   "D01ISICCY",
                                   "D01ISIRTE",
                                   "D01ISIPFV",
                                   "D01ISIPFC",
                                   "D01CUSCUN",
                                   "D01CUSNME",
                                   "D01CSTCOD",
                                   "D01CSTNME",
                                   "D01STSDSC",
                                   "D01PMTDSC",
                                   "D01ORDIPT",
                                   "D01ORDIBK",
                                   "D01ORDIBR",
                                   "D01ORDICY",
                                   "D01ORDIGL",
                                   "D01ORDIAC",
                                   "D01ORDICC",
                                   "E01CPNPVI",
                                   "E01CPNCPT",
                                   "E01CPNCBK",
                                   "E01CPNCBR",
                                   "E01CPNCCY",
                                   "E01CPNCGL",
                                   "E01CPNCAC",
                                   "E01CPNCCC",
                                   "E01CPNUSC",
                                   "E01CPNUSA",
                                   "E01CPNRMK",
                                   "E01CPNACT",
                                   "E01CPNRCD",
                                   "E01CPNFL0",
                                   "E01CPNFL1",
                                   "E01CPNFL2",
                                   "E01CPNFL3",
                                   "E01CPNFL4",
                                   "E01CPNFL5",
                                   "E01CPNFL6",
                                   "E01CPNFL7",
                                   "E01CPNFL8",
                                   "E01CPNFL9"
                                 };
  final static String fid = "1030213182639";
  final static String rid = "2AF955626B94F";
  final static String fmtname = "EIE021001";
  final int FIELDCOUNT = 76;
  private static Hashtable tlookup = new Hashtable();
  private CharacterField fieldH01USERID = null;
  private CharacterField fieldH01PROGRM = null;
  private CharacterField fieldH01TIMSYS = null;
  private CharacterField fieldH01SCRCOD = null;
  private CharacterField fieldH01OPECOD = null;
  private CharacterField fieldH01FLGMAS = null;
  private CharacterField fieldH01FLGWK1 = null;
  private CharacterField fieldH01FLGWK2 = null;
  private CharacterField fieldH01FLGWK3 = null;
  private CharacterField fieldE01CPNSTS = null;
  private DecimalField fieldE01CPNIIC = null;
  private CharacterField fieldE01CPNTYP = null;
  private DecimalField fieldE01CPNPMC = null;
  private DecimalField fieldE01CPNPM1 = null;
  private DecimalField fieldE01CPNPM2 = null;
  private DecimalField fieldE01CPNPM3 = null;
  private DecimalField fieldE01CPNPMT = null;
  private DecimalField fieldE01CPNNUM = null;
  private DecimalField fieldE01CPNAMT = null;
  private DecimalField fieldE01CPNCOM = null;
  private DecimalField fieldE01CPNPAM = null;
  private DecimalField fieldE01CPNDAM = null;
  private CharacterField fieldE01CPNTBL = null;
  private CharacterField fieldE01CPNNAR = null;
  private DecimalField fieldE01CPNDLC = null;
  private DecimalField fieldE01CPNDL1 = null;
  private DecimalField fieldE01CPNDL2 = null;
  private DecimalField fieldE01CPNDL3 = null;
  private DecimalField fieldE01CPNDLT = null;
  private CharacterField fieldE01CPNREF = null;
  private CharacterField fieldD01ISIDSC = null;
  private CharacterField fieldD01ISIPTY = null;
  private CharacterField fieldD01ISINUM = null;
  private CharacterField fieldD01ISISER = null;
  private CharacterField fieldD01ISICUS = null;
  private CharacterField fieldD01ISISYM = null;
  private CharacterField fieldD01ISICCY = null;
  private DecimalField fieldD01ISIRTE = null;
  private DecimalField fieldD01ISIPFV = null;
  private CharacterField fieldD01ISIPFC = null;
  private DecimalField fieldD01CUSCUN = null;
  private CharacterField fieldD01CUSNME = null;
  private CharacterField fieldD01CSTCOD = null;
  private CharacterField fieldD01CSTNME = null;
  private CharacterField fieldD01STSDSC = null;
  private CharacterField fieldD01PMTDSC = null;
  private CharacterField fieldD01ORDIPT = null;
  private CharacterField fieldD01ORDIBK = null;
  private DecimalField fieldD01ORDIBR = null;
  private CharacterField fieldD01ORDICY = null;
  private DecimalField fieldD01ORDIGL = null;
  private DecimalField fieldD01ORDIAC = null;
  private DecimalField fieldD01ORDICC = null;
  private CharacterField fieldE01CPNPVI = null;
  private CharacterField fieldE01CPNCPT = null;
  private CharacterField fieldE01CPNCBK = null;
  private DecimalField fieldE01CPNCBR = null;
  private CharacterField fieldE01CPNCCY = null;
  private DecimalField fieldE01CPNCGL = null;
  private DecimalField fieldE01CPNCAC = null;
  private DecimalField fieldE01CPNCCC = null;
  private CharacterField fieldE01CPNUSC = null;
  private CharacterField fieldE01CPNUSA = null;
  private CharacterField fieldE01CPNRMK = null;
  private CharacterField fieldE01CPNACT = null;
  private DecimalField fieldE01CPNRCD = null;
  private CharacterField fieldE01CPNFL0 = null;
  private CharacterField fieldE01CPNFL1 = null;
  private CharacterField fieldE01CPNFL2 = null;
  private CharacterField fieldE01CPNFL3 = null;
  private CharacterField fieldE01CPNFL4 = null;
  private CharacterField fieldE01CPNFL5 = null;
  private CharacterField fieldE01CPNFL6 = null;
  private DecimalField fieldE01CPNFL7 = null;
  private DecimalField fieldE01CPNFL8 = null;
  private DecimalField fieldE01CPNFL9 = null;

  /**
  * Constructor for EIE021001Message.
  */
  public EIE021001Message()
  {
    createFields();
    initialize();
  }

  /**
  * Create fields for this message.
  * This method implements the abstract method in the MessageRecord superclass.
  */
  protected void createFields()
  {
    recordsize = 691;
    fileid = fid;
    recordid = rid;
    message = new byte[getByteLength()];
    formatname = fmtname;
    fieldnames = fldnames;
    tagnames = tnames;
    fields = new MessageField[FIELDCOUNT];

    fields[0] = fieldH01USERID =
    new CharacterField(message, HEADERSIZE + 0, 10, "H01USERID");
    fields[1] = fieldH01PROGRM =
    new CharacterField(message, HEADERSIZE + 10, 10, "H01PROGRM");
    fields[2] = fieldH01TIMSYS =
    new CharacterField(message, HEADERSIZE + 20, 12, "H01TIMSYS");
    fields[3] = fieldH01SCRCOD =
    new CharacterField(message, HEADERSIZE + 32, 2, "H01SCRCOD");
    fields[4] = fieldH01OPECOD =
    new CharacterField(message, HEADERSIZE + 34, 4, "H01OPECOD");
    fields[5] = fieldH01FLGMAS =
    new CharacterField(message, HEADERSIZE + 38, 1, "H01FLGMAS");
    fields[6] = fieldH01FLGWK1 =
    new CharacterField(message, HEADERSIZE + 39, 1, "H01FLGWK1");
    fields[7] = fieldH01FLGWK2 =
    new CharacterField(message, HEADERSIZE + 40, 1, "H01FLGWK2");
    fields[8] = fieldH01FLGWK3 =
    new CharacterField(message, HEADERSIZE + 41, 1, "H01FLGWK3");
    fields[9] = fieldE01CPNSTS =
    new CharacterField(message, HEADERSIZE + 42, 1, "E01CPNSTS");
    fields[10] = fieldE01CPNIIC =
    new DecimalField(message, HEADERSIZE + 43, 10, 0, "E01CPNIIC");
    fields[11] = fieldE01CPNTYP =
    new CharacterField(message, HEADERSIZE + 53, 1, "E01CPNTYP");
    fields[12] = fieldE01CPNPMC =
    new DecimalField(message, HEADERSIZE + 54, 2, 0, "E01CPNPMC");
    fields[13] = fieldE01CPNPM1 =
    new DecimalField(message, HEADERSIZE + 56, 3, 0, "E01CPNPM1");
    fields[14] = fieldE01CPNPM2 =
    new DecimalField(message, HEADERSIZE + 59, 3, 0, "E01CPNPM2");
    fields[15] = fieldE01CPNPM3 =
    new DecimalField(message, HEADERSIZE + 62, 3, 0, "E01CPNPM3");
    fields[16] = fieldE01CPNPMT =
    new DecimalField(message, HEADERSIZE + 65, 7, 0, "E01CPNPMT");
    fields[17] = fieldE01CPNNUM =
    new DecimalField(message, HEADERSIZE + 72, 10, 0, "E01CPNNUM");
    fields[18] = fieldE01CPNAMT =
    new DecimalField(message, HEADERSIZE + 82, 15, 2, "E01CPNAMT");
    fields[19] = fieldE01CPNCOM =
    new DecimalField(message, HEADERSIZE + 97, 15, 2, "E01CPNCOM");
    fields[20] = fieldE01CPNPAM =
    new DecimalField(message, HEADERSIZE + 112, 15, 2, "E01CPNPAM");
    fields[21] = fieldE01CPNDAM =
    new DecimalField(message, HEADERSIZE + 127, 15, 2, "E01CPNDAM");
    fields[22] = fieldE01CPNTBL =
    new CharacterField(message, HEADERSIZE + 142, 2, "E01CPNTBL");
    fields[23] = fieldE01CPNNAR =
    new CharacterField(message, HEADERSIZE + 144, 30, "E01CPNNAR");
    fields[24] = fieldE01CPNDLC =
    new DecimalField(message, HEADERSIZE + 174, 2, 0, "E01CPNDLC");
    fields[25] = fieldE01CPNDL1 =
    new DecimalField(message, HEADERSIZE + 176, 3, 0, "E01CPNDL1");
    fields[26] = fieldE01CPNDL2 =
    new DecimalField(message, HEADERSIZE + 179, 3, 0, "E01CPNDL2");
    fields[27] = fieldE01CPNDL3 =
    new DecimalField(message, HEADERSIZE + 182, 3, 0, "E01CPNDL3");
    fields[28] = fieldE01CPNDLT =
    new DecimalField(message, HEADERSIZE + 185, 7, 0, "E01CPNDLT");
    fields[29] = fieldE01CPNREF =
    new CharacterField(message, HEADERSIZE + 192, 15, "E01CPNREF");
    fields[30] = fieldD01ISIDSC =
    new CharacterField(message, HEADERSIZE + 207, 50, "D01ISIDSC");
    fields[31] = fieldD01ISIPTY =
    new CharacterField(message, HEADERSIZE + 257, 3, "D01ISIPTY");
    fields[32] = fieldD01ISINUM =
    new CharacterField(message, HEADERSIZE + 260, 12, "D01ISINUM");
    fields[33] = fieldD01ISISER =
    new CharacterField(message, HEADERSIZE + 272, 4, "D01ISISER");
    fields[34] = fieldD01ISICUS =
    new CharacterField(message, HEADERSIZE + 276, 12, "D01ISICUS");
    fields[35] = fieldD01ISISYM =
    new CharacterField(message, HEADERSIZE + 288, 15, "D01ISISYM");
    fields[36] = fieldD01ISICCY =
    new CharacterField(message, HEADERSIZE + 303, 3, "D01ISICCY");
    fields[37] = fieldD01ISIRTE =
    new DecimalField(message, HEADERSIZE + 306, 11, 6, "D01ISIRTE");
    fields[38] = fieldD01ISIPFV =
    new DecimalField(message, HEADERSIZE + 317, 4, 0, "D01ISIPFV");
    fields[39] = fieldD01ISIPFC =
    new CharacterField(message, HEADERSIZE + 321, 1, "D01ISIPFC");
    fields[40] = fieldD01CUSCUN =
    new DecimalField(message, HEADERSIZE + 322, 10, 0, "D01CUSCUN");
    fields[41] = fieldD01CUSNME =
    new CharacterField(message, HEADERSIZE + 332, 35, "D01CUSNME");
    fields[42] = fieldD01CSTCOD =
    new CharacterField(message, HEADERSIZE + 367, 3, "D01CSTCOD");
    fields[43] = fieldD01CSTNME =
    new CharacterField(message, HEADERSIZE + 370, 35, "D01CSTNME");
    fields[44] = fieldD01STSDSC =
    new CharacterField(message, HEADERSIZE + 405, 15, "D01STSDSC");
    fields[45] = fieldD01PMTDSC =
    new CharacterField(message, HEADERSIZE + 420, 15, "D01PMTDSC");
    fields[46] = fieldD01ORDIPT =
    new CharacterField(message, HEADERSIZE + 435, 1, "D01ORDIPT");
    fields[47] = fieldD01ORDIBK =
    new CharacterField(message, HEADERSIZE + 436, 2, "D01ORDIBK");
    fields[48] = fieldD01ORDIBR =
    new DecimalField(message, HEADERSIZE + 438, 4, 0, "D01ORDIBR");
    fields[49] = fieldD01ORDICY =
    new CharacterField(message, HEADERSIZE + 442, 3, "D01ORDICY");
    fields[50] = fieldD01ORDIGL =
    new DecimalField(message, HEADERSIZE + 445, 13, 0, "D01ORDIGL");
    fields[51] = fieldD01ORDIAC =
    new DecimalField(message, HEADERSIZE + 458, 10, 0, "D01ORDIAC");
    fields[52] = fieldD01ORDICC =
    new DecimalField(message, HEADERSIZE + 468, 7, 0, "D01ORDICC");
    fields[53] = fieldE01CPNPVI =
    new CharacterField(message, HEADERSIZE + 475, 1, "E01CPNPVI");
    fields[54] = fieldE01CPNCPT =
    new CharacterField(message, HEADERSIZE + 476, 1, "E01CPNCPT");
    fields[55] = fieldE01CPNCBK =
    new CharacterField(message, HEADERSIZE + 477, 2, "E01CPNCBK");
    fields[56] = fieldE01CPNCBR =
    new DecimalField(message, HEADERSIZE + 479, 4, 0, "E01CPNCBR");
    fields[57] = fieldE01CPNCCY =
    new CharacterField(message, HEADERSIZE + 483, 3, "E01CPNCCY");
    fields[58] = fieldE01CPNCGL =
    new DecimalField(message, HEADERSIZE + 486, 13, 0, "E01CPNCGL");
    fields[59] = fieldE01CPNCAC =
    new DecimalField(message, HEADERSIZE + 499, 10, 0, "E01CPNCAC");
    fields[60] = fieldE01CPNCCC =
    new DecimalField(message, HEADERSIZE + 509, 7, 0, "E01CPNCCC");
    fields[61] = fieldE01CPNUSC =
    new CharacterField(message, HEADERSIZE + 516, 10, "E01CPNUSC");
    fields[62] = fieldE01CPNUSA =
    new CharacterField(message, HEADERSIZE + 526, 10, "E01CPNUSA");
    fields[63] = fieldE01CPNRMK =
    new CharacterField(message, HEADERSIZE + 536, 30, "E01CPNRMK");
    fields[64] = fieldE01CPNACT =
    new CharacterField(message, HEADERSIZE + 566, 1, "E01CPNACT");
    fields[65] = fieldE01CPNRCD =
    new DecimalField(message, HEADERSIZE + 567, 6, 0, "E01CPNRCD");
    fields[66] = fieldE01CPNFL0 =
    new CharacterField(message, HEADERSIZE + 573, 1, "E01CPNFL0");
    fields[67] = fieldE01CPNFL1 =
    new CharacterField(message, HEADERSIZE + 574, 1, "E01CPNFL1");
    fields[68] = fieldE01CPNFL2 =
    new CharacterField(message, HEADERSIZE + 575, 1, "E01CPNFL2");
    fields[69] = fieldE01CPNFL3 =
    new CharacterField(message, HEADERSIZE + 576, 1, "E01CPNFL3");
    fields[70] = fieldE01CPNFL4 =
    new CharacterField(message, HEADERSIZE + 577, 15, "E01CPNFL4");
    fields[71] = fieldE01CPNFL5 =
    new CharacterField(message, HEADERSIZE + 592, 15, "E01CPNFL5");
    fields[72] = fieldE01CPNFL6 =
    new CharacterField(message, HEADERSIZE + 607, 15, "E01CPNFL6");
    fields[73] = fieldE01CPNFL7 =
    new DecimalField(message, HEADERSIZE + 622, 23, 6, "E01CPNFL7");
    fields[74] = fieldE01CPNFL8 =
    new DecimalField(message, HEADERSIZE + 645, 23, 6, "E01CPNFL8");
    fields[75] = fieldE01CPNFL9 =
    new DecimalField(message, HEADERSIZE + 668, 23, 6, "E01CPNFL9");

    synchronized (tlookup)
    {
      if (tlookup.isEmpty())
      {
        for (int i = 0; i < tnames.length; i++)
          tlookup.put(tnames[i], new Integer(i));
      }
    }

    taglookup = tlookup;
  }

  /**
  * Set field H01USERID using a String value.
  */
  public void setH01USERID(String newvalue)
  {
    fieldH01USERID.setString(newvalue);
  }

  /**
  * Get value of field H01USERID as a String.
  */
  public String getH01USERID()
  {
    return fieldH01USERID.getString();
  }

  /**
  * Set field H01PROGRM using a String value.
  */
  public void setH01PROGRM(String newvalue)
  {
    fieldH01PROGRM.setString(newvalue);
  }

  /**
  * Get value of field H01PROGRM as a String.
  */
  public String getH01PROGRM()
  {
    return fieldH01PROGRM.getString();
  }

  /**
  * Set field H01TIMSYS using a String value.
  */
  public void setH01TIMSYS(String newvalue)
  {
    fieldH01TIMSYS.setString(newvalue);
  }

  /**
  * Get value of field H01TIMSYS as a String.
  */
  public String getH01TIMSYS()
  {
    return fieldH01TIMSYS.getString();
  }

  /**
  * Set field H01SCRCOD using a String value.
  */
  public void setH01SCRCOD(String newvalue)
  {
    fieldH01SCRCOD.setString(newvalue);
  }

  /**
  * Get value of field H01SCRCOD as a String.
  */
  public String getH01SCRCOD()
  {
    return fieldH01SCRCOD.getString();
  }

  /**
  * Set field H01OPECOD using a String value.
  */
  public void setH01OPECOD(String newvalue)
  {
    fieldH01OPECOD.setString(newvalue);
  }

  /**
  * Get value of field H01OPECOD as a String.
  */
  public String getH01OPECOD()
  {
    return fieldH01OPECOD.getString();
  }

  /**
  * Set field H01FLGMAS using a String value.
  */
  public void setH01FLGMAS(String newvalue)
  {
    fieldH01FLGMAS.setString(newvalue);
  }

  /**
  * Get value of field H01FLGMAS as a String.
  */
  public String getH01FLGMAS()
  {
    return fieldH01FLGMAS.getString();
  }

  /**
  * Set field H01FLGWK1 using a String value.
  */
  public void setH01FLGWK1(String newvalue)
  {
    fieldH01FLGWK1.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK1 as a String.
  */
  public String getH01FLGWK1()
  {
    return fieldH01FLGWK1.getString();
  }

  /**
  * Set field H01FLGWK2 using a String value.
  */
  public void setH01FLGWK2(String newvalue)
  {
    fieldH01FLGWK2.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK2 as a String.
  */
  public String getH01FLGWK2()
  {
    return fieldH01FLGWK2.getString();
  }

  /**
  * Set field H01FLGWK3 using a String value.
  */
  public void setH01FLGWK3(String newvalue)
  {
    fieldH01FLGWK3.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK3 as a String.
  */
  public String getH01FLGWK3()
  {
    return fieldH01FLGWK3.getString();
  }

  /**
  * Set field E01CPNSTS using a String value.
  */
  public void setE01CPNSTS(String newvalue)
  {
    fieldE01CPNSTS.setString(newvalue);
  }

  /**
  * Get value of field E01CPNSTS as a String.
  */
  public String getE01CPNSTS()
  {
    return fieldE01CPNSTS.getString();
  }

  /**
  * Set field E01CPNIIC using a String value.
  */
  public void setE01CPNIIC(String newvalue)
  {
    fieldE01CPNIIC.setString(newvalue);
  }

  /**
  * Get value of field E01CPNIIC as a String.
  */
  public String getE01CPNIIC()
  {
    return fieldE01CPNIIC.getString();
  }

  /**
  * Set numeric field E01CPNIIC using a BigDecimal value.
  */
  public void setE01CPNIIC(BigDecimal newvalue)
  {
    fieldE01CPNIIC.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CPNIIC as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CPNIIC()
  {
    return fieldE01CPNIIC.getBigDecimal();
  }

  /**
  * Set field E01CPNTYP using a String value.
  */
  public void setE01CPNTYP(String newvalue)
  {
    fieldE01CPNTYP.setString(newvalue);
  }

  /**
  * Get value of field E01CPNTYP as a String.
  */
  public String getE01CPNTYP()
  {
    return fieldE01CPNTYP.getString();
  }

  /**
  * Set field E01CPNPMC using a String value.
  */
  public void setE01CPNPMC(String newvalue)
  {
    fieldE01CPNPMC.setString(newvalue);
  }

  /**
  * Get value of field E01CPNPMC as a String.
  */
  public String getE01CPNPMC()
  {
    return fieldE01CPNPMC.getString();
  }

  /**
  * Set numeric field E01CPNPMC using a BigDecimal value.
  */
  public void setE01CPNPMC(BigDecimal newvalue)
  {
    fieldE01CPNPMC.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CPNPMC as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CPNPMC()
  {
    return fieldE01CPNPMC.getBigDecimal();
  }

  /**
  * Set field E01CPNPM1 using a String value.
  */
  public void setE01CPNPM1(String newvalue)
  {
    fieldE01CPNPM1.setString(newvalue);
  }

  /**
  * Get value of field E01CPNPM1 as a String.
  */
  public String getE01CPNPM1()
  {
    return fieldE01CPNPM1.getString();
  }

  /**
  * Set numeric field E01CPNPM1 using a BigDecimal value.
  */
  public void setE01CPNPM1(BigDecimal newvalue)
  {
    fieldE01CPNPM1.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CPNPM1 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CPNPM1()
  {
    return fieldE01CPNPM1.getBigDecimal();
  }

  /**
  * Set field E01CPNPM2 using a String value.
  */
  public void setE01CPNPM2(String newvalue)
  {
    fieldE01CPNPM2.setString(newvalue);
  }

  /**
  * Get value of field E01CPNPM2 as a String.
  */
  public String getE01CPNPM2()
  {
    return fieldE01CPNPM2.getString();
  }

  /**
  * Set numeric field E01CPNPM2 using a BigDecimal value.
  */
  public void setE01CPNPM2(BigDecimal newvalue)
  {
    fieldE01CPNPM2.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CPNPM2 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CPNPM2()
  {
    return fieldE01CPNPM2.getBigDecimal();
  }

  /**
  * Set field E01CPNPM3 using a String value.
  */
  public void setE01CPNPM3(String newvalue)
  {
    fieldE01CPNPM3.setString(newvalue);
  }

  /**
  * Get value of field E01CPNPM3 as a String.
  */
  public String getE01CPNPM3()
  {
    return fieldE01CPNPM3.getString();
  }

  /**
  * Set numeric field E01CPNPM3 using a BigDecimal value.
  */
  public void setE01CPNPM3(BigDecimal newvalue)
  {
    fieldE01CPNPM3.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CPNPM3 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CPNPM3()
  {
    return fieldE01CPNPM3.getBigDecimal();
  }

  /**
  * Set field E01CPNPMT using a String value.
  */
  public void setE01CPNPMT(String newvalue)
  {
    fieldE01CPNPMT.setString(newvalue);
  }

  /**
  * Get value of field E01CPNPMT as a String.
  */
  public String getE01CPNPMT()
  {
    return fieldE01CPNPMT.getString();
  }

  /**
  * Set numeric field E01CPNPMT using a BigDecimal value.
  */
  public void setE01CPNPMT(BigDecimal newvalue)
  {
    fieldE01CPNPMT.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CPNPMT as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CPNPMT()
  {
    return fieldE01CPNPMT.getBigDecimal();
  }

  /**
  * Set field E01CPNNUM using a String value.
  */
  public void setE01CPNNUM(String newvalue)
  {
    fieldE01CPNNUM.setString(newvalue);
  }

  /**
  * Get value of field E01CPNNUM as a String.
  */
  public String getE01CPNNUM()
  {
    return fieldE01CPNNUM.getString();
  }

  /**
  * Set numeric field E01CPNNUM using a BigDecimal value.
  */
  public void setE01CPNNUM(BigDecimal newvalue)
  {
    fieldE01CPNNUM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CPNNUM as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CPNNUM()
  {
    return fieldE01CPNNUM.getBigDecimal();
  }

  /**
  * Set field E01CPNAMT using a String value.
  */
  public void setE01CPNAMT(String newvalue)
  {
    fieldE01CPNAMT.setString(newvalue);
  }

  /**
  * Get value of field E01CPNAMT as a String.
  */
  public String getE01CPNAMT()
  {
    return fieldE01CPNAMT.getString();
  }

  /**
  * Set numeric field E01CPNAMT using a BigDecimal value.
  */
  public void setE01CPNAMT(BigDecimal newvalue)
  {
    fieldE01CPNAMT.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CPNAMT as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CPNAMT()
  {
    return fieldE01CPNAMT.getBigDecimal();
  }

  /**
  * Set field E01CPNCOM using a String value.
  */
  public void setE01CPNCOM(String newvalue)
  {
    fieldE01CPNCOM.setString(newvalue);
  }

  /**
  * Get value of field E01CPNCOM as a String.
  */
  public String getE01CPNCOM()
  {
    return fieldE01CPNCOM.getString();
  }

  /**
  * Set numeric field E01CPNCOM using a BigDecimal value.
  */
  public void setE01CPNCOM(BigDecimal newvalue)
  {
    fieldE01CPNCOM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CPNCOM as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CPNCOM()
  {
    return fieldE01CPNCOM.getBigDecimal();
  }

  /**
  * Set field E01CPNPAM using a String value.
  */
  public void setE01CPNPAM(String newvalue)
  {
    fieldE01CPNPAM.setString(newvalue);
  }

  /**
  * Get value of field E01CPNPAM as a String.
  */
  public String getE01CPNPAM()
  {
    return fieldE01CPNPAM.getString();
  }

  /**
  * Set numeric field E01CPNPAM using a BigDecimal value.
  */
  public void setE01CPNPAM(BigDecimal newvalue)
  {
    fieldE01CPNPAM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CPNPAM as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CPNPAM()
  {
    return fieldE01CPNPAM.getBigDecimal();
  }

  /**
  * Set field E01CPNDAM using a String value.
  */
  public void setE01CPNDAM(String newvalue)
  {
    fieldE01CPNDAM.setString(newvalue);
  }

  /**
  * Get value of field E01CPNDAM as a String.
  */
  public String getE01CPNDAM()
  {
    return fieldE01CPNDAM.getString();
  }

  /**
  * Set numeric field E01CPNDAM using a BigDecimal value.
  */
  public void setE01CPNDAM(BigDecimal newvalue)
  {
    fieldE01CPNDAM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CPNDAM as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CPNDAM()
  {
    return fieldE01CPNDAM.getBigDecimal();
  }

  /**
  * Set field E01CPNTBL using a String value.
  */
  public void setE01CPNTBL(String newvalue)
  {
    fieldE01CPNTBL.setString(newvalue);
  }

  /**
  * Get value of field E01CPNTBL as a String.
  */
  public String getE01CPNTBL()
  {
    return fieldE01CPNTBL.getString();
  }

  /**
  * Set field E01CPNNAR using a String value.
  */
  public void setE01CPNNAR(String newvalue)
  {
    fieldE01CPNNAR.setString(newvalue);
  }

  /**
  * Get value of field E01CPNNAR as a String.
  */
  public String getE01CPNNAR()
  {
    return fieldE01CPNNAR.getString();
  }

  /**
  * Set field E01CPNDLC using a String value.
  */
  public void setE01CPNDLC(String newvalue)
  {
    fieldE01CPNDLC.setString(newvalue);
  }

  /**
  * Get value of field E01CPNDLC as a String.
  */
  public String getE01CPNDLC()
  {
    return fieldE01CPNDLC.getString();
  }

  /**
  * Set numeric field E01CPNDLC using a BigDecimal value.
  */
  public void setE01CPNDLC(BigDecimal newvalue)
  {
    fieldE01CPNDLC.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CPNDLC as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CPNDLC()
  {
    return fieldE01CPNDLC.getBigDecimal();
  }

  /**
  * Set field E01CPNDL1 using a String value.
  */
  public void setE01CPNDL1(String newvalue)
  {
    fieldE01CPNDL1.setString(newvalue);
  }

  /**
  * Get value of field E01CPNDL1 as a String.
  */
  public String getE01CPNDL1()
  {
    return fieldE01CPNDL1.getString();
  }

  /**
  * Set numeric field E01CPNDL1 using a BigDecimal value.
  */
  public void setE01CPNDL1(BigDecimal newvalue)
  {
    fieldE01CPNDL1.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CPNDL1 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CPNDL1()
  {
    return fieldE01CPNDL1.getBigDecimal();
  }

  /**
  * Set field E01CPNDL2 using a String value.
  */
  public void setE01CPNDL2(String newvalue)
  {
    fieldE01CPNDL2.setString(newvalue);
  }

  /**
  * Get value of field E01CPNDL2 as a String.
  */
  public String getE01CPNDL2()
  {
    return fieldE01CPNDL2.getString();
  }

  /**
  * Set numeric field E01CPNDL2 using a BigDecimal value.
  */
  public void setE01CPNDL2(BigDecimal newvalue)
  {
    fieldE01CPNDL2.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CPNDL2 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CPNDL2()
  {
    return fieldE01CPNDL2.getBigDecimal();
  }

  /**
  * Set field E01CPNDL3 using a String value.
  */
  public void setE01CPNDL3(String newvalue)
  {
    fieldE01CPNDL3.setString(newvalue);
  }

  /**
  * Get value of field E01CPNDL3 as a String.
  */
  public String getE01CPNDL3()
  {
    return fieldE01CPNDL3.getString();
  }

  /**
  * Set numeric field E01CPNDL3 using a BigDecimal value.
  */
  public void setE01CPNDL3(BigDecimal newvalue)
  {
    fieldE01CPNDL3.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CPNDL3 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CPNDL3()
  {
    return fieldE01CPNDL3.getBigDecimal();
  }

  /**
  * Set field E01CPNDLT using a String value.
  */
  public void setE01CPNDLT(String newvalue)
  {
    fieldE01CPNDLT.setString(newvalue);
  }

  /**
  * Get value of field E01CPNDLT as a String.
  */
  public String getE01CPNDLT()
  {
    return fieldE01CPNDLT.getString();
  }

  /**
  * Set numeric field E01CPNDLT using a BigDecimal value.
  */
  public void setE01CPNDLT(BigDecimal newvalue)
  {
    fieldE01CPNDLT.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CPNDLT as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CPNDLT()
  {
    return fieldE01CPNDLT.getBigDecimal();
  }

  /**
  * Set field E01CPNREF using a String value.
  */
  public void setE01CPNREF(String newvalue)
  {
    fieldE01CPNREF.setString(newvalue);
  }

  /**
  * Get value of field E01CPNREF as a String.
  */
  public String getE01CPNREF()
  {
    return fieldE01CPNREF.getString();
  }

  /**
  * Set field D01ISIDSC using a String value.
  */
  public void setD01ISIDSC(String newvalue)
  {
    fieldD01ISIDSC.setString(newvalue);
  }

  /**
  * Get value of field D01ISIDSC as a String.
  */
  public String getD01ISIDSC()
  {
    return fieldD01ISIDSC.getString();
  }

  /**
  * Set field D01ISIPTY using a String value.
  */
  public void setD01ISIPTY(String newvalue)
  {
    fieldD01ISIPTY.setString(newvalue);
  }

  /**
  * Get value of field D01ISIPTY as a String.
  */
  public String getD01ISIPTY()
  {
    return fieldD01ISIPTY.getString();
  }

  /**
  * Set field D01ISINUM using a String value.
  */
  public void setD01ISINUM(String newvalue)
  {
    fieldD01ISINUM.setString(newvalue);
  }

  /**
  * Get value of field D01ISINUM as a String.
  */
  public String getD01ISINUM()
  {
    return fieldD01ISINUM.getString();
  }

  /**
  * Set field D01ISISER using a String value.
  */
  public void setD01ISISER(String newvalue)
  {
    fieldD01ISISER.setString(newvalue);
  }

  /**
  * Get value of field D01ISISER as a String.
  */
  public String getD01ISISER()
  {
    return fieldD01ISISER.getString();
  }

  /**
  * Set field D01ISICUS using a String value.
  */
  public void setD01ISICUS(String newvalue)
  {
    fieldD01ISICUS.setString(newvalue);
  }

  /**
  * Get value of field D01ISICUS as a String.
  */
  public String getD01ISICUS()
  {
    return fieldD01ISICUS.getString();
  }

  /**
  * Set field D01ISISYM using a String value.
  */
  public void setD01ISISYM(String newvalue)
  {
    fieldD01ISISYM.setString(newvalue);
  }

  /**
  * Get value of field D01ISISYM as a String.
  */
  public String getD01ISISYM()
  {
    return fieldD01ISISYM.getString();
  }

  /**
  * Set field D01ISICCY using a String value.
  */
  public void setD01ISICCY(String newvalue)
  {
    fieldD01ISICCY.setString(newvalue);
  }

  /**
  * Get value of field D01ISICCY as a String.
  */
  public String getD01ISICCY()
  {
    return fieldD01ISICCY.getString();
  }

  /**
  * Set field D01ISIRTE using a String value.
  */
  public void setD01ISIRTE(String newvalue)
  {
    fieldD01ISIRTE.setString(newvalue);
  }

  /**
  * Get value of field D01ISIRTE as a String.
  */
  public String getD01ISIRTE()
  {
    return fieldD01ISIRTE.getString();
  }

  /**
  * Set numeric field D01ISIRTE using a BigDecimal value.
  */
  public void setD01ISIRTE(BigDecimal newvalue)
  {
    fieldD01ISIRTE.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field D01ISIRTE as a BigDecimal.
  */
  public BigDecimal getBigDecimalD01ISIRTE()
  {
    return fieldD01ISIRTE.getBigDecimal();
  }

  /**
  * Set field D01ISIPFV using a String value.
  */
  public void setD01ISIPFV(String newvalue)
  {
    fieldD01ISIPFV.setString(newvalue);
  }

  /**
  * Get value of field D01ISIPFV as a String.
  */
  public String getD01ISIPFV()
  {
    return fieldD01ISIPFV.getString();
  }

  /**
  * Set numeric field D01ISIPFV using a BigDecimal value.
  */
  public void setD01ISIPFV(BigDecimal newvalue)
  {
    fieldD01ISIPFV.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field D01ISIPFV as a BigDecimal.
  */
  public BigDecimal getBigDecimalD01ISIPFV()
  {
    return fieldD01ISIPFV.getBigDecimal();
  }

  /**
  * Set field D01ISIPFC using a String value.
  */
  public void setD01ISIPFC(String newvalue)
  {
    fieldD01ISIPFC.setString(newvalue);
  }

  /**
  * Get value of field D01ISIPFC as a String.
  */
  public String getD01ISIPFC()
  {
    return fieldD01ISIPFC.getString();
  }

  /**
  * Set field D01CUSCUN using a String value.
  */
  public void setD01CUSCUN(String newvalue)
  {
    fieldD01CUSCUN.setString(newvalue);
  }

  /**
  * Get value of field D01CUSCUN as a String.
  */
  public String getD01CUSCUN()
  {
    return fieldD01CUSCUN.getString();
  }

  /**
  * Set numeric field D01CUSCUN using a BigDecimal value.
  */
  public void setD01CUSCUN(BigDecimal newvalue)
  {
    fieldD01CUSCUN.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field D01CUSCUN as a BigDecimal.
  */
  public BigDecimal getBigDecimalD01CUSCUN()
  {
    return fieldD01CUSCUN.getBigDecimal();
  }

  /**
  * Set field D01CUSNME using a String value.
  */
  public void setD01CUSNME(String newvalue)
  {
    fieldD01CUSNME.setString(newvalue);
  }

  /**
  * Get value of field D01CUSNME as a String.
  */
  public String getD01CUSNME()
  {
    return fieldD01CUSNME.getString();
  }

  /**
  * Set field D01CSTCOD using a String value.
  */
  public void setD01CSTCOD(String newvalue)
  {
    fieldD01CSTCOD.setString(newvalue);
  }

  /**
  * Get value of field D01CSTCOD as a String.
  */
  public String getD01CSTCOD()
  {
    return fieldD01CSTCOD.getString();
  }

  /**
  * Set field D01CSTNME using a String value.
  */
  public void setD01CSTNME(String newvalue)
  {
    fieldD01CSTNME.setString(newvalue);
  }

  /**
  * Get value of field D01CSTNME as a String.
  */
  public String getD01CSTNME()
  {
    return fieldD01CSTNME.getString();
  }

  /**
  * Set field D01STSDSC using a String value.
  */
  public void setD01STSDSC(String newvalue)
  {
    fieldD01STSDSC.setString(newvalue);
  }

  /**
  * Get value of field D01STSDSC as a String.
  */
  public String getD01STSDSC()
  {
    return fieldD01STSDSC.getString();
  }

  /**
  * Set field D01PMTDSC using a String value.
  */
  public void setD01PMTDSC(String newvalue)
  {
    fieldD01PMTDSC.setString(newvalue);
  }

  /**
  * Get value of field D01PMTDSC as a String.
  */
  public String getD01PMTDSC()
  {
    return fieldD01PMTDSC.getString();
  }

  /**
  * Set field D01ORDIPT using a String value.
  */
  public void setD01ORDIPT(String newvalue)
  {
    fieldD01ORDIPT.setString(newvalue);
  }

  /**
  * Get value of field D01ORDIPT as a String.
  */
  public String getD01ORDIPT()
  {
    return fieldD01ORDIPT.getString();
  }

  /**
  * Set field D01ORDIBK using a String value.
  */
  public void setD01ORDIBK(String newvalue)
  {
    fieldD01ORDIBK.setString(newvalue);
  }

  /**
  * Get value of field D01ORDIBK as a String.
  */
  public String getD01ORDIBK()
  {
    return fieldD01ORDIBK.getString();
  }

  /**
  * Set field D01ORDIBR using a String value.
  */
  public void setD01ORDIBR(String newvalue)
  {
    fieldD01ORDIBR.setString(newvalue);
  }

  /**
  * Get value of field D01ORDIBR as a String.
  */
  public String getD01ORDIBR()
  {
    return fieldD01ORDIBR.getString();
  }

  /**
  * Set numeric field D01ORDIBR using a BigDecimal value.
  */
  public void setD01ORDIBR(BigDecimal newvalue)
  {
    fieldD01ORDIBR.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field D01ORDIBR as a BigDecimal.
  */
  public BigDecimal getBigDecimalD01ORDIBR()
  {
    return fieldD01ORDIBR.getBigDecimal();
  }

  /**
  * Set field D01ORDICY using a String value.
  */
  public void setD01ORDICY(String newvalue)
  {
    fieldD01ORDICY.setString(newvalue);
  }

  /**
  * Get value of field D01ORDICY as a String.
  */
  public String getD01ORDICY()
  {
    return fieldD01ORDICY.getString();
  }

  /**
  * Set field D01ORDIGL using a String value.
  */
  public void setD01ORDIGL(String newvalue)
  {
    fieldD01ORDIGL.setString(newvalue);
  }

  /**
  * Get value of field D01ORDIGL as a String.
  */
  public String getD01ORDIGL()
  {
    return fieldD01ORDIGL.getString();
  }

  /**
  * Set numeric field D01ORDIGL using a BigDecimal value.
  */
  public void setD01ORDIGL(BigDecimal newvalue)
  {
    fieldD01ORDIGL.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field D01ORDIGL as a BigDecimal.
  */
  public BigDecimal getBigDecimalD01ORDIGL()
  {
    return fieldD01ORDIGL.getBigDecimal();
  }

  /**
  * Set field D01ORDIAC using a String value.
  */
  public void setD01ORDIAC(String newvalue)
  {
    fieldD01ORDIAC.setString(newvalue);
  }

  /**
  * Get value of field D01ORDIAC as a String.
  */
  public String getD01ORDIAC()
  {
    return fieldD01ORDIAC.getString();
  }

  /**
  * Set numeric field D01ORDIAC using a BigDecimal value.
  */
  public void setD01ORDIAC(BigDecimal newvalue)
  {
    fieldD01ORDIAC.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field D01ORDIAC as a BigDecimal.
  */
  public BigDecimal getBigDecimalD01ORDIAC()
  {
    return fieldD01ORDIAC.getBigDecimal();
  }

  /**
  * Set field D01ORDICC using a String value.
  */
  public void setD01ORDICC(String newvalue)
  {
    fieldD01ORDICC.setString(newvalue);
  }

  /**
  * Get value of field D01ORDICC as a String.
  */
  public String getD01ORDICC()
  {
    return fieldD01ORDICC.getString();
  }

  /**
  * Set numeric field D01ORDICC using a BigDecimal value.
  */
  public void setD01ORDICC(BigDecimal newvalue)
  {
    fieldD01ORDICC.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field D01ORDICC as a BigDecimal.
  */
  public BigDecimal getBigDecimalD01ORDICC()
  {
    return fieldD01ORDICC.getBigDecimal();
  }

  /**
  * Set field E01CPNPVI using a String value.
  */
  public void setE01CPNPVI(String newvalue)
  {
    fieldE01CPNPVI.setString(newvalue);
  }

  /**
  * Get value of field E01CPNPVI as a String.
  */
  public String getE01CPNPVI()
  {
    return fieldE01CPNPVI.getString();
  }

  /**
  * Set field E01CPNCPT using a String value.
  */
  public void setE01CPNCPT(String newvalue)
  {
    fieldE01CPNCPT.setString(newvalue);
  }

  /**
  * Get value of field E01CPNCPT as a String.
  */
  public String getE01CPNCPT()
  {
    return fieldE01CPNCPT.getString();
  }

  /**
  * Set field E01CPNCBK using a String value.
  */
  public void setE01CPNCBK(String newvalue)
  {
    fieldE01CPNCBK.setString(newvalue);
  }

  /**
  * Get value of field E01CPNCBK as a String.
  */
  public String getE01CPNCBK()
  {
    return fieldE01CPNCBK.getString();
  }

  /**
  * Set field E01CPNCBR using a String value.
  */
  public void setE01CPNCBR(String newvalue)
  {
    fieldE01CPNCBR.setString(newvalue);
  }

  /**
  * Get value of field E01CPNCBR as a String.
  */
  public String getE01CPNCBR()
  {
    return fieldE01CPNCBR.getString();
  }

  /**
  * Set numeric field E01CPNCBR using a BigDecimal value.
  */
  public void setE01CPNCBR(BigDecimal newvalue)
  {
    fieldE01CPNCBR.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CPNCBR as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CPNCBR()
  {
    return fieldE01CPNCBR.getBigDecimal();
  }

  /**
  * Set field E01CPNCCY using a String value.
  */
  public void setE01CPNCCY(String newvalue)
  {
    fieldE01CPNCCY.setString(newvalue);
  }

  /**
  * Get value of field E01CPNCCY as a String.
  */
  public String getE01CPNCCY()
  {
    return fieldE01CPNCCY.getString();
  }

  /**
  * Set field E01CPNCGL using a String value.
  */
  public void setE01CPNCGL(String newvalue)
  {
    fieldE01CPNCGL.setString(newvalue);
  }

  /**
  * Get value of field E01CPNCGL as a String.
  */
  public String getE01CPNCGL()
  {
    return fieldE01CPNCGL.getString();
  }

  /**
  * Set numeric field E01CPNCGL using a BigDecimal value.
  */
  public void setE01CPNCGL(BigDecimal newvalue)
  {
    fieldE01CPNCGL.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CPNCGL as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CPNCGL()
  {
    return fieldE01CPNCGL.getBigDecimal();
  }

  /**
  * Set field E01CPNCAC using a String value.
  */
  public void setE01CPNCAC(String newvalue)
  {
    fieldE01CPNCAC.setString(newvalue);
  }

  /**
  * Get value of field E01CPNCAC as a String.
  */
  public String getE01CPNCAC()
  {
    return fieldE01CPNCAC.getString();
  }

  /**
  * Set numeric field E01CPNCAC using a BigDecimal value.
  */
  public void setE01CPNCAC(BigDecimal newvalue)
  {
    fieldE01CPNCAC.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CPNCAC as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CPNCAC()
  {
    return fieldE01CPNCAC.getBigDecimal();
  }

  /**
  * Set field E01CPNCCC using a String value.
  */
  public void setE01CPNCCC(String newvalue)
  {
    fieldE01CPNCCC.setString(newvalue);
  }

  /**
  * Get value of field E01CPNCCC as a String.
  */
  public String getE01CPNCCC()
  {
    return fieldE01CPNCCC.getString();
  }

  /**
  * Set numeric field E01CPNCCC using a BigDecimal value.
  */
  public void setE01CPNCCC(BigDecimal newvalue)
  {
    fieldE01CPNCCC.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CPNCCC as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CPNCCC()
  {
    return fieldE01CPNCCC.getBigDecimal();
  }

  /**
  * Set field E01CPNUSC using a String value.
  */
  public void setE01CPNUSC(String newvalue)
  {
    fieldE01CPNUSC.setString(newvalue);
  }

  /**
  * Get value of field E01CPNUSC as a String.
  */
  public String getE01CPNUSC()
  {
    return fieldE01CPNUSC.getString();
  }

  /**
  * Set field E01CPNUSA using a String value.
  */
  public void setE01CPNUSA(String newvalue)
  {
    fieldE01CPNUSA.setString(newvalue);
  }

  /**
  * Get value of field E01CPNUSA as a String.
  */
  public String getE01CPNUSA()
  {
    return fieldE01CPNUSA.getString();
  }

  /**
  * Set field E01CPNRMK using a String value.
  */
  public void setE01CPNRMK(String newvalue)
  {
    fieldE01CPNRMK.setString(newvalue);
  }

  /**
  * Get value of field E01CPNRMK as a String.
  */
  public String getE01CPNRMK()
  {
    return fieldE01CPNRMK.getString();
  }

  /**
  * Set field E01CPNACT using a String value.
  */
  public void setE01CPNACT(String newvalue)
  {
    fieldE01CPNACT.setString(newvalue);
  }

  /**
  * Get value of field E01CPNACT as a String.
  */
  public String getE01CPNACT()
  {
    return fieldE01CPNACT.getString();
  }

  /**
  * Set field E01CPNRCD using a String value.
  */
  public void setE01CPNRCD(String newvalue)
  {
    fieldE01CPNRCD.setString(newvalue);
  }

  /**
  * Get value of field E01CPNRCD as a String.
  */
  public String getE01CPNRCD()
  {
    return fieldE01CPNRCD.getString();
  }

  /**
  * Set numeric field E01CPNRCD using a BigDecimal value.
  */
  public void setE01CPNRCD(BigDecimal newvalue)
  {
    fieldE01CPNRCD.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CPNRCD as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CPNRCD()
  {
    return fieldE01CPNRCD.getBigDecimal();
  }

  /**
  * Set field E01CPNFL0 using a String value.
  */
  public void setE01CPNFL0(String newvalue)
  {
    fieldE01CPNFL0.setString(newvalue);
  }

  /**
  * Get value of field E01CPNFL0 as a String.
  */
  public String getE01CPNFL0()
  {
    return fieldE01CPNFL0.getString();
  }

  /**
  * Set field E01CPNFL1 using a String value.
  */
  public void setE01CPNFL1(String newvalue)
  {
    fieldE01CPNFL1.setString(newvalue);
  }

  /**
  * Get value of field E01CPNFL1 as a String.
  */
  public String getE01CPNFL1()
  {
    return fieldE01CPNFL1.getString();
  }

  /**
  * Set field E01CPNFL2 using a String value.
  */
  public void setE01CPNFL2(String newvalue)
  {
    fieldE01CPNFL2.setString(newvalue);
  }

  /**
  * Get value of field E01CPNFL2 as a String.
  */
  public String getE01CPNFL2()
  {
    return fieldE01CPNFL2.getString();
  }

  /**
  * Set field E01CPNFL3 using a String value.
  */
  public void setE01CPNFL3(String newvalue)
  {
    fieldE01CPNFL3.setString(newvalue);
  }

  /**
  * Get value of field E01CPNFL3 as a String.
  */
  public String getE01CPNFL3()
  {
    return fieldE01CPNFL3.getString();
  }

  /**
  * Set field E01CPNFL4 using a String value.
  */
  public void setE01CPNFL4(String newvalue)
  {
    fieldE01CPNFL4.setString(newvalue);
  }

  /**
  * Get value of field E01CPNFL4 as a String.
  */
  public String getE01CPNFL4()
  {
    return fieldE01CPNFL4.getString();
  }

  /**
  * Set field E01CPNFL5 using a String value.
  */
  public void setE01CPNFL5(String newvalue)
  {
    fieldE01CPNFL5.setString(newvalue);
  }

  /**
  * Get value of field E01CPNFL5 as a String.
  */
  public String getE01CPNFL5()
  {
    return fieldE01CPNFL5.getString();
  }

  /**
  * Set field E01CPNFL6 using a String value.
  */
  public void setE01CPNFL6(String newvalue)
  {
    fieldE01CPNFL6.setString(newvalue);
  }

  /**
  * Get value of field E01CPNFL6 as a String.
  */
  public String getE01CPNFL6()
  {
    return fieldE01CPNFL6.getString();
  }

  /**
  * Set field E01CPNFL7 using a String value.
  */
  public void setE01CPNFL7(String newvalue)
  {
    fieldE01CPNFL7.setString(newvalue);
  }

  /**
  * Get value of field E01CPNFL7 as a String.
  */
  public String getE01CPNFL7()
  {
    return fieldE01CPNFL7.getString();
  }

  /**
  * Set numeric field E01CPNFL7 using a BigDecimal value.
  */
  public void setE01CPNFL7(BigDecimal newvalue)
  {
    fieldE01CPNFL7.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CPNFL7 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CPNFL7()
  {
    return fieldE01CPNFL7.getBigDecimal();
  }

  /**
  * Set field E01CPNFL8 using a String value.
  */
  public void setE01CPNFL8(String newvalue)
  {
    fieldE01CPNFL8.setString(newvalue);
  }

  /**
  * Get value of field E01CPNFL8 as a String.
  */
  public String getE01CPNFL8()
  {
    return fieldE01CPNFL8.getString();
  }

  /**
  * Set numeric field E01CPNFL8 using a BigDecimal value.
  */
  public void setE01CPNFL8(BigDecimal newvalue)
  {
    fieldE01CPNFL8.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CPNFL8 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CPNFL8()
  {
    return fieldE01CPNFL8.getBigDecimal();
  }

  /**
  * Set field E01CPNFL9 using a String value.
  */
  public void setE01CPNFL9(String newvalue)
  {
    fieldE01CPNFL9.setString(newvalue);
  }

  /**
  * Get value of field E01CPNFL9 as a String.
  */
  public String getE01CPNFL9()
  {
    return fieldE01CPNFL9.getString();
  }

  /**
  * Set numeric field E01CPNFL9 using a BigDecimal value.
  */
  public void setE01CPNFL9(BigDecimal newvalue)
  {
    fieldE01CPNFL9.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CPNFL9 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CPNFL9()
  {
    return fieldE01CPNFL9.getBigDecimal();
  }

}
