package datapro.eibs.beans;

import datapro.eibs.sockets.*;
import java.io.*;
import java.math.*;

import java.util.*;

/**
* Class generated by AS/400 CRTCLASS command from ERA001002 physical file definition.
* 
* File level identifier is 1030214133818.
* Record format level identifier is 2A3A4CEB60EDB.
*/

public class ERA001002Message extends MessageRecord
{
  final static String fldnames[] = {
                                     "H02USERID",
                                     "H02PROGRM",
                                     "H02TIMSYS",
                                     "H02SCRCOD",
                                     "H02OPECOD",
                                     "H02FLGMAS",
                                     "H02FLGWK1",
                                     "H02FLGWK2",
                                     "H02FLGWK3",
                                     "E02RODBNK",
                                     "E02RODCUN",
                                     "E02RODREF",
                                     "E02RODSEQ",
                                     "E02RODSTS",
                                     "E02RODNBR",
                                     "E02RODDSC",
                                     "E02RODOD1",
                                     "E02RODOD2",
                                     "E02RODOD3",
                                     "E02RODMD1",
                                     "E02RODMD2",
                                     "E02RODMD3",
                                     "E02RODAMT",
                                     "E02RODFLG",
                                     "E02RODUC1",
                                     "E02RODUC2",
                                     "E02RODUC7",
                                     "E02RODRF2",
                                     "E02RODRF4",
                                     "E02RODAIN",
                                     "F02RODBNK",
                                     "F02RODCUN",
                                     "F02RODREF",
                                     "F02RODSEQ",
                                     "F02RODSTS",
                                     "F02RODNBR",
                                     "F02RODDSC",
                                     "F02RODOD1",
                                     "F02RODOD2",
                                     "F02RODOD3",
                                     "F02RODMD1",
                                     "F02RODMD2",
                                     "F02RODMD3",
                                     "F02RODAMT",
                                     "F02RODFLG",
                                     "F02RODUC1",
                                     "F02RODUC2",
                                     "F02RODUC7",
                                     "F02RODRF2",
                                     "F02RODRF4",
                                     "F02RODAIN"
                                   };
  final static String tnames[] = {
                                   "H02USERID",
                                   "H02PROGRM",
                                   "H02TIMSYS",
                                   "H02SCRCOD",
                                   "H02OPECOD",
                                   "H02FLGMAS",
                                   "H02FLGWK1",
                                   "H02FLGWK2",
                                   "H02FLGWK3",
                                   "E02RODBNK",
                                   "E02RODCUN",
                                   "E02RODREF",
                                   "E02RODSEQ",
                                   "E02RODSTS",
                                   "E02RODNBR",
                                   "E02RODDSC",
                                   "E02RODOD1",
                                   "E02RODOD2",
                                   "E02RODOD3",
                                   "E02RODMD1",
                                   "E02RODMD2",
                                   "E02RODMD3",
                                   "E02RODAMT",
                                   "E02RODFLG",
                                   "E02RODUC1",
                                   "E02RODUC2",
                                   "E02RODUC7",
                                   "E02RODRF2",
                                   "E02RODRF4",
                                   "E02RODAIN",
                                   "F02RODBNK",
                                   "F02RODCUN",
                                   "F02RODREF",
                                   "F02RODSEQ",
                                   "F02RODSTS",
                                   "F02RODNBR",
                                   "F02RODDSC",
                                   "F02RODOD1",
                                   "F02RODOD2",
                                   "F02RODOD3",
                                   "F02RODMD1",
                                   "F02RODMD2",
                                   "F02RODMD3",
                                   "F02RODAMT",
                                   "F02RODFLG",
                                   "F02RODUC1",
                                   "F02RODUC2",
                                   "F02RODUC7",
                                   "F02RODRF2",
                                   "F02RODRF4",
                                   "F02RODAIN"
                                 };
  final static String fid = "1030214133818";
  final static String rid = "2A3A4CEB60EDB";
  final static String fmtname = "ERA001002";
  final int FIELDCOUNT = 51;
  private static Hashtable tlookup = new Hashtable();
  private CharacterField fieldH02USERID = null;
  private CharacterField fieldH02PROGRM = null;
  private CharacterField fieldH02TIMSYS = null;
  private CharacterField fieldH02SCRCOD = null;
  private CharacterField fieldH02OPECOD = null;
  private CharacterField fieldH02FLGMAS = null;
  private CharacterField fieldH02FLGWK1 = null;
  private CharacterField fieldH02FLGWK2 = null;
  private CharacterField fieldH02FLGWK3 = null;
  private CharacterField fieldE02RODBNK = null;
  private DecimalField fieldE02RODCUN = null;
  private DecimalField fieldE02RODREF = null;
  private DecimalField fieldE02RODSEQ = null;
  private CharacterField fieldE02RODSTS = null;
  private CharacterField fieldE02RODNBR = null;
  private CharacterField fieldE02RODDSC = null;
  private DecimalField fieldE02RODOD1 = null;
  private DecimalField fieldE02RODOD2 = null;
  private DecimalField fieldE02RODOD3 = null;
  private DecimalField fieldE02RODMD1 = null;
  private DecimalField fieldE02RODMD2 = null;
  private DecimalField fieldE02RODMD3 = null;
  private DecimalField fieldE02RODAMT = null;
  private CharacterField fieldE02RODFLG = null;
  private CharacterField fieldE02RODUC1 = null;
  private CharacterField fieldE02RODUC2 = null;
  private CharacterField fieldE02RODUC7 = null;
  private CharacterField fieldE02RODRF2 = null;
  private CharacterField fieldE02RODRF4 = null;
  private CharacterField fieldE02RODAIN = null;
  private CharacterField fieldF02RODBNK = null;
  private CharacterField fieldF02RODCUN = null;
  private CharacterField fieldF02RODREF = null;
  private CharacterField fieldF02RODSEQ = null;
  private CharacterField fieldF02RODSTS = null;
  private CharacterField fieldF02RODNBR = null;
  private CharacterField fieldF02RODDSC = null;
  private CharacterField fieldF02RODOD1 = null;
  private CharacterField fieldF02RODOD2 = null;
  private CharacterField fieldF02RODOD3 = null;
  private CharacterField fieldF02RODMD1 = null;
  private CharacterField fieldF02RODMD2 = null;
  private CharacterField fieldF02RODMD3 = null;
  private CharacterField fieldF02RODAMT = null;
  private CharacterField fieldF02RODFLG = null;
  private CharacterField fieldF02RODUC1 = null;
  private CharacterField fieldF02RODUC2 = null;
  private CharacterField fieldF02RODUC7 = null;
  private CharacterField fieldF02RODRF2 = null;
  private CharacterField fieldF02RODRF4 = null;
  private CharacterField fieldF02RODAIN = null;

  /**
  * Constructor for ERA001002Message.
  */
  public ERA001002Message()
  {
    createFields();
    initialize();
  }

  /**
  * Create fields for this message.
  * This method implements the abstract method in the MessageRecord superclass.
  */
  protected void createFields()
  {
    recordsize = 250;
    fileid = fid;
    recordid = rid;
    message = new byte[getByteLength()];
    formatname = fmtname;
    fieldnames = fldnames;
    tagnames = tnames;
    fields = new MessageField[FIELDCOUNT];

    fields[0] = fieldH02USERID =
    new CharacterField(message, HEADERSIZE + 0, 10, "H02USERID");
    fields[1] = fieldH02PROGRM =
    new CharacterField(message, HEADERSIZE + 10, 10, "H02PROGRM");
    fields[2] = fieldH02TIMSYS =
    new CharacterField(message, HEADERSIZE + 20, 12, "H02TIMSYS");
    fields[3] = fieldH02SCRCOD =
    new CharacterField(message, HEADERSIZE + 32, 2, "H02SCRCOD");
    fields[4] = fieldH02OPECOD =
    new CharacterField(message, HEADERSIZE + 34, 4, "H02OPECOD");
    fields[5] = fieldH02FLGMAS =
    new CharacterField(message, HEADERSIZE + 38, 1, "H02FLGMAS");
    fields[6] = fieldH02FLGWK1 =
    new CharacterField(message, HEADERSIZE + 39, 1, "H02FLGWK1");
    fields[7] = fieldH02FLGWK2 =
    new CharacterField(message, HEADERSIZE + 40, 1, "H02FLGWK2");
    fields[8] = fieldH02FLGWK3 =
    new CharacterField(message, HEADERSIZE + 41, 1, "H02FLGWK3");
    fields[9] = fieldE02RODBNK =
    new CharacterField(message, HEADERSIZE + 42, 2, "E02RODBNK");
    fields[10] = fieldE02RODCUN =
    new DecimalField(message, HEADERSIZE + 44, 10, 0, "E02RODCUN");
    fields[11] = fieldE02RODREF =
    new DecimalField(message, HEADERSIZE + 54, 13, 0, "E02RODREF");
    fields[12] = fieldE02RODSEQ =
    new DecimalField(message, HEADERSIZE + 67, 4, 0, "E02RODSEQ");
    fields[13] = fieldE02RODSTS =
    new CharacterField(message, HEADERSIZE + 71, 1, "E02RODSTS");
    fields[14] = fieldE02RODNBR =
    new CharacterField(message, HEADERSIZE + 72, 20, "E02RODNBR");
    fields[15] = fieldE02RODDSC =
    new CharacterField(message, HEADERSIZE + 92, 35, "E02RODDSC");
    fields[16] = fieldE02RODOD1 =
    new DecimalField(message, HEADERSIZE + 127, 3, 0, "E02RODOD1");
    fields[17] = fieldE02RODOD2 =
    new DecimalField(message, HEADERSIZE + 130, 3, 0, "E02RODOD2");
    fields[18] = fieldE02RODOD3 =
    new DecimalField(message, HEADERSIZE + 133, 3, 0, "E02RODOD3");
    fields[19] = fieldE02RODMD1 =
    new DecimalField(message, HEADERSIZE + 136, 3, 0, "E02RODMD1");
    fields[20] = fieldE02RODMD2 =
    new DecimalField(message, HEADERSIZE + 139, 3, 0, "E02RODMD2");
    fields[21] = fieldE02RODMD3 =
    new DecimalField(message, HEADERSIZE + 142, 3, 0, "E02RODMD3");
    fields[22] = fieldE02RODAMT =
    new DecimalField(message, HEADERSIZE + 145, 17, 2, "E02RODAMT");
    fields[23] = fieldE02RODFLG =
    new CharacterField(message, HEADERSIZE + 162, 1, "E02RODFLG");
    fields[24] = fieldE02RODUC1 =
    new CharacterField(message, HEADERSIZE + 163, 4, "E02RODUC1");
    fields[25] = fieldE02RODUC2 =
    new CharacterField(message, HEADERSIZE + 167, 4, "E02RODUC2");
    fields[26] = fieldE02RODUC7 =
    new CharacterField(message, HEADERSIZE + 171, 4, "E02RODUC7");
    fields[27] = fieldE02RODRF2 =
    new CharacterField(message, HEADERSIZE + 175, 20, "E02RODRF2");
    fields[28] = fieldE02RODRF4 =
    new CharacterField(message, HEADERSIZE + 195, 30, "E02RODRF4");
    fields[29] = fieldE02RODAIN =
    new CharacterField(message, HEADERSIZE + 225, 4, "E02RODAIN");
    fields[30] = fieldF02RODBNK =
    new CharacterField(message, HEADERSIZE + 229, 1, "F02RODBNK");
    fields[31] = fieldF02RODCUN =
    new CharacterField(message, HEADERSIZE + 230, 1, "F02RODCUN");
    fields[32] = fieldF02RODREF =
    new CharacterField(message, HEADERSIZE + 231, 1, "F02RODREF");
    fields[33] = fieldF02RODSEQ =
    new CharacterField(message, HEADERSIZE + 232, 1, "F02RODSEQ");
    fields[34] = fieldF02RODSTS =
    new CharacterField(message, HEADERSIZE + 233, 1, "F02RODSTS");
    fields[35] = fieldF02RODNBR =
    new CharacterField(message, HEADERSIZE + 234, 1, "F02RODNBR");
    fields[36] = fieldF02RODDSC =
    new CharacterField(message, HEADERSIZE + 235, 1, "F02RODDSC");
    fields[37] = fieldF02RODOD1 =
    new CharacterField(message, HEADERSIZE + 236, 1, "F02RODOD1");
    fields[38] = fieldF02RODOD2 =
    new CharacterField(message, HEADERSIZE + 237, 1, "F02RODOD2");
    fields[39] = fieldF02RODOD3 =
    new CharacterField(message, HEADERSIZE + 238, 1, "F02RODOD3");
    fields[40] = fieldF02RODMD1 =
    new CharacterField(message, HEADERSIZE + 239, 1, "F02RODMD1");
    fields[41] = fieldF02RODMD2 =
    new CharacterField(message, HEADERSIZE + 240, 1, "F02RODMD2");
    fields[42] = fieldF02RODMD3 =
    new CharacterField(message, HEADERSIZE + 241, 1, "F02RODMD3");
    fields[43] = fieldF02RODAMT =
    new CharacterField(message, HEADERSIZE + 242, 1, "F02RODAMT");
    fields[44] = fieldF02RODFLG =
    new CharacterField(message, HEADERSIZE + 243, 1, "F02RODFLG");
    fields[45] = fieldF02RODUC1 =
    new CharacterField(message, HEADERSIZE + 244, 1, "F02RODUC1");
    fields[46] = fieldF02RODUC2 =
    new CharacterField(message, HEADERSIZE + 245, 1, "F02RODUC2");
    fields[47] = fieldF02RODUC7 =
    new CharacterField(message, HEADERSIZE + 246, 1, "F02RODUC7");
    fields[48] = fieldF02RODRF2 =
    new CharacterField(message, HEADERSIZE + 247, 1, "F02RODRF2");
    fields[49] = fieldF02RODRF4 =
    new CharacterField(message, HEADERSIZE + 248, 1, "F02RODRF4");
    fields[50] = fieldF02RODAIN =
    new CharacterField(message, HEADERSIZE + 249, 1, "F02RODAIN");

    synchronized (tlookup)
    {
      if (tlookup.isEmpty())
      {
        for (int i = 0; i < tnames.length; i++)
          tlookup.put(tnames[i], new Integer(i));
      }
    }

    taglookup = tlookup;
  }

  /**
  * Set field H02USERID using a String value.
  */
  public void setH02USERID(String newvalue)
  {
    fieldH02USERID.setString(newvalue);
  }

  /**
  * Get value of field H02USERID as a String.
  */
  public String getH02USERID()
  {
    return fieldH02USERID.getString();
  }

  /**
  * Set field H02PROGRM using a String value.
  */
  public void setH02PROGRM(String newvalue)
  {
    fieldH02PROGRM.setString(newvalue);
  }

  /**
  * Get value of field H02PROGRM as a String.
  */
  public String getH02PROGRM()
  {
    return fieldH02PROGRM.getString();
  }

  /**
  * Set field H02TIMSYS using a String value.
  */
  public void setH02TIMSYS(String newvalue)
  {
    fieldH02TIMSYS.setString(newvalue);
  }

  /**
  * Get value of field H02TIMSYS as a String.
  */
  public String getH02TIMSYS()
  {
    return fieldH02TIMSYS.getString();
  }

  /**
  * Set field H02SCRCOD using a String value.
  */
  public void setH02SCRCOD(String newvalue)
  {
    fieldH02SCRCOD.setString(newvalue);
  }

  /**
  * Get value of field H02SCRCOD as a String.
  */
  public String getH02SCRCOD()
  {
    return fieldH02SCRCOD.getString();
  }

  /**
  * Set field H02OPECOD using a String value.
  */
  public void setH02OPECOD(String newvalue)
  {
    fieldH02OPECOD.setString(newvalue);
  }

  /**
  * Get value of field H02OPECOD as a String.
  */
  public String getH02OPECOD()
  {
    return fieldH02OPECOD.getString();
  }

  /**
  * Set field H02FLGMAS using a String value.
  */
  public void setH02FLGMAS(String newvalue)
  {
    fieldH02FLGMAS.setString(newvalue);
  }

  /**
  * Get value of field H02FLGMAS as a String.
  */
  public String getH02FLGMAS()
  {
    return fieldH02FLGMAS.getString();
  }

  /**
  * Set field H02FLGWK1 using a String value.
  */
  public void setH02FLGWK1(String newvalue)
  {
    fieldH02FLGWK1.setString(newvalue);
  }

  /**
  * Get value of field H02FLGWK1 as a String.
  */
  public String getH02FLGWK1()
  {
    return fieldH02FLGWK1.getString();
  }

  /**
  * Set field H02FLGWK2 using a String value.
  */
  public void setH02FLGWK2(String newvalue)
  {
    fieldH02FLGWK2.setString(newvalue);
  }

  /**
  * Get value of field H02FLGWK2 as a String.
  */
  public String getH02FLGWK2()
  {
    return fieldH02FLGWK2.getString();
  }

  /**
  * Set field H02FLGWK3 using a String value.
  */
  public void setH02FLGWK3(String newvalue)
  {
    fieldH02FLGWK3.setString(newvalue);
  }

  /**
  * Get value of field H02FLGWK3 as a String.
  */
  public String getH02FLGWK3()
  {
    return fieldH02FLGWK3.getString();
  }

  /**
  * Set field E02RODBNK using a String value.
  */
  public void setE02RODBNK(String newvalue)
  {
    fieldE02RODBNK.setString(newvalue);
  }

  /**
  * Get value of field E02RODBNK as a String.
  */
  public String getE02RODBNK()
  {
    return fieldE02RODBNK.getString();
  }

  /**
  * Set field E02RODCUN using a String value.
  */
  public void setE02RODCUN(String newvalue)
  {
    fieldE02RODCUN.setString(newvalue);
  }

  /**
  * Get value of field E02RODCUN as a String.
  */
  public String getE02RODCUN()
  {
    return fieldE02RODCUN.getString();
  }

  /**
  * Set numeric field E02RODCUN using a BigDecimal value.
  */
  public void setE02RODCUN(BigDecimal newvalue)
  {
    fieldE02RODCUN.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E02RODCUN as a BigDecimal.
  */
  public BigDecimal getBigDecimalE02RODCUN()
  {
    return fieldE02RODCUN.getBigDecimal();
  }

  /**
  * Set field E02RODREF using a String value.
  */
  public void setE02RODREF(String newvalue)
  {
    fieldE02RODREF.setString(newvalue);
  }

  /**
  * Get value of field E02RODREF as a String.
  */
  public String getE02RODREF()
  {
    return fieldE02RODREF.getString();
  }

  /**
  * Set numeric field E02RODREF using a BigDecimal value.
  */
  public void setE02RODREF(BigDecimal newvalue)
  {
    fieldE02RODREF.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E02RODREF as a BigDecimal.
  */
  public BigDecimal getBigDecimalE02RODREF()
  {
    return fieldE02RODREF.getBigDecimal();
  }

  /**
  * Set field E02RODSEQ using a String value.
  */
  public void setE02RODSEQ(String newvalue)
  {
    fieldE02RODSEQ.setString(newvalue);
  }

  /**
  * Get value of field E02RODSEQ as a String.
  */
  public String getE02RODSEQ()
  {
    return fieldE02RODSEQ.getString();
  }

  /**
  * Set numeric field E02RODSEQ using a BigDecimal value.
  */
  public void setE02RODSEQ(BigDecimal newvalue)
  {
    fieldE02RODSEQ.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E02RODSEQ as a BigDecimal.
  */
  public BigDecimal getBigDecimalE02RODSEQ()
  {
    return fieldE02RODSEQ.getBigDecimal();
  }

  /**
  * Set field E02RODSTS using a String value.
  */
  public void setE02RODSTS(String newvalue)
  {
    fieldE02RODSTS.setString(newvalue);
  }

  /**
  * Get value of field E02RODSTS as a String.
  */
  public String getE02RODSTS()
  {
    return fieldE02RODSTS.getString();
  }

  /**
  * Set field E02RODNBR using a String value.
  */
  public void setE02RODNBR(String newvalue)
  {
    fieldE02RODNBR.setString(newvalue);
  }

  /**
  * Get value of field E02RODNBR as a String.
  */
  public String getE02RODNBR()
  {
    return fieldE02RODNBR.getString();
  }

  /**
  * Set field E02RODDSC using a String value.
  */
  public void setE02RODDSC(String newvalue)
  {
    fieldE02RODDSC.setString(newvalue);
  }

  /**
  * Get value of field E02RODDSC as a String.
  */
  public String getE02RODDSC()
  {
    return fieldE02RODDSC.getString();
  }

  /**
  * Set field E02RODOD1 using a String value.
  */
  public void setE02RODOD1(String newvalue)
  {
    fieldE02RODOD1.setString(newvalue);
  }

  /**
  * Get value of field E02RODOD1 as a String.
  */
  public String getE02RODOD1()
  {
    return fieldE02RODOD1.getString();
  }

  /**
  * Set numeric field E02RODOD1 using a BigDecimal value.
  */
  public void setE02RODOD1(BigDecimal newvalue)
  {
    fieldE02RODOD1.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E02RODOD1 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE02RODOD1()
  {
    return fieldE02RODOD1.getBigDecimal();
  }

  /**
  * Set field E02RODOD2 using a String value.
  */
  public void setE02RODOD2(String newvalue)
  {
    fieldE02RODOD2.setString(newvalue);
  }

  /**
  * Get value of field E02RODOD2 as a String.
  */
  public String getE02RODOD2()
  {
    return fieldE02RODOD2.getString();
  }

  /**
  * Set numeric field E02RODOD2 using a BigDecimal value.
  */
  public void setE02RODOD2(BigDecimal newvalue)
  {
    fieldE02RODOD2.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E02RODOD2 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE02RODOD2()
  {
    return fieldE02RODOD2.getBigDecimal();
  }

  /**
  * Set field E02RODOD3 using a String value.
  */
  public void setE02RODOD3(String newvalue)
  {
    fieldE02RODOD3.setString(newvalue);
  }

  /**
  * Get value of field E02RODOD3 as a String.
  */
  public String getE02RODOD3()
  {
    return fieldE02RODOD3.getString();
  }

  /**
  * Set numeric field E02RODOD3 using a BigDecimal value.
  */
  public void setE02RODOD3(BigDecimal newvalue)
  {
    fieldE02RODOD3.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E02RODOD3 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE02RODOD3()
  {
    return fieldE02RODOD3.getBigDecimal();
  }

  /**
  * Set field E02RODMD1 using a String value.
  */
  public void setE02RODMD1(String newvalue)
  {
    fieldE02RODMD1.setString(newvalue);
  }

  /**
  * Get value of field E02RODMD1 as a String.
  */
  public String getE02RODMD1()
  {
    return fieldE02RODMD1.getString();
  }

  /**
  * Set numeric field E02RODMD1 using a BigDecimal value.
  */
  public void setE02RODMD1(BigDecimal newvalue)
  {
    fieldE02RODMD1.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E02RODMD1 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE02RODMD1()
  {
    return fieldE02RODMD1.getBigDecimal();
  }

  /**
  * Set field E02RODMD2 using a String value.
  */
  public void setE02RODMD2(String newvalue)
  {
    fieldE02RODMD2.setString(newvalue);
  }

  /**
  * Get value of field E02RODMD2 as a String.
  */
  public String getE02RODMD2()
  {
    return fieldE02RODMD2.getString();
  }

  /**
  * Set numeric field E02RODMD2 using a BigDecimal value.
  */
  public void setE02RODMD2(BigDecimal newvalue)
  {
    fieldE02RODMD2.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E02RODMD2 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE02RODMD2()
  {
    return fieldE02RODMD2.getBigDecimal();
  }

  /**
  * Set field E02RODMD3 using a String value.
  */
  public void setE02RODMD3(String newvalue)
  {
    fieldE02RODMD3.setString(newvalue);
  }

  /**
  * Get value of field E02RODMD3 as a String.
  */
  public String getE02RODMD3()
  {
    return fieldE02RODMD3.getString();
  }

  /**
  * Set numeric field E02RODMD3 using a BigDecimal value.
  */
  public void setE02RODMD3(BigDecimal newvalue)
  {
    fieldE02RODMD3.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E02RODMD3 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE02RODMD3()
  {
    return fieldE02RODMD3.getBigDecimal();
  }

  /**
  * Set field E02RODAMT using a String value.
  */
  public void setE02RODAMT(String newvalue)
  {
    fieldE02RODAMT.setString(newvalue);
  }

  /**
  * Get value of field E02RODAMT as a String.
  */
  public String getE02RODAMT()
  {
    return fieldE02RODAMT.getString();
  }

  /**
  * Set numeric field E02RODAMT using a BigDecimal value.
  */
  public void setE02RODAMT(BigDecimal newvalue)
  {
    fieldE02RODAMT.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E02RODAMT as a BigDecimal.
  */
  public BigDecimal getBigDecimalE02RODAMT()
  {
    return fieldE02RODAMT.getBigDecimal();
  }

  /**
  * Set field E02RODFLG using a String value.
  */
  public void setE02RODFLG(String newvalue)
  {
    fieldE02RODFLG.setString(newvalue);
  }

  /**
  * Get value of field E02RODFLG as a String.
  */
  public String getE02RODFLG()
  {
    return fieldE02RODFLG.getString();
  }

  /**
  * Set field E02RODUC1 using a String value.
  */
  public void setE02RODUC1(String newvalue)
  {
    fieldE02RODUC1.setString(newvalue);
  }

  /**
  * Get value of field E02RODUC1 as a String.
  */
  public String getE02RODUC1()
  {
    return fieldE02RODUC1.getString();
  }

  /**
  * Set field E02RODUC2 using a String value.
  */
  public void setE02RODUC2(String newvalue)
  {
    fieldE02RODUC2.setString(newvalue);
  }

  /**
  * Get value of field E02RODUC2 as a String.
  */
  public String getE02RODUC2()
  {
    return fieldE02RODUC2.getString();
  }

  /**
  * Set field E02RODUC7 using a String value.
  */
  public void setE02RODUC7(String newvalue)
  {
    fieldE02RODUC7.setString(newvalue);
  }

  /**
  * Get value of field E02RODUC7 as a String.
  */
  public String getE02RODUC7()
  {
    return fieldE02RODUC7.getString();
  }

  /**
  * Set field E02RODRF2 using a String value.
  */
  public void setE02RODRF2(String newvalue)
  {
    fieldE02RODRF2.setString(newvalue);
  }

  /**
  * Get value of field E02RODRF2 as a String.
  */
  public String getE02RODRF2()
  {
    return fieldE02RODRF2.getString();
  }

  /**
  * Set field E02RODRF4 using a String value.
  */
  public void setE02RODRF4(String newvalue)
  {
    fieldE02RODRF4.setString(newvalue);
  }

  /**
  * Get value of field E02RODRF4 as a String.
  */
  public String getE02RODRF4()
  {
    return fieldE02RODRF4.getString();
  }

  /**
  * Set field E02RODAIN using a String value.
  */
  public void setE02RODAIN(String newvalue)
  {
    fieldE02RODAIN.setString(newvalue);
  }

  /**
  * Get value of field E02RODAIN as a String.
  */
  public String getE02RODAIN()
  {
    return fieldE02RODAIN.getString();
  }

  /**
  * Set field F02RODBNK using a String value.
  */
  public void setF02RODBNK(String newvalue)
  {
    fieldF02RODBNK.setString(newvalue);
  }

  /**
  * Get value of field F02RODBNK as a String.
  */
  public String getF02RODBNK()
  {
    return fieldF02RODBNK.getString();
  }

  /**
  * Set field F02RODCUN using a String value.
  */
  public void setF02RODCUN(String newvalue)
  {
    fieldF02RODCUN.setString(newvalue);
  }

  /**
  * Get value of field F02RODCUN as a String.
  */
  public String getF02RODCUN()
  {
    return fieldF02RODCUN.getString();
  }

  /**
  * Set field F02RODREF using a String value.
  */
  public void setF02RODREF(String newvalue)
  {
    fieldF02RODREF.setString(newvalue);
  }

  /**
  * Get value of field F02RODREF as a String.
  */
  public String getF02RODREF()
  {
    return fieldF02RODREF.getString();
  }

  /**
  * Set field F02RODSEQ using a String value.
  */
  public void setF02RODSEQ(String newvalue)
  {
    fieldF02RODSEQ.setString(newvalue);
  }

  /**
  * Get value of field F02RODSEQ as a String.
  */
  public String getF02RODSEQ()
  {
    return fieldF02RODSEQ.getString();
  }

  /**
  * Set field F02RODSTS using a String value.
  */
  public void setF02RODSTS(String newvalue)
  {
    fieldF02RODSTS.setString(newvalue);
  }

  /**
  * Get value of field F02RODSTS as a String.
  */
  public String getF02RODSTS()
  {
    return fieldF02RODSTS.getString();
  }

  /**
  * Set field F02RODNBR using a String value.
  */
  public void setF02RODNBR(String newvalue)
  {
    fieldF02RODNBR.setString(newvalue);
  }

  /**
  * Get value of field F02RODNBR as a String.
  */
  public String getF02RODNBR()
  {
    return fieldF02RODNBR.getString();
  }

  /**
  * Set field F02RODDSC using a String value.
  */
  public void setF02RODDSC(String newvalue)
  {
    fieldF02RODDSC.setString(newvalue);
  }

  /**
  * Get value of field F02RODDSC as a String.
  */
  public String getF02RODDSC()
  {
    return fieldF02RODDSC.getString();
  }

  /**
  * Set field F02RODOD1 using a String value.
  */
  public void setF02RODOD1(String newvalue)
  {
    fieldF02RODOD1.setString(newvalue);
  }

  /**
  * Get value of field F02RODOD1 as a String.
  */
  public String getF02RODOD1()
  {
    return fieldF02RODOD1.getString();
  }

  /**
  * Set field F02RODOD2 using a String value.
  */
  public void setF02RODOD2(String newvalue)
  {
    fieldF02RODOD2.setString(newvalue);
  }

  /**
  * Get value of field F02RODOD2 as a String.
  */
  public String getF02RODOD2()
  {
    return fieldF02RODOD2.getString();
  }

  /**
  * Set field F02RODOD3 using a String value.
  */
  public void setF02RODOD3(String newvalue)
  {
    fieldF02RODOD3.setString(newvalue);
  }

  /**
  * Get value of field F02RODOD3 as a String.
  */
  public String getF02RODOD3()
  {
    return fieldF02RODOD3.getString();
  }

  /**
  * Set field F02RODMD1 using a String value.
  */
  public void setF02RODMD1(String newvalue)
  {
    fieldF02RODMD1.setString(newvalue);
  }

  /**
  * Get value of field F02RODMD1 as a String.
  */
  public String getF02RODMD1()
  {
    return fieldF02RODMD1.getString();
  }

  /**
  * Set field F02RODMD2 using a String value.
  */
  public void setF02RODMD2(String newvalue)
  {
    fieldF02RODMD2.setString(newvalue);
  }

  /**
  * Get value of field F02RODMD2 as a String.
  */
  public String getF02RODMD2()
  {
    return fieldF02RODMD2.getString();
  }

  /**
  * Set field F02RODMD3 using a String value.
  */
  public void setF02RODMD3(String newvalue)
  {
    fieldF02RODMD3.setString(newvalue);
  }

  /**
  * Get value of field F02RODMD3 as a String.
  */
  public String getF02RODMD3()
  {
    return fieldF02RODMD3.getString();
  }

  /**
  * Set field F02RODAMT using a String value.
  */
  public void setF02RODAMT(String newvalue)
  {
    fieldF02RODAMT.setString(newvalue);
  }

  /**
  * Get value of field F02RODAMT as a String.
  */
  public String getF02RODAMT()
  {
    return fieldF02RODAMT.getString();
  }

  /**
  * Set field F02RODFLG using a String value.
  */
  public void setF02RODFLG(String newvalue)
  {
    fieldF02RODFLG.setString(newvalue);
  }

  /**
  * Get value of field F02RODFLG as a String.
  */
  public String getF02RODFLG()
  {
    return fieldF02RODFLG.getString();
  }

  /**
  * Set field F02RODUC1 using a String value.
  */
  public void setF02RODUC1(String newvalue)
  {
    fieldF02RODUC1.setString(newvalue);
  }

  /**
  * Get value of field F02RODUC1 as a String.
  */
  public String getF02RODUC1()
  {
    return fieldF02RODUC1.getString();
  }

  /**
  * Set field F02RODUC2 using a String value.
  */
  public void setF02RODUC2(String newvalue)
  {
    fieldF02RODUC2.setString(newvalue);
  }

  /**
  * Get value of field F02RODUC2 as a String.
  */
  public String getF02RODUC2()
  {
    return fieldF02RODUC2.getString();
  }

  /**
  * Set field F02RODUC7 using a String value.
  */
  public void setF02RODUC7(String newvalue)
  {
    fieldF02RODUC7.setString(newvalue);
  }

  /**
  * Get value of field F02RODUC7 as a String.
  */
  public String getF02RODUC7()
  {
    return fieldF02RODUC7.getString();
  }

  /**
  * Set field F02RODRF2 using a String value.
  */
  public void setF02RODRF2(String newvalue)
  {
    fieldF02RODRF2.setString(newvalue);
  }

  /**
  * Get value of field F02RODRF2 as a String.
  */
  public String getF02RODRF2()
  {
    return fieldF02RODRF2.getString();
  }

  /**
  * Set field F02RODRF4 using a String value.
  */
  public void setF02RODRF4(String newvalue)
  {
    fieldF02RODRF4.setString(newvalue);
  }

  /**
  * Get value of field F02RODRF4 as a String.
  */
  public String getF02RODRF4()
  {
    return fieldF02RODRF4.getString();
  }

  /**
  * Set field F02RODAIN using a String value.
  */
  public void setF02RODAIN(String newvalue)
  {
    fieldF02RODAIN.setString(newvalue);
  }

  /**
  * Get value of field F02RODAIN as a String.
  */
  public String getF02RODAIN()
  {
    return fieldF02RODAIN.getString();
  }

}
